DENDRO: ot::TNPoint< T, dim > Class Template Reference
ot::TNPoint< T, dim > Class Template Reference
TreeNode + extra attributes to keep track of node uniqueness.
#include <nsort.h>
Public Member Functions
CellType< dim > get_cellType (LevI lev) const
Get type of cell to which point is interior, at arbitrary level.
unsigned int get_lexNodeRank (const TreeNode< T, dim > &hostCell, unsigned int polyOrder) const
Assuming nodes on a cell are ordered lexicographically, get the rank of this node on the given cell.
int get_owner () const
bool getIsCancellation () const
bool operator!= (TNPoint const &that) const
Compares level and full coordinates, disregarding selection status.
TNPoint & operator= (TNPoint const &other)
Assignment operator. No checks for dim or maxD are performed. It's ok to change dim and maxD of the object using the assignment operator.
bool operator== (TNPoint const &that) const
Compares level and full coordinates, disregarding selection status.
void set_owner (int owner)
void setIsCancellation (bool isCancellation)
TNPoint ()
Constructs a node at the extreme "lower-left" corner of the domain.
TNPoint (const std::array< T, dim > coords, unsigned int level)
Constructs a point.
TNPoint (const TNPoint &other)
Copy constructor.
Public Member Functions inherited from ot::TreeNode< T, dim >
void appendAllNeighbours (std::vector< TreeNode > &nodeList) const
Append in-bounds neighbors of node to node list.
void appendCoarseNeighbours (std::vector< TreeNode > &nodeList) const
const periodic::PCoord< T, dim > & coords () const
TreeNode getAncestor (unsigned int ancLev) const
int getAnchor (std::array< T, dim > &xyz) const
get the coordinates of the octant
std::array< char, MAX_LEVEL+1 > getBase32Hex (unsigned int lev=0) const
TreeNode getChildMorton (unsigned char child) const
return a child of this octant with the given child number.
unsigned int getCommonAncestorDepth (const TreeNode &other) const
Returns the greatest depth at which the other node shares an ancestor.
TreeNode getDFD () const
TreeNode getDLD () const
TreeNode getFirstChildMorton () const
return the smallest (in morton id) of this octant
bool getIsOnTreeBdry () const
unsigned int getLevel () const
return the level of the octant
unsigned int getMaxDepth () const
returns the max depth
unsigned char getMortonIndex (T level) const
return the (Morton indexed) child number at specified level.
unsigned char getMortonIndex () const
return the (Morton indexed) child number at the node's own level.
TreeNode getParent () const
T getX (int d) const
return the coordinates of the dth dimention
const std::array< T, dim > & getX () const
bool isAncestor (const TreeNode &other) const
Checks if this octant is an ancestor of the input.
bool isAncestorInclusive (const TreeNode &other) const
bool isRoot () const
returns true if *(this) octant is root. false otherwise
T lowerBound (int d) const
lower bound of the d dimension
bool operator!= (TreeNode const &other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
TreeNode & operator= (TreeNode const &other)=default
Assignment operator. No checks for dim or maxD are performed. It's ok to change dim and maxD of the current octant using the assignment operator.
bool operator== (TreeNode const &other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
const periodic::PRange< T, dim > range () const
void setIsOnTreeBdry (bool isOnTreeBdry)
void setLevel (unsigned int lev)
set the level of the octant
void setMortonIndex (unsigned char child)
set the last digit (at node's level) in each component of the anchor.
void setX (int d, T coord)
set the coordinate in the dth dimension
void setX (const std::array< T, dim > &coords)
TreeNode ()
Constructs a root octant.
TreeNode (const std::array< T, dim > coords, unsigned int level)
Constructs an octant.
TreeNode (const TreeNode &other)=default
Copy constructor.
T upperBound (int d) const
upper bound of the d dimension, not mapped periodic
Static Public Member Functions
static CellType< dim > get_cellType (const TreeNode< T, dim > &tnPoint, LevI lev)
static unsigned int get_lexNodeRank (const TreeNode< T, dim > &hostCell, const TreeNode< T, dim > &tnPoint, unsigned int polyOrder)
Assuming nodes on a cell are ordered lexicographically, get the rank of given node on the given cell.
static unsigned int get_nodeRank1D (const TreeNode< T, dim > &hostCell, const TreeNode< T, dim > &tnPoint, unsigned int d, unsigned int polyOrder)
static std::array< unsigned, dim > get_nodeRanks1D (const TreeNode< T, dim > &hostCell, const TreeNode< T, dim > &tnPoint, unsigned int polyOrder)
static void get_relNodeCoords (const TreeNode< T, dim > &containingSubtree, const TreeNode< T, dim > &tnPoint, unsigned int polyOrder, std::array< unsigned int, dim > &numerators, unsigned int &denominator)
Protected Attributes
bool m_isCancellation = false
int m_owner = -1
Protected Attributes inherited from ot::TreeNode< T, dim >
periodic::PCoord< T, dim > m_coords
bool m_isOnTreeBdry
unsigned int m_uiLevel
Additional Inherited Members
Public Types inherited from ot::TreeNode< T, dim >
using coordType = T
Protected Member Functions inherited from ot::TreeNode< T, dim >
TreeNode (const int dummy, const std::array< T, dim > coords, unsigned int level)
Constructs an octant.
Detailed Description
template<typename T, unsigned int dim>
class ot::TNPoint< T, dim >
TreeNode + extra attributes to keep track of node uniqueness.
Definition at line 79 of file nsort.h.
Constructor & Destructor Documentation
TNPoint() [1/3]
template<typename T, unsigned int dim> ot::TNPoint< T, dim >::TNPoint ()
Constructs a node at the extreme "lower-left" corner of the domain.
TNPoint() [2/3]
template<typename T, unsigned int dim> ot::TNPoint< T, dim >::TNPoint (const std::array< T, dim > coords, unsigned int level)
Constructs a point.
Parameters
coords The coordinates of the point.
level The level of the point (i.e. level of the element that spawned it).
Note
Uses the "dummy" overload of TreeNode() so that the coordinates are copied as-is.
TNPoint() [3/3]
template<typename T, unsigned int dim> ot::TNPoint< T, dim >::TNPoint (const TNPoint< T, dim > & other)
Copy constructor.
Member Function Documentation
get_cellType() [1/2]
template<typename T, unsigned int dim> CellType<dim> ot::TNPoint< T, dim >::get_cellType (LevI lev) const
Get type of cell to which point is interior, at arbitrary level.
long get_globId() const { return m_globId; } void set_globId(long globId) { m_globId = globId; }
get_cellType() [2/2]
template<typename T, unsigned int dim> static CellType<dim> ot::TNPoint< T, dim >::get_cellType (const TreeNode< T, dim > & tnPoint, LevI lev) static
get_lexNodeRank() [1/2]
template<typename T, unsigned int dim> unsigned int ot::TNPoint< T, dim >::get_lexNodeRank (const TreeNode< T, dim > & hostCell, unsigned int polyOrder) const
Assuming nodes on a cell are ordered lexicographically, get the rank of this node on the given cell.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
get_lexNodeRank() [2/2]
template<typename T, unsigned int dim> static unsigned int ot::TNPoint< T, dim >::get_lexNodeRank (const TreeNode< T, dim > & hostCell, const TreeNode< T, dim > & tnPoint, unsigned int polyOrder) static
Assuming nodes on a cell are ordered lexicographically, get the rank of given node on the given cell.
get_nodeRank1D()
template<typename T, unsigned int dim> static unsigned int ot::TNPoint< T, dim >::get_nodeRank1D (const TreeNode< T, dim > & hostCell, const TreeNode< T, dim > & tnPoint, unsigned int d, unsigned int polyOrder) static
Referenced by ot::treeNode2Physical().
get_nodeRanks1D()
template<typename T, unsigned int dim> static std::array<unsigned, dim> ot::TNPoint< T, dim >::get_nodeRanks1D (const TreeNode< T, dim > & hostCell, const TreeNode< T, dim > & tnPoint, unsigned int polyOrder) static
get_owner()
template<typename T, unsigned int dim> int ot::TNPoint< T, dim >::get_owner () const inline
Definition at line 110 of file nsort.h.
get_relNodeCoords()
template<typename T, unsigned int dim> static void ot::TNPoint< T, dim >::get_relNodeCoords (const TreeNode< T, dim > & containingSubtree, const TreeNode< T, dim > & tnPoint, unsigned int polyOrder, std::array< unsigned int, dim > & numerators, unsigned int & denominator) static
Referenced by ot::fillAccessNodeCoordsFlat().
getIsCancellation()
template<typename T, unsigned int dim> bool ot::TNPoint< T, dim >::getIsCancellation () const
operator!=()
template<typename T, unsigned int dim> bool ot::TNPoint< T, dim >::operator!= (TNPoint< T, dim > const & that) const
Compares level and full coordinates, disregarding selection status.
operator=()
template<typename T, unsigned int dim> TNPoint& ot::TNPoint< T, dim >::operator= (TNPoint< T, dim > const & other)
Assignment operator. No checks for dim or maxD are performed. It's ok to change dim and maxD of the object using the assignment operator.
operator==()
template<typename T, unsigned int dim> bool ot::TNPoint< T, dim >::operator== (TNPoint< T, dim > const & that) const
Compares level and full coordinates, disregarding selection status.
set_owner()
template<typename T, unsigned int dim> void ot::TNPoint< T, dim >::set_owner (int owner) inline
Definition at line 111 of file nsort.h.
setIsCancellation()
template<typename T, unsigned int dim> void ot::TNPoint< T, dim >::setIsCancellation (bool isCancellation)
Member Data Documentation
m_isCancellation
template<typename T, unsigned int dim> bool ot::TNPoint< T, dim >::m_isCancellation = false protected
Definition at line 147 of file nsort.h.
m_owner
template<typename T, unsigned int dim> int ot::TNPoint< T, dim >::m_owner = -1 protected
Definition at line 143 of file nsort.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/nsort.h