DENDRO: ot::MatvecBaseCoords< dim > Class Template Reference
ot::MatvecBaseCoords< dim > Class Template Reference
#include <sfcTreeLoop_matvec_io.h>
Classes
struct AccessSubtree
Public Types
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords >
Public Types inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
using C = unsigned int
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
using SubtreeInfoT = SubtreeInfo< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
Public Member Functions
bool isLeaf () const
bool isLeafOrLower () const
MatvecBaseCoords ()=delete
MatvecBaseCoords (size_t numNodes, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > *allNodeCoords, const TreeNode< unsigned int, dim > *treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > &firstElement, const TreeNode< unsigned int, dim > &lastElement)
AccessSubtree subtreeInfo ()
Public Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
MatvecBaseCoords< dim > & asConcreteType ()
const TreeNode< C, dim > & getCurrentSubtree () const
SubtreeInfoT getSubtreeInfo ()
bool isFinished () const
bool isPre () const
bool next ()
void reset ()
bool step ()
Static Public Attributes
static constexpr unsigned int NumChildren = 1u << dim
Static Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
static constexpr unsigned int NumChildren
Protected Member Functions
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
void fillAccessNodeCoordsFlat ()
void fillLeafNodeBdry ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
const FrameT & getCurrentFrame () const
FrameT & getCurrentFrame ()
SFC_State< dim > getCurrentRotation () const
const FrameT & getRootFrame () const
FrameT & getRootFrame ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
SFC_TreeLoop (const TreeNode< C, dim > *sortedTreePart, size_t localTreeSz, unsigned int max_depth)
SFC_TreeLoop ()=delete
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Static Protected Member Functions
static MatvecBaseSummary< dim > generate_node_summary (const TreeNode< unsigned int, dim > *begin, const TreeNode< unsigned int, dim > *end)
static unsigned int get_max_depth (const TreeNode< unsigned int, dim > *begin, size_t numNodes)
static const std::vector< bool > & getNodeNonhangingIn (const FrameT &frame)
static std::vector< bool > & getNodeNonhangingIn (FrameT &frame)
Protected Attributes
std::vector< double > m_accessNodeCoordsFlat
unsigned int m_eleOrder
std::vector< bool > m_leafNodeBdry
std::vector< bool > m_parentNodeBdry
bool m_visitEmpty
Protected Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
FrameInputs< dim, Inputs< TreeNode< unsigned int, dim >, bool > >::DataStoreT m_rootInputData
FrameOutputs< dim, Outputs<> >::DataStoreT m_rootOutputData
MatvecBaseSummary< dim > m_rootSummary
std::array< RankI,(1u<< dim)+1 > m_rootTreeSplitters
std::vector< FrameT > m_stack
const TreeNode< C, dim > * m_treePartPtr
Friends
void fillLeafNodeBdry (const FrameT &, unsigned int, const std::vector< bool > &, std::vector< bool > &)
Additional Inherited Members
Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >
friend SubtreeInfoT
Detailed Description
template<unsigned int dim>
class ot::MatvecBaseCoords< dim >
Definition at line 111 of file sfcTreeLoop_matvec_io.h.
Member Typedef Documentation
FrameT
template<unsigned int dim> using ot::MatvecBaseCoords< dim >::FrameT = Frame<dim, Inputs<TreeNode<unsigned int, dim>, bool>, Outputs<>, MatvecBaseSummary<dim>, MatvecBaseCoords>
Definition at line 125 of file sfcTreeLoop_matvec_io.h.
Constructor & Destructor Documentation
MatvecBaseCoords() [1/2]
template<unsigned int dim> ot::MatvecBaseCoords< dim >::MatvecBaseCoords () delete
MatvecBaseCoords() [2/2]
template<unsigned int dim> ot::MatvecBaseCoords< dim >::MatvecBaseCoords (size_t numNodes, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > * allNodeCoords, const TreeNode< unsigned int, dim > * treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > & firstElement, const TreeNode< unsigned int, dim > & lastElement)
Definition at line 695 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::generate_node_summary(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getRootFrame(), intPow(), ot::MatvecBaseCoords< dim >::m_eleOrder, ot::MatvecBaseCoords< dim >::m_parentNodeBdry, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Member Function Documentation
bottomUpNodes()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::bottomUpNodes (FrameT & parentFrame, ExtantCellFlagT extantChildren) inline protected
Definition at line 236 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower().
child2Parent()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::child2Parent (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 238 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::generate_node_summary(), and ot::MatvecBaseCoords< dim >::get_max_depth().
fillAccessNodeCoordsFlat()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat () protected
Definition at line 1963 of file sfcTreeLoop_matvec_io.h.
References ot::fillAccessNodeCoordsFlat(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_accessNodeCoordsFlat, and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::get_max_depth(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNodeCoords(), ot::MatvecBaseCoords< dim >::getNodeNonhangingIn(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::getNodeNonhangingIn().
fillLeafNodeBdry()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::fillLeafNodeBdry () inline protected
Definition at line 260 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::m_eleOrder, ot::MatvecBaseCoords< dim >::m_leafNodeBdry, and ot::MatvecBaseCoords< dim >::m_parentNodeBdry.
generate_node_summary()
template<unsigned int dim> MatvecBaseSummary< dim > ot::MatvecBaseCoords< dim >::generate_node_summary (const TreeNode< unsigned int, dim > * begin, const TreeNode< unsigned int, dim > * end) static protected
Definition at line 2001 of file sfcTreeLoop_matvec_io.h.
References ot::TreeNode< T, dim >::getIsOnTreeBdry(), ot::TreeNode< T, dim >::getLevel(), ot::MatvecBaseSummary< dim >::m_haveHanging, ot::MatvecBaseSummary< dim >::m_numBdryNodes, ot::MatvecBaseSummary< dim >::m_subtreeFinestLevel, and ot::MatvecBaseSummary< dim >::m_subtreeNodeCount.
Referenced by ot::MatvecBaseCoords< dim >::child2Parent(), and ot::MatvecBaseCoords< dim >::MatvecBaseCoords().
get_max_depth()
template<unsigned int dim> unsigned int ot::MatvecBaseCoords< dim >::get_max_depth (const TreeNode< unsigned int, dim > * begin, size_t numNodes) static protected
Definition at line 2028 of file sfcTreeLoop_matvec_io.h.
References ot::TreeNode< T, dim >::getLevel().
Referenced by ot::MatvecBaseCoords< dim >::child2Parent().
getNodeNonhangingIn() [1/2]
template<unsigned int dim> static const std::vector<bool>& ot::MatvecBaseCoords< dim >::getNodeNonhangingIn (const FrameT & frame) inline static protected
Definition at line 250 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::readNodeNonhangingIn().
getNodeNonhangingIn() [2/2]
template<unsigned int dim> static std::vector<bool>& ot::MatvecBaseCoords< dim >::getNodeNonhangingIn (FrameT & frame) inline static protected
Definition at line 254 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat().
isLeaf()
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::isLeaf () const inline
Definition at line 223 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::isLeaf().
isLeafOrLower()
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::isLeafOrLower () const inline
Definition at line 228 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, and ot::MatvecBaseCoords< dim >::topDownNodes().
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::isLeafOrLower().
parent2Child()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::parent2Child (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 237 of file sfcTreeLoop_matvec_io.h.
subtreeInfo()
template<unsigned int dim> AccessSubtree ot::MatvecBaseCoords< dim >::subtreeInfo () inline
Definition at line 213 of file sfcTreeLoop_matvec_io.h.
topDownNodes()
template<unsigned int dim> void ot::MatvecBaseCoords< dim >::topDownNodes (FrameT & parentFrame, ExtantCellFlagT * extantChildren) protected
Copied from sfcTreeLoop.h:
topDownNodes() is responsible to
Resize the child input buffers (SFC order) in the parent frame;
Duplicate elements of the parent input buffers to incident child input buffers (SFC order);
2.1. Initialize a summary object for each child (SFC order).
Indicate to SFC_TreeLoop which children to traverse, by accumulating into the extantChildren bit array (Morton order).
Restrictions
MAY NOT resize or write to parent input buffers.
MAY NOT resize or write to variably sized output buffers.
Utilities are provided to identify and iterate over incident children.
ExtantCellFlagT iterateChildren = (m_visitEmpty ? segmentChildren : *extantChildren);
assert(parentFrame.template getChildInput<0>(child_sfc)[nodeRank] == myNodes[nIdx]);
*extantChildren = segmentChildren;
Definition at line 908 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getExtantTreeChildrenMorton(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeBdry, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_visitEmpty, ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, ot::nchild(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::NumChildren.
Referenced by ot::MatvecBaseCoords< dim >::isLeafOrLower(), ot::MatvecBaseIn< dim, NodeT, p2c >::isLeafOrLower(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower().
Friends And Related Function Documentation
fillLeafNodeBdry
template<unsigned int dim> void fillLeafNodeBdry (const FrameT & , unsigned int, const std::vector< bool > & , std::vector< bool > &) friend
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::getLeafNodeBdry().
Member Data Documentation
m_accessNodeCoordsFlat
template<unsigned int dim> std::vector<double> ot::MatvecBaseCoords< dim >::m_accessNodeCoordsFlat protected
Definition at line 270 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::getNodeCoords().
m_eleOrder
template<unsigned int dim> unsigned int ot::MatvecBaseCoords< dim >::m_eleOrder protected
Definition at line 262 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::fillLeafNodeBdry(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillLeafNodeBdry(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillLeafNodeBdry(), ot::MatvecBaseCoords< dim >::AccessSubtree::getEleOrder(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNodesPerElement(), and ot::MatvecBaseCoords< dim >::MatvecBaseCoords().
m_leafNodeBdry
template<unsigned int dim> std::vector<bool> ot::MatvecBaseCoords< dim >::m_leafNodeBdry protected
Definition at line 267 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::fillLeafNodeBdry(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillLeafNodeBdry(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillLeafNodeBdry(), and ot::MatvecBaseCoords< dim >::AccessSubtree::getLeafNodeBdry().
m_parentNodeBdry
template<unsigned int dim> std::vector<bool> ot::MatvecBaseCoords< dim >::m_parentNodeBdry protected
Definition at line 268 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::fillLeafNodeBdry(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillLeafNodeBdry(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillLeafNodeBdry(), and ot::MatvecBaseCoords< dim >::MatvecBaseCoords().
m_visitEmpty
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::m_visitEmpty protected
Definition at line 264 of file sfcTreeLoop_matvec_io.h.
NumChildren
template<unsigned int dim> constexpr unsigned int ot::MatvecBaseCoords< dim >::NumChildren = 1u << dim static
Definition at line 127 of file sfcTreeLoop_matvec_io.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h