DENDRO: ot::MatvecBaseOut< dim, NodeT, UseAccumulation > Class Template Reference
ot::MatvecBaseOut< dim, NodeT, UseAccumulation > Class Template Reference
#include <sfcTreeLoop_matvec_io.h>
Classes
struct AccessSubtree
Public Types
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut >
Public Types inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
using C = unsigned int
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
using SubtreeInfoT = SubtreeInfo< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
Public Member Functions
size_t finalize (NodeT *outputNodeVals, char *outputIsDirty=nullptr) const
bool isLeaf () const
bool isLeafOrLower () const
MatvecBaseOut ()=delete
MatvecBaseOut (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > *allNodeCoords, const TreeNode< unsigned int, dim > *treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > &firstElement, const TreeNode< unsigned int, dim > &lastElement)
AccessSubtree subtreeInfo ()
Public Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
MatvecBaseOut< dim, NodeT, UseAccumulation > & asConcreteType ()
const TreeNode< C, dim > & getCurrentSubtree () const
SubtreeInfoT getSubtreeInfo ()
bool isFinished () const
bool isPre () const
bool next ()
void reset ()
bool step ()
Static Public Attributes
static constexpr unsigned int NumChildren = 1u << dim
Static Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
static constexpr unsigned int NumChildren
Protected Member Functions
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
void fillAccessNodeCoordsFlat ()
void fillLeafNodeBdry ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
const FrameT & getCurrentFrame () const
FrameT & getCurrentFrame ()
SFC_State< dim > getCurrentRotation () const
const FrameT & getRootFrame () const
FrameT & getRootFrame ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
SFC_TreeLoop (const TreeNode< C, dim > *sortedTreePart, size_t localTreeSz, unsigned int max_depth)
SFC_TreeLoop ()=delete
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Static Protected Member Functions
static MatvecBaseSummary< dim > generate_node_summary (const TreeNode< unsigned int, dim > *begin, const TreeNode< unsigned int, dim > *end)
static unsigned int get_max_depth (const TreeNode< unsigned int, dim > *begin, size_t numNodes)
static const std::vector< bool > & getNodeNonhangingIn (const FrameT &frame)
static std::vector< bool > & getNodeNonhangingIn (FrameT &frame)
Protected Attributes
std::vector< double > m_accessNodeCoordsFlat
unsigned int m_eleOrder
InterpMatrices< dim, NodeT > m_interp_matrices
InterpMatrices< dim, char > m_interp_matrices_logical
std::vector< bool > m_leafNodeBdry
unsigned int m_ndofs
std::vector< bool > m_parentNodeBdry
std::vector< NodeT > m_parentNodeVals
bool m_visitEmpty
Protected Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
FrameInputs< dim, Inputs< TreeNode< unsigned int, dim >, bool > >::DataStoreT m_rootInputData
FrameOutputs< dim, Outputs< NodeT, char > >::DataStoreT m_rootOutputData
MatvecBaseSummary< dim > m_rootSummary
std::array< RankI,(1u<< dim)+1 > m_rootTreeSplitters
std::vector< FrameT > m_stack
const TreeNode< C, dim > * m_treePartPtr
Friends
void fillLeafNodeBdry (const FrameT &, unsigned int, const std::vector< bool > &, std::vector< bool > &)
Additional Inherited Members
Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >
friend SubtreeInfoT
Detailed Description
template<unsigned int dim, typename NodeT, bool UseAccumulation>
class ot::MatvecBaseOut< dim, NodeT, UseAccumulation >
Definition at line 468 of file sfcTreeLoop_matvec_io.h.
Member Typedef Documentation
FrameT
template<unsigned int dim, typename NodeT , bool UseAccumulation> using ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::FrameT = Frame<dim, Inputs<TreeNode<unsigned int, dim>, bool>, Outputs<NodeT, char>, MatvecBaseSummary<dim>, MatvecBaseOut>
Definition at line 482 of file sfcTreeLoop_matvec_io.h.
Constructor & Destructor Documentation
MatvecBaseOut() [1/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut () delete
MatvecBaseOut() [2/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > * allNodeCoords, const TreeNode< unsigned int, dim > * treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > & firstElement, const TreeNode< unsigned int, dim > & lastElement)
Definition at line 814 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::generate_node_summary(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getRootFrame(), intPow(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeBdry, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeVals, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Member Function Documentation
bottomUpNodes()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes (FrameT & parentFrame, ExtantCellFlagT extantChildren) protected
Copied from sfcTreeLoop.h:
bottomUpNodes() is responsible to
Resize the parent output buffers (handles to buffers are given);
Merge results from incident child output buffers (SFC order) into the parent output buffers.
The previously indicated extantChildren bit array (Morton order) will be supplied.
Utilities are provided to identify and iterate over incident children.
const size_t numParentNodes = parentFrame.mySummaryHandle.m_subtreeNodeCount; // Assumes parent is never leaf.
Definition at line 1684 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_interp_matrices, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_interp_matrices_logical, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeVals, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_visitEmpty, ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, ot::nchild(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::NumChildren.
child2Parent()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::child2Parent (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 644 of file sfcTreeLoop_matvec_io.h.
fillAccessNodeCoordsFlat()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat () protected
Definition at line 1986 of file sfcTreeLoop_matvec_io.h.
References ot::fillAccessNodeCoordsFlat(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_accessNodeCoordsFlat, and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodeCoords().
fillLeafNodeBdry()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillLeafNodeBdry () inline protected
Definition at line 672 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::m_eleOrder, ot::MatvecBaseCoords< dim >::m_leafNodeBdry, and ot::MatvecBaseCoords< dim >::m_parentNodeBdry.
finalize()
template<unsigned int dim, typename NodeT , bool UseAccumulation> size_t ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::finalize (NodeT * outputNodeVals, char * outputIsDirty = nullptr) const
Definition at line 875 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getRootFrame(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
generate_node_summary()
template<unsigned int dim, typename NodeT , bool UseAccumulation> static MatvecBaseSummary<dim> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::generate_node_summary (const TreeNode< unsigned int, dim > * begin, const TreeNode< unsigned int, dim > * end) inline static protected
Definition at line 646 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBase< dim, NodeT >::generate_node_summary().
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut().
get_max_depth()
template<unsigned int dim, typename NodeT , bool UseAccumulation> static unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::get_max_depth (const TreeNode< unsigned int, dim > * begin, size_t numNodes) inline static protected
Definition at line 653 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBase< dim, NodeT >::get_max_depth().
getNodeNonhangingIn() [1/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> static const std::vector<bool>& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::getNodeNonhangingIn (const FrameT & frame) inline static protected
Definition at line 662 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeNonhangingIn().
getNodeNonhangingIn() [2/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> static std::vector<bool>& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::getNodeNonhangingIn (FrameT & frame) inline static protected
Definition at line 666 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat().
isLeaf()
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeaf () const inline
Definition at line 629 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower () const inline
Definition at line 634 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::bottomUpNodes(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, and ot::MatvecBaseCoords< dim >::topDownNodes().
Referenced by ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isLeafOrLower(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
parent2Child()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::parent2Child (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 643 of file sfcTreeLoop_matvec_io.h.
subtreeInfo()
template<unsigned int dim, typename NodeT , bool UseAccumulation> AccessSubtree ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::subtreeInfo () inline
Definition at line 619 of file sfcTreeLoop_matvec_io.h.
topDownNodes()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes (FrameT & parentFrame, ExtantCellFlagT * extantChildren) protected
Copied from sfcTreeLoop.h:
topDownNodes() is responsible to
Resize the child input buffers (SFC order) in the parent frame;
Duplicate elements of the parent input buffers to incident child input buffers (SFC order);
2.1. Initialize a summary object for each child (SFC order).
Indicate to SFC_TreeLoop which children to traverse, by accumulating into the extantChildren bit array (Morton order).
Restrictions
MAY NOT resize or write to parent input buffers.
MAY NOT resize or write to variably sized output buffers.
Utilities are provided to identify and iterate over incident children.
assert(parentFrame.template getChildInput<0>(child_sfc)[nodeRank] == myNodes[nIdx]);
*extantChildren = segmentChildren;
Definition at line 1456 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getExtantTreeChildrenMorton(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeBdry, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_visitEmpty, ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, ot::nchild(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::NumChildren.
Friends And Related Function Documentation
fillLeafNodeBdry
template<unsigned int dim, typename NodeT , bool UseAccumulation> void fillLeafNodeBdry (const FrameT & , unsigned int, const std::vector< bool > & , std::vector< bool > &) friend
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getLeafNodeBdry().
Member Data Documentation
m_accessNodeCoordsFlat
template<unsigned int dim, typename NodeT , bool UseAccumulation> std::vector<double> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_accessNodeCoordsFlat protected
Definition at line 684 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodeCoords().
m_eleOrder
template<unsigned int dim, typename NodeT , bool UseAccumulation> unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder protected
Definition at line 675 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getEleOrder(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodesPerElement(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
m_interp_matrices
template<unsigned int dim, typename NodeT , bool UseAccumulation> InterpMatrices<dim, NodeT> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_interp_matrices protected
Definition at line 686 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), and ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes().
m_interp_matrices_logical
template<unsigned int dim, typename NodeT , bool UseAccumulation> InterpMatrices<dim, char> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_interp_matrices_logical protected
Definition at line 687 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes().
m_leafNodeBdry
template<unsigned int dim, typename NodeT , bool UseAccumulation> std::vector<bool> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_leafNodeBdry protected
Definition at line 681 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getLeafNodeBdry().
m_ndofs
template<unsigned int dim, typename NodeT , bool UseAccumulation> unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs protected
Definition at line 674 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::finalize(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNdofs(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOut(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOutScalar(), and ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes().
m_parentNodeBdry
template<unsigned int dim, typename NodeT , bool UseAccumulation> std::vector<bool> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeBdry protected
Definition at line 682 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
m_parentNodeVals
template<unsigned int dim, typename NodeT , bool UseAccumulation> std::vector<NodeT> ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeVals protected
Definition at line 680 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut(), and ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes().
m_visitEmpty
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_visitEmpty protected
Definition at line 677 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
NumChildren
template<unsigned int dim, typename NodeT , bool UseAccumulation> constexpr unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::NumChildren = 1u << dim static
Definition at line 484 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h