DENDRO: ot::MatvecBase< dim, NodeT > Class Template Reference
ot::MatvecBase< dim, NodeT > Class Template Reference
#include <sfcTreeLoop_matvec.h>
Classes
struct AccessSubtree
Public Types
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase >
Public Types inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
using C = unsigned int
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
using SubtreeInfoT = SubtreeInfo< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
Public Member Functions
size_t finalize (NodeT *outputNodeVals) const
bool isLeaf () const
bool isLeafOrLower () const
MatvecBase ()=delete
MatvecBase (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, const TreeNode< unsigned int, dim > *allNodeCoords, const NodeT *inputNodeVals, const TreeNode< unsigned int, dim > *treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > &firstElement, const TreeNode< unsigned int, dim > &lastElement)
AccessSubtree subtreeInfo ()
Public Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
MatvecBase< dim, NodeT > & asConcreteType ()
const TreeNode< C, dim > & getCurrentSubtree () const
SubtreeInfoT getSubtreeInfo ()
bool isFinished () const
bool isPre () const
bool next ()
void reset ()
bool step ()
Static Public Member Functions
static MatvecBaseSummary< dim > generate_node_summary (const TreeNode< unsigned int, dim > *begin, const TreeNode< unsigned int, dim > *end)
static unsigned int get_max_depth (const TreeNode< unsigned int, dim > *begin, size_t numNodes)
static std::vector< bool > getNodeNonhangingIn (const FrameT &frame)
Static Public Attributes
static constexpr unsigned int NumChildren = 1u << dim
Static Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
static constexpr unsigned int NumChildren
Protected Member Functions
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
void fillAccessNodeCoordsFlat ()
void fillLeafNodeBdry ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
const FrameT & getCurrentFrame () const
FrameT & getCurrentFrame ()
SFC_State< dim > getCurrentRotation () const
const FrameT & getRootFrame () const
FrameT & getRootFrame ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
SFC_TreeLoop (const TreeNode< C, dim > *sortedTreePart, size_t localTreeSz, unsigned int max_depth)
SFC_TreeLoop ()=delete
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Attributes
std::vector< double > m_accessNodeCoordsFlat
unsigned int m_eleOrder
InterpMatrices< dim, NodeT > m_interp_matrices
std::vector< bool > m_leafNodeBdry
std::vector< TreeNode< unsigned int, dim > > m_leafNodeCoords
std::vector< NodeT > m_leafNodeVals
unsigned int m_ndofs
std::vector< bool > m_parentNodeBdry
std::vector< NodeT > m_parentNodeVals
int m_warningCounter = 0
Protected Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
FrameInputs< dim, Inputs< TreeNode< unsigned int, dim >, NodeT > >::DataStoreT m_rootInputData
FrameOutputs< dim, Outputs< NodeT > >::DataStoreT m_rootOutputData
MatvecBaseSummary< dim > m_rootSummary
std::array< RankI,(1u<< dim)+1 > m_rootTreeSplitters
std::vector< FrameT > m_stack
const TreeNode< C, dim > * m_treePartPtr
Additional Inherited Members
Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >
friend SubtreeInfoT
Detailed Description
template<unsigned int dim, typename NodeT>
class ot::MatvecBase< dim, NodeT >
Definition at line 102 of file sfcTreeLoop_matvec.h.
Member Typedef Documentation
FrameT
template<unsigned int dim, typename NodeT > using ot::MatvecBase< dim, NodeT >::FrameT = Frame<dim, Inputs<TreeNode<unsigned int, dim>, NodeT>, Outputs<NodeT>, MatvecBaseSummary<dim>, MatvecBase>
Definition at line 116 of file sfcTreeLoop_matvec.h.
Constructor & Destructor Documentation
MatvecBase() [1/2]
template<unsigned int dim, typename NodeT > ot::MatvecBase< dim, NodeT >::MatvecBase () delete
MatvecBase() [2/2]
template<unsigned int dim, typename NodeT > ot::MatvecBase< dim, NodeT >::MatvecBase (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, const TreeNode< unsigned int, dim > * allNodeCoords, const NodeT * inputNodeVals, const TreeNode< unsigned int, dim > * treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > & firstElement, const TreeNode< unsigned int, dim > & lastElement)
Definition at line 342 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::generate_node_summary(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getRootFrame(), intPow(), ot::MatvecBase< dim, NodeT >::m_eleOrder, ot::MatvecBase< dim, NodeT >::m_leafNodeCoords, ot::MatvecBase< dim, NodeT >::m_leafNodeVals, ot::MatvecBase< dim, NodeT >::m_parentNodeBdry, ot::MatvecBase< dim, NodeT >::m_parentNodeVals, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Member Function Documentation
bottomUpNodes()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::bottomUpNodes (FrameT & parentFrame, ExtantCellFlagT extantChildren) protected
Copied from sfcTreeLoop.h:
bottomUpNodes() is responsible to
Resize the parent output buffers (handles to buffers are given);
Merge results from incident child output buffers (SFC order) into the parent output buffers.
The previously indicated extantChildren bit array (Morton order) will be supplied.
Utilities are provided to identify and iterate over incident children.
const size_t numParentNodes = parentFrame.mySummaryHandle.m_subtreeNodeCount; // Assumes parent is never leaf.
Definition at line 670 of file sfcTreeLoop_matvec.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBase< dim, NodeT >::m_eleOrder, ot::MatvecBase< dim, NodeT >::m_interp_matrices, ot::MatvecBase< dim, NodeT >::m_ndofs, ot::MatvecBase< dim, NodeT >::m_parentNodeVals, ot::nchild(), and ot::MatvecBase< dim, NodeT >::NumChildren.
child2Parent()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::child2Parent (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 268 of file sfcTreeLoop_matvec.h.
References ot::fillAccessNodeCoordsFlat().
fillAccessNodeCoordsFlat()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat () protected
Definition at line 910 of file sfcTreeLoop_matvec.h.
References ot::fillAccessNodeCoordsFlat(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentSubtree(), ot::MatvecBase< dim, NodeT >::isLeafOrLower(), ot::MatvecBase< dim, NodeT >::m_accessNodeCoordsFlat, and ot::MatvecBase< dim, NodeT >::m_eleOrder.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodeCoords().
fillLeafNodeBdry()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::fillLeafNodeBdry () inline protected
Definition at line 273 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::getLeafNodeBdry().
finalize()
template<unsigned int dim, typename NodeT > size_t ot::MatvecBase< dim, NodeT >::finalize (NodeT * outputNodeVals) const
Definition at line 403 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getRootFrame(), ot::MatvecBase< dim, NodeT >::m_ndofs, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
generate_node_summary()
template<unsigned int dim, typename NodeT > MatvecBaseSummary< dim > ot::MatvecBase< dim, NodeT >::generate_node_summary (const TreeNode< unsigned int, dim > * begin, const TreeNode< unsigned int, dim > * end) static
Definition at line 304 of file sfcTreeLoop_matvec.h.
References ot::TreeNode< T, dim >::getIsOnTreeBdry(), ot::TreeNode< T, dim >::getLevel(), ot::MatvecBaseSummary< dim >::m_numBdryNodes, ot::MatvecBaseSummary< dim >::m_subtreeFinestLevel, and ot::MatvecBaseSummary< dim >::m_subtreeNodeCount.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::generate_node_summary(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::generate_node_summary(), and ot::MatvecBase< dim, NodeT >::MatvecBase().
get_max_depth()
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::get_max_depth (const TreeNode< unsigned int, dim > * begin, size_t numNodes) static
Definition at line 327 of file sfcTreeLoop_matvec.h.
References ot::TreeNode< T, dim >::getLevel().
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::get_max_depth(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::get_max_depth().
getNodeNonhangingIn()
template<unsigned int dim, typename NodeT > static std::vector<bool> ot::MatvecBase< dim, NodeT >::getNodeNonhangingIn (const FrameT & frame) inline static
Definition at line 253 of file sfcTreeLoop_matvec.h.
References ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), and ot::sfc_tree_utils::topDownNodes().
isLeaf()
template<unsigned int dim, typename NodeT > bool ot::MatvecBase< dim, NodeT >::isLeaf () const inline
Definition at line 235 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT > bool ot::MatvecBase< dim, NodeT >::isLeafOrLower () const inline
Definition at line 240 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat(), and ot::MatvecBase< dim, NodeT >::AccessSubtree::isLeafOrLower().
parent2Child()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::parent2Child (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 267 of file sfcTreeLoop_matvec.h.
subtreeInfo()
template<unsigned int dim, typename NodeT > AccessSubtree ot::MatvecBase< dim, NodeT >::subtreeInfo () inline
Definition at line 225 of file sfcTreeLoop_matvec.h.
topDownNodes()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::topDownNodes (FrameT & parentFrame, ExtantCellFlagT * extantChildren) protected
Copied from sfcTreeLoop.h:
topDownNodes() is responsible to
Resize the child input buffers (SFC order) in the parent frame;
Duplicate elements of the parent input buffers to incident child input buffers (SFC order);
2.1. Initialize a summary object for each child (SFC order).
Indicate to SFC_TreeLoop which children to traverse, by accumulating into the extantChildren bit array (Morton order).
Restrictions
MAY NOT resize or write to parent input buffers.
MAY NOT resize or write to variably sized output buffers.
Utilities are provided to identify and iterate over incident children.
std::vector<TreeNode<unsigned int, dim>> &childNodeCoords = parentFrame.template getChildInput<0>(child_sfc); childNodeCoords.clear(); Element<unsigned int, dim>(childSubtreesSFC[child_sfc]).template appendNodes<TreeNode<unsigned int, dim>>(m_eleOrder, childNodeCoords);
assert(parentFrame.template getChildInput<0>(child_sfc)[nodeRank] == myNodes[nIdx]);
Definition at line 422 of file sfcTreeLoop_matvec.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT >, Outputs< NodeT >, MatvecBaseSummary< dim >, MatvecBase< dim, NodeT > >::getCurrentSubtree(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getExtantTreeChildrenMorton(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBase< dim, NodeT >::m_eleOrder, ot::MatvecBase< dim, NodeT >::m_interp_matrices, ot::MatvecBase< dim, NodeT >::m_ndofs, ot::MatvecBase< dim, NodeT >::m_parentNodeBdry, ot::MatvecBase< dim, NodeT >::m_parentNodeVals, ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, ot::nchild(), and ot::MatvecBase< dim, NodeT >::NumChildren.
Member Data Documentation
m_accessNodeCoordsFlat
template<unsigned int dim, typename NodeT > std::vector<double> ot::MatvecBase< dim, NodeT >::m_accessNodeCoordsFlat protected
Definition at line 293 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat(), and ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodeCoords().
m_eleOrder
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::m_eleOrder protected
Definition at line 284 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getEleOrder(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodesPerElement(), ot::MatvecBase< dim, NodeT >::MatvecBase(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
m_interp_matrices
template<unsigned int dim, typename NodeT > InterpMatrices<dim, NodeT> ot::MatvecBase< dim, NodeT >::m_interp_matrices protected
Definition at line 295 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
m_leafNodeBdry
template<unsigned int dim, typename NodeT > std::vector<bool> ot::MatvecBase< dim, NodeT >::m_leafNodeBdry protected
Definition at line 290 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::getLeafNodeBdry().
m_leafNodeCoords
template<unsigned int dim, typename NodeT > std::vector<TreeNode<unsigned int,dim> > ot::MatvecBase< dim, NodeT >::m_leafNodeCoords protected
Definition at line 287 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::MatvecBase().
m_leafNodeVals
template<unsigned int dim, typename NodeT > std::vector<NodeT> ot::MatvecBase< dim, NodeT >::m_leafNodeVals protected
Definition at line 288 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::MatvecBase().
m_ndofs
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::m_ndofs protected
Definition at line 283 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBase< dim, NodeT >::finalize(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getNdofs(), ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsIn(), ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsOut(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
m_parentNodeBdry
template<unsigned int dim, typename NodeT > std::vector<bool> ot::MatvecBase< dim, NodeT >::m_parentNodeBdry protected
Definition at line 291 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::MatvecBase(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
m_parentNodeVals
template<unsigned int dim, typename NodeT > std::vector<NodeT> ot::MatvecBase< dim, NodeT >::m_parentNodeVals protected
Definition at line 289 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBase< dim, NodeT >::MatvecBase(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
m_warningCounter
template<unsigned int dim, typename NodeT > int ot::MatvecBase< dim, NodeT >::m_warningCounter = 0 protected
Definition at line 272 of file sfcTreeLoop_matvec.h.
NumChildren
template<unsigned int dim, typename NodeT > constexpr unsigned int ot::MatvecBase< dim, NodeT >::NumChildren = 1u << dim static
Definition at line 118 of file sfcTreeLoop_matvec.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), and ot::MatvecBase< dim, NodeT >::topDownNodes().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec.h