DENDRO: ot::TreeNode< T, dim > Class Template Reference
ot::TreeNode< T, dim > Class Template Reference
A class to manage octants.
#include <treeNode.h>
Public Types
using coordType = T
Public Member Functions
void appendAllNeighbours (std::vector< TreeNode > &nodeList) const
Append in-bounds neighbors of node to node list.
void appendCoarseNeighbours (std::vector< TreeNode > &nodeList) const
const periodic::PCoord< T, dim > & coords () const
TreeNode getAncestor (unsigned int ancLev) const
int getAnchor (std::array< T, dim > &xyz) const
get the coordinates of the octant
std::array< char, MAX_LEVEL+1 > getBase32Hex (unsigned int lev=0) const
TreeNode getChildMorton (unsigned char child) const
return a child of this octant with the given child number.
unsigned int getCommonAncestorDepth (const TreeNode &other) const
Returns the greatest depth at which the other node shares an ancestor.
TreeNode getDFD () const
TreeNode getDLD () const
TreeNode getFirstChildMorton () const
return the smallest (in morton id) of this octant
bool getIsOnTreeBdry () const
unsigned int getLevel () const
return the level of the octant
unsigned int getMaxDepth () const
returns the max depth
unsigned char getMortonIndex (T level) const
return the (Morton indexed) child number at specified level.
unsigned char getMortonIndex () const
return the (Morton indexed) child number at the node's own level.
TreeNode getParent () const
T getX (int d) const
return the coordinates of the dth dimention
const std::array< T, dim > & getX () const
bool isAncestor (const TreeNode &other) const
Checks if this octant is an ancestor of the input.
bool isAncestorInclusive (const TreeNode &other) const
bool isRoot () const
returns true if *(this) octant is root. false otherwise
T lowerBound (int d) const
lower bound of the d dimension
bool operator!= (TreeNode const &other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
TreeNode & operator= (TreeNode const &other)=default
Assignment operator. No checks for dim or maxD are performed. It's ok to change dim and maxD of the current octant using the assignment operator.
bool operator== (TreeNode const &other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
const periodic::PRange< T, dim > range () const
void setIsOnTreeBdry (bool isOnTreeBdry)
void setLevel (unsigned int lev)
set the level of the octant
void setMortonIndex (unsigned char child)
set the last digit (at node's level) in each component of the anchor.
void setX (int d, T coord)
set the coordinate in the dth dimension
void setX (const std::array< T, dim > &coords)
TreeNode ()
Constructs a root octant.
TreeNode (const std::array< T, dim > coords, unsigned int level)
Constructs an octant.
TreeNode (const TreeNode &other)=default
Copy constructor.
T upperBound (int d) const
upper bound of the d dimension, not mapped periodic
Protected Member Functions
TreeNode (const int dummy, const std::array< T, dim > coords, unsigned int level)
Constructs an octant.
Protected Attributes
periodic::PCoord< T, dim > m_coords
bool m_isOnTreeBdry
unsigned int m_uiLevel
Friends
std::ostream & operator (std::ostream &os, TreeNode< T, dim > const &node)
stream operator to output treeNodes with std::cout
Detailed Description
template<typename T, unsigned int dim>
class ot::TreeNode< T, dim >
A class to manage octants.
Template Parameters
dim the dimension of the tree
Definition at line 32 of file treeNode.h.
Member Typedef Documentation
coordType
template<typename T, unsigned int dim> using ot::TreeNode< T, dim >::coordType = T
Definition at line 78 of file treeNode.h.
Constructor & Destructor Documentation
TreeNode() [1/4]
template<typename T, unsigned int dim> ot::TreeNode< T, dim >::TreeNode (const int dummy, const std::array< T, dim > coords, unsigned int level) protected
Constructs an octant.
Parameters
dummy : not used yet.
coords The coordinates of the anchor of the octant
level The level of the octant
TreeNode() [2/4]
template<typename T, unsigned int dim> ot::TreeNode< T, dim >::TreeNode ()
Constructs a root octant.
See also
MAX_LEVEL
TreeNode() [3/4]
template<typename T, unsigned int dim> ot::TreeNode< T, dim >::TreeNode (const std::array< T, dim > coords, unsigned int level)
Constructs an octant.
Parameters
coords The coordinates of the anchor of the octant
level The level of the octant
Note
Coordinates are not masked to level, however periodic is applied.
TreeNode() [4/4]
template<typename T, unsigned int dim> ot::TreeNode< T, dim >::TreeNode (const TreeNode< T, dim > & other) default
Copy constructor.
Member Function Documentation
appendAllNeighbours()
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::appendAllNeighbours (std::vector< TreeNode< T, dim > > & nodeList) const
Append in-bounds neighbors of node to node list.
Author
Masado Ishii
Referenced by ot::TreeNode< T, D >::coords().
appendCoarseNeighbours()
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::appendCoarseNeighbours (std::vector< TreeNode< T, dim > > & nodeList) const
Referenced by ot::TreeNode< T, D >::coords().
coords()
template<typename T, unsigned int dim> const periodic::PCoord<T, dim>& ot::TreeNode< T, dim >::coords () const inline
Definition at line 124 of file treeNode.h.
Referenced by ot::checksum_octant(), and ot::TreeNode< T, D >::coords().
getAncestor()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getAncestor (unsigned int ancLev) const
Author
Rahul Sampath
Parameters
The level of the ancestor
Returns
the ancestor of this octant at level 'ancLev'
Referenced by ot::TreeNode< T, D >::coords(), and ot::treeNode2Physical().
getAnchor()
template<typename T, unsigned int dim> int ot::TreeNode< T, dim >::getAnchor (std::array< T, dim > & xyz) const
get the coordinates of the octant
Parameters
[out]
Referenced by ot::TreeNode< T, D >::coords(), and ot::dbgCoordStr().
getBase32Hex()
template<typename T, unsigned int dim> std::array<char, MAX_LEVEL+1> ot::TreeNode< T, dim >::getBase32Hex (unsigned int lev = 0) const
Author
Masado Ishii
Referenced by ot::TreeNode< T, D >::coords().
getChildMorton()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getChildMorton (unsigned char child) const
return a child of this octant with the given child number.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::TreeNode< T, D >::coords(), ot::createRegularOctree(), ot::dld(), ot::function2Octree(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::step(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
getCommonAncestorDepth()
template<typename T, unsigned int dim> unsigned int ot::TreeNode< T, dim >::getCommonAncestorDepth (const TreeNode< T, dim > & other) const
Returns the greatest depth at which the other node shares an ancestor.
Referenced by ot::TreeNode< T, D >::coords().
getDFD()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getDFD () const
Author
Rahul Sampath
Returns
the Deepest first decendant of this octant
Referenced by ot::TreeNode< T, D >::coords().
getDLD()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getDLD () const
Author
Rahul Sampath
Returns
the deepest last decendant of this octant
Referenced by ot::TreeNode< T, D >::coords().
getFirstChildMorton()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getFirstChildMorton () const
return the smallest (in morton id) of this octant
Referenced by ot::TreeNode< T, D >::coords().
getIsOnTreeBdry()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::getIsOnTreeBdry () const inline
As a point, is this point exposed as part of the tree/domain boundary? As an element, does the element have any exposed exterior points? Before the tree is filtered, this is set assuming the unit hypercube.
Referenced by ot::TreeNode< T, D >::coords(), ot::fillLeafNodeBdry(), ot::MatvecBaseCoords< dim >::generate_node_summary(), ot::MatvecBase< dim, NodeT >::generate_node_summary(), ot::MatvecBaseCoords< dim >::AccessSubtree::isElementBoundary(), ot::MatvecBase< dim, NodeT >::AccessSubtree::isElementBoundary(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isElementBoundary(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isElementBoundary().
getLevel()
template<typename T, unsigned int dim> unsigned int ot::TreeNode< T, dim >::getLevel () const
return the level of the octant
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::checksum_octant(), ot::compareMorton(), ot::createRegularOctree(), ot::dld(), ot::fillAccessNodeCoordsFlat(), ot::fillLeafNodeBdry(), ot::MatvecBaseCoords< dim >::generate_node_summary(), ot::MatvecBase< dim, NodeT >::generate_node_summary(), ot::MatvecBaseCoords< dim >::get_max_depth(), ot::MatvecBase< dim, NodeT >::get_max_depth(), ot::MatvecBase< dim, NodeT >::getNodeNonhangingIn(), ot::MatvecBaseCoords< dim >::isLeaf(), ot::MatvecBaseIn< dim, NodeT, p2c >::isLeaf(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeaf(), ot::MatvecBaseCoords< dim >::isLeafOrLower(), ot::MatvecBaseIn< dim, NodeT, p2c >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::permuteDims(), ot::printNodeCoords(), ot::printNodes(), ot::printtn(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes(), and ot::treeNode2Physical().
getMaxDepth()
template<typename T, unsigned int dim> unsigned int ot::TreeNode< T, dim >::getMaxDepth () const
returns the max depth
getMortonIndex() [1/2]
template<typename T, unsigned int dim> unsigned char ot::TreeNode< T, dim >::getMortonIndex (T level) const
return the (Morton indexed) child number at specified level.
Referenced by ot::compareMorton(), and ot::dld().
getMortonIndex() [2/2]
template<typename T, unsigned int dim> unsigned char ot::TreeNode< T, dim >::getMortonIndex () const
return the (Morton indexed) child number at the node's own level.
Referenced by ot::TreeNode< T, D >::coords().
getParent()
template<typename T, unsigned int dim> TreeNode ot::TreeNode< T, dim >::getParent () const
Returns
the parent of this octant
Referenced by ot::checkSiblingLeafsTogether(), ot::TreeNode< T, D >::coords(), and ot::fillLeafNodeBdry().
getX() [1/2]
template<typename T, unsigned int dim> T ot::TreeNode< T, dim >::getX (int d) const
return the coordinates of the dth dimention
Referenced by ot::compareMorton(), ot::fillAccessNodeCoordsFlat(), ot::fillLeafNodeBdry(), ot::permuteDims(), ot::printNodeCoords(), ot::printNodes(), ot::printtn(), and ot::treeNode2Physical().
getX() [2/2]
template<typename T, unsigned int dim> const std::array<T, dim>& ot::TreeNode< T, dim >::getX () const inline
Definition at line 122 of file treeNode.h.
isAncestor()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::isAncestor (const TreeNode< T, dim > & other) const
Checks if this octant is an ancestor of the input.
Author
Rahul Sampath
Returns
'true' if this is an ancestor of 'other'
Referenced by ot::TreeNode< T, D >::coords().
isAncestorInclusive()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::isAncestorInclusive (const TreeNode< T, dim > & other) const
Referenced by ot::TreeNode< T, D >::coords().
isRoot()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::isRoot () const
returns true if *(this) octant is root. false otherwise
Referenced by ot::TreeNode< T, D >::coords().
lowerBound()
template<typename T, unsigned int dim> T ot::TreeNode< T, dim >::lowerBound (int d) const
lower bound of the d dimension
Referenced by ot::TreeNode< T, D >::coords().
operator!=()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::operator!= (TreeNode< T, dim > const & other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
operator=()
template<typename T, unsigned int dim> TreeNode& ot::TreeNode< T, dim >::operator= (TreeNode< T, dim > const & other) default
Assignment operator. No checks for dim or maxD are performed. It's ok to change dim and maxD of the current octant using the assignment operator.
operator==()
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::operator== (TreeNode< T, dim > const & other) const
Two octants are equal if their respective anchors are equal and their levels are equal.
range()
template<typename T, unsigned int dim> const periodic::PRange<T, dim> ot::TreeNode< T, dim >::range () const inline
Referenced by ot::TreeNode< T, D >::coords().
setIsOnTreeBdry()
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::setIsOnTreeBdry (bool isOnTreeBdry) inline
Note
If you set this yourself you may invalidate the tree.
Referenced by ot::TreeNode< T, D >::coords().
setLevel()
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::setLevel (unsigned int lev)
set the level of the octant
Referenced by ot::KeyFunIdentity_maxDepth< T, dim >::operator()(), and ot::permuteDims().
setMortonIndex()
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::setMortonIndex (unsigned char child)
set the last digit (at node's level) in each component of the anchor.
Referenced by ot::TreeNode< T, D >::coords().
setX() [1/2]
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::setX (int d, T coord)
set the coordinate in the dth dimension
Referenced by ot::TreeNode< T, D >::coords(), and ot::permuteDims().
setX() [2/2]
template<typename T, unsigned int dim> void ot::TreeNode< T, dim >::setX (const std::array< T, dim > & coords)
upperBound()
template<typename T, unsigned int dim> T ot::TreeNode< T, dim >::upperBound (int d) const
upper bound of the d dimension, not mapped periodic
Referenced by ot::TreeNode< T, D >::coords().
Friends And Related Function Documentation
operator
template<typename T, unsigned int dim> std::ostream& operator (std::ostream & os, TreeNode< T, dim > const & node) friend
stream operator to output treeNodes with std::cout
Member Data Documentation
m_coords
template<typename T, unsigned int dim> periodic::PCoord<T, dim> ot::TreeNode< T, dim >::m_coords protected
TreeNode coefficients
Definition at line 55 of file treeNode.h.
Referenced by ot::TreeNode< T, D >::coords().
m_isOnTreeBdry
template<typename T, unsigned int dim> bool ot::TreeNode< T, dim >::m_isOnTreeBdry protected
As a point, is this point exposed as part of the tree/domain boundary? As an element, does the element have any exposed exterior points?
Note
false unless previously set (or copied after setting) setIsOnTreeBdry().
Definition at line 63 of file treeNode.h.
m_uiLevel
template<typename T, unsigned int dim> unsigned int ot::TreeNode< T, dim >::m_uiLevel protected
level of the tree node
Definition at line 58 of file treeNode.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/treeNode.h