DENDRO: periodic::PRange< T, dim > Class Template Reference
periodic::PRange< T, dim > Class Template Reference
#include <pcoord.h>
Public Types
using CoordTransfer = typename PCoord< T, dim >::CoordTransfer
Public Member Functions
bool closedContains (int axis, const CoordTransfer &coord) const
bool closedContains (int axis, T coord) const
bool closedContains (const PCoord< T, dim > &pcoord) const
bool halfClosedContains (int axis, const CoordTransfer &coord) const
bool halfClosedContains (int axis, T coord) const
const PCoord< T, dim > & max () const
const CoordTransfer max (int d) const
const PCoord< T, dim > & min () const
const CoordTransfer min (int d) const
bool openContains (int axis, const CoordTransfer &coord) const
bool openContains (int axis, T coord) const
PRange & operator= (const PRange &)=default
PRange & operator= (PRange &&)=default
PRange ()
PRange (const PCoord< T, dim > &min, T side)
PRange (const PRange &)=default
PRange (PRange &&)=default
T side () const
bool upperEquals (int axis, const CoordTransfer &coord) const
bool upperEquals (int axis, T coord) const
Detailed Description
template<typename T, int dim>
class periodic::PRange< T, dim >
Definition at line 85 of file pcoord.h.
Member Typedef Documentation
CoordTransfer
template<typename T, int dim> using periodic::PRange< T, dim >::CoordTransfer = typename PCoord<T, dim>::CoordTransfer
Definition at line 101 of file pcoord.h.
Constructor & Destructor Documentation
PRange() [1/4]
template<typename T , int dim> periodic::PRange< T, dim >::PRange () inline
Definition at line 281 of file pcoord.h.
PRange() [2/4]
template<typename T , int dim> periodic::PRange< T, dim >::PRange (const PCoord< T, dim > & min, T side) inline
Definition at line 287 of file pcoord.h.
References periodic::PCoord< T, dim >::coord(), and periodic::PRange< T, dim >::side().
PRange() [3/4]
template<typename T, int dim> periodic::PRange< T, dim >::PRange (const PRange< T, dim > &) default
PRange() [4/4]
template<typename T, int dim> periodic::PRange< T, dim >::PRange (PRange< T, dim > &&) default
Member Function Documentation
closedContains() [1/3]
template<typename T , int dim> bool periodic::PRange< T, dim >::closedContains (int axis, const CoordTransfer & coord) const inline
Definition at line 353 of file pcoord.h.
References periodic::PRange< T, dim >::halfClosedContains(), and periodic::PRange< T, dim >::upperEquals().
Referenced by periodic::PRange< T, dim >::closedContains().
closedContains() [2/3]
template<typename T , int dim> bool periodic::PRange< T, dim >::closedContains (int axis, T coord) const inline
Definition at line 388 of file pcoord.h.
References periodic::PRange< T, dim >::halfClosedContains(), and periodic::PRange< T, dim >::upperEquals().
closedContains() [3/3]
template<typename T , int dim> bool periodic::PRange< T, dim >::closedContains (const PCoord< T, dim > & pcoord) const inline
Definition at line 396 of file pcoord.h.
References periodic::PRange< T, dim >::closedContains(), and periodic::PCoord< T, dim >::coord().
halfClosedContains() [1/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::halfClosedContains (int axis, const CoordTransfer & coord) const inline
Definition at line 337 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::closedContains().
halfClosedContains() [2/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::halfClosedContains (int axis, T coord) const inline
Definition at line 370 of file pcoord.h.
References periodic::PCoord< T, dim >::map().
max() [1/2]
template<typename T , int dim> const PCoord< T, dim > & periodic::PRange< T, dim >::max () const inline
Definition at line 303 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::max().
max() [2/2]
template<typename T , int dim> const PCoord< T, dim >::CoordTransfer periodic::PRange< T, dim >::max (int d) const inline
Definition at line 315 of file pcoord.h.
References periodic::PRange< T, dim >::max().
min() [1/2]
template<typename T , int dim> const PCoord< T, dim > & periodic::PRange< T, dim >::min () const inline
Definition at line 296 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::min().
min() [2/2]
template<typename T , int dim> const PCoord< T, dim >::CoordTransfer periodic::PRange< T, dim >::min (int d) const inline
Definition at line 309 of file pcoord.h.
References periodic::PRange< T, dim >::min().
openContains() [1/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::openContains (int axis, const CoordTransfer & coord) const inline
Definition at line 329 of file pcoord.h.
openContains() [2/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::openContains (int axis, T coord) const inline
Definition at line 361 of file pcoord.h.
References periodic::PCoord< T, dim >::map().
operator=() [1/2]
template<typename T, int dim> PRange& periodic::PRange< T, dim >::operator= (const PRange< T, dim > &) default
operator=() [2/2]
template<typename T, int dim> PRange& periodic::PRange< T, dim >::operator= (PRange< T, dim > &&) default
side()
template<typename T , int dim> T periodic::PRange< T, dim >::side () const inline
Definition at line 322 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::PRange().
upperEquals() [1/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::upperEquals (int axis, const CoordTransfer & coord) const inline
Definition at line 345 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::closedContains().
upperEquals() [2/2]
template<typename T , int dim> bool periodic::PRange< T, dim >::upperEquals (int axis, T coord) const inline
Definition at line 379 of file pcoord.h.
References periodic::PCoord< T, dim >::map().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/pcoord.h