DENDRO: ot::MeshLoopImpl< T, dim, TreatSorted > Class Template Reference
ot::MeshLoopImpl< T, dim, TreatSorted > Class Template Reference
Iterator over TreeNodes (cells in the mesh) with in-place bucketing.
#include <meshLoop.h>
Public Types
using TN = typename std::conditional< TreatSorted, const TreeNode< T, dim >, TreeNode< T, dim > >::type
Public Member Functions
const MeshLoopFrame< T, dim > & getTopConst () const
bool isFinished ()
bool isPre ()
MeshLoopImpl (TN *tnlist, size_t sz, bool vEmpty, bool vPre, bool vPost)
MeshLoopImpl ()=delete
bool next (bool vEmpty, bool vPre, bool vPost)
bool step (bool vEmpty, bool vPre, bool vPost)
Protected Member Functions
void bucketAndPush (RankI begin, RankI end, LevI lev, RotI pRot)
MeshLoopFrame< T, dim > & getTop ()
Protected Attributes
TN * m_ptr
std::vector< MeshLoopFrame< T, dim > > m_stack
size_t m_sz
Static Protected Attributes
static constexpr unsigned int NumChildren = 1u << dim
Detailed Description
template<typename T, unsigned int dim, bool TreatSorted>
class ot::MeshLoopImpl< T, dim, TreatSorted >
Iterator over TreeNodes (cells in the mesh) with in-place bucketing.
Template Parameters
TreatSorted if true, uses SFC_locateBuckets(const *ptr) instead of SFC_bucketing(non-const *ptr).
Definition at line 16 of file meshLoop.h.
Member Typedef Documentation
TN
template<typename T , unsigned int dim, bool TreatSorted> using ot::MeshLoopImpl< T, dim, TreatSorted >::TN = typename std::conditional<TreatSorted, const TreeNode<T, dim>, TreeNode<T, dim> >::type
Definition at line 152 of file meshLoop.h.
Constructor & Destructor Documentation
MeshLoopImpl() [1/2]
template<typename T , unsigned int dim, bool TreatSorted> ot::MeshLoopImpl< T, dim, TreatSorted >::MeshLoopImpl (TN * tnlist, size_t sz, bool vEmpty, bool vPre, bool vPost)
Definition at line 184 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush().
MeshLoopImpl() [2/2]
template<typename T , unsigned int dim, bool TreatSorted> ot::MeshLoopImpl< T, dim, TreatSorted >::MeshLoopImpl () delete
Member Function Documentation
bucketAndPush()
template<typename T , unsigned int dim, bool TreatSorted> void ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush (RankI begin, RankI end, LevI lev, RotI pRot) protected
Definition at line 201 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::m_ptr, ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack, ot::SFC_Tree< T, dim >::SFC_bucketing(), and ot::SFC_Tree< T, dim >::SFC_locateBuckets().
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::getTop(), ot::MeshLoopImpl< T, dim, TreatSorted >::MeshLoopImpl(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
getTop()
template<typename T , unsigned int dim, bool TreatSorted> MeshLoopFrame<T, dim>& ot::MeshLoopImpl< T, dim, TreatSorted >::getTop () inline protected
Definition at line 168 of file meshLoop.h.
References ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::begin(), ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::end(), and ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::step().
getTopConst()
template<typename T , unsigned int dim, bool TreatSorted> const MeshLoopFrame<T, dim>& ot::MeshLoopImpl< T, dim, TreatSorted >::getTopConst () const inline
Definition at line 162 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::getTopConst().
isFinished()
template<typename T , unsigned int dim, bool TreatSorted> bool ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished ()
Definition at line 244 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::MeshLoopInterface_S_NS(), and ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator!=().
isPre()
template<typename T , unsigned int dim, bool TreatSorted> bool ot::MeshLoopImpl< T, dim, TreatSorted >::isPre ()
Definition at line 237 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::MeshLoopInterface_S_NS(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::next(), ot::MeshLoopImpl< T, dim, TreatSorted >::next(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
next()
template<typename T , unsigned int dim, bool TreatSorted> bool ot::MeshLoopImpl< T, dim, TreatSorted >::next (bool vEmpty, bool vPre, bool vPost)
Definition at line 288 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::next(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
step()
template<typename T , unsigned int dim, bool TreatSorted> bool ot::MeshLoopImpl< T, dim, TreatSorted >::step (bool vEmpty, bool vPre, bool vPost)
Definition at line 252 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush(), ot::MeshLoopImpl< T, dim, TreatSorted >::getTop(), HILBERT_TABLE, ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), ot::MeshLoopFrame< T, dim >::m_child_splitters, ot::MeshLoopFrame< T, dim >::m_is_pre, ot::MeshLoopFrame< T, dim >::m_lev, ot::MeshLoopFrame< T, dim >::m_pRot, ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack, m_uiMaxDepth, ot::MeshLoopImpl< T, dim, TreatSorted >::next(), ot::MeshLoopImpl< T, dim, TreatSorted >::NumChildren, and rotations.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::MeshLoopInterface_S_NS(), and ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step().
Member Data Documentation
m_ptr
template<typename T , unsigned int dim, bool TreatSorted> TN* ot::MeshLoopImpl< T, dim, TreatSorted >::m_ptr protected
Definition at line 173 of file meshLoop.h.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush().
m_stack
template<typename T , unsigned int dim, bool TreatSorted> std::vector<MeshLoopFrame<T, dim> > ot::MeshLoopImpl< T, dim, TreatSorted >::m_stack protected
Definition at line 172 of file meshLoop.h.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush(), ot::MeshLoopImpl< T, dim, TreatSorted >::getTop(), ot::MeshLoopImpl< T, dim, TreatSorted >::getTopConst(), ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), ot::MeshLoopImpl< T, dim, TreatSorted >::next(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
m_sz
template<typename T , unsigned int dim, bool TreatSorted> size_t ot::MeshLoopImpl< T, dim, TreatSorted >::m_sz protected
Definition at line 174 of file meshLoop.h.
NumChildren
template<typename T , unsigned int dim, bool TreatSorted> constexpr unsigned int ot::MeshLoopImpl< T, dim, TreatSorted >::NumChildren = 1u << dim static protected
Definition at line 165 of file meshLoop.h.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::step().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/meshLoop.h