DENDRO: ot::IterateNodesToChildren< dim > Class Template Reference
ot::IterateNodesToChildren< dim > Class Template Reference
#include <sfcTreeLoop.h>
Public Types
using FType = typename ot::CellType< dim >::FlagType
Public Member Functions
IterateNodesToChildren & begin ()
ChildI getChild_m () const
ChildI getChild_sfc () const
size_t getPNodeIdx () const
bool isEnd () const
IterateNodesToChildren (const TreeNode< unsigned int, dim > &subtree, const TreeNode< unsigned int, dim > *nodesBegin, size_t numParentNodes, SFC_State< dim > sfc, ExtantCellFlagT subtreeChildren=((1u<<(1u<< dim)) - 1))
void next ()
bool operator!= (const IterateNodesToChildren &other) const
IterateNodesToChildren & operator* ()
IterateNodesToChildren & operator++ ()
Static Public Member Functions
static IterateNodesToChildren end ()
Protected Member Functions
bool fromChildSet ()
bool fromNodeSet ()
Protected Attributes
binOp::TallBitMatrix< dim, FType > m_bitExpander
ExtantCellFlagT m_extantChildren
FType m_firstIncidentChild_m
ChildI m_incidentChild_m
ChildI m_incidentChild_sfc
ChildI m_incidentSubspaceVolume
const TreeNode< unsigned int, dim > * m_nodesBegin
size_t m_numParentNodes
size_t m_pNodeIdx
const ChildI * m_rot_inv
const Element< unsigned int, dim > m_subtree
const ExtantCellFlagT m_subtreeChildren
ChildI m_virtChildIdx
Detailed Description
template<unsigned int dim>
class ot::IterateNodesToChildren< dim >
IterateNodesToChildren
Implements an iterator/generator in place of the following nested for:
for (ot::RankI nIdx = curBegin; nIdx < curEnd; nIdx++)
{
  curSubtree.incidentChildren( sibNodeCoords[nIdx],
                               firstIncidentChild_m,
                               incidentSubspace,
                               incidentSubspaceDim);
  binOp::TallBitMatrix<dim, FType> bitExpander =
      binOp::TallBitMatrix<dim, FType>::generateColumns(incidentSubspace);
  const ot::ChildI numIncidentChildren = 1u << incidentSubspaceDim;
  for (ot::ChildI c = 0; c < numIncidentChildren; c++)
  {
    ot::ChildI incidentChild_m = firstIncidentChild_m + bitExpander.expandBitstring(c);
    ot::ChildI incidentChild_sfc = rot_inv[incidentChild_m];
    // Read or write node information to child. //
  }
}
New interface: IterateNodesToChildren::IterateNodesToChildren({init info}); void IterateNodesToChildren::next(); bool IterateNodesToChildren::isEnd();
ChildI getChild_m(); ChildI getChild_sfc(); size_t getPNodeIdx();
Definition at line 181 of file sfcTreeLoop.h.
Member Typedef Documentation
FType
template<unsigned int dim> using ot::IterateNodesToChildren< dim >::FType = typename ot::CellType<dim>::FlagType
Definition at line 757 of file sfcTreeLoop.h.
Constructor & Destructor Documentation
IterateNodesToChildren()
template<unsigned int dim> ot::IterateNodesToChildren< dim >::IterateNodesToChildren (const TreeNode< unsigned int, dim > & subtree, const TreeNode< unsigned int, dim > * nodesBegin, size_t numParentNodes, SFC_State< dim > sfc, ExtantCellFlagT subtreeChildren = ((1u << (1u<<dim)) - 1)) inline
Definition at line 760 of file sfcTreeLoop.h.
Member Function Documentation
begin()
template<unsigned int dim> IterateNodesToChildren& ot::IterateNodesToChildren< dim >::begin () inline
Definition at line 805 of file sfcTreeLoop.h.
end()
template<unsigned int dim> static IterateNodesToChildren ot::IterateNodesToChildren< dim >::end () inline static
Definition at line 810 of file sfcTreeLoop.h.
fromChildSet()
template<unsigned int dim> bool ot::IterateNodesToChildren< dim >::fromChildSet () inline protected
Definition at line 858 of file sfcTreeLoop.h.
fromNodeSet()
template<unsigned int dim> bool ot::IterateNodesToChildren< dim >::fromNodeSet () inline protected
Definition at line 834 of file sfcTreeLoop.h.
References binOp::TallBitMatrix< W, B >::generateColumns().
getChild_m()
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::getChild_m () const inline
Definition at line 795 of file sfcTreeLoop.h.
getChild_sfc()
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::getChild_sfc () const inline
Definition at line 798 of file sfcTreeLoop.h.
getPNodeIdx()
template<unsigned int dim> size_t ot::IterateNodesToChildren< dim >::getPNodeIdx () const inline
Definition at line 801 of file sfcTreeLoop.h.
isEnd()
template<unsigned int dim> bool ot::IterateNodesToChildren< dim >::isEnd () const inline
Definition at line 778 of file sfcTreeLoop.h.
Referenced by ot::IterateNodesToChildren< dim >::operator!=().
next()
template<unsigned int dim> void ot::IterateNodesToChildren< dim >::next () inline
Definition at line 784 of file sfcTreeLoop.h.
operator!=()
template<unsigned int dim> bool ot::IterateNodesToChildren< dim >::operator!= (const IterateNodesToChildren< dim > & other) const inline
Definition at line 815 of file sfcTreeLoop.h.
References ot::IterateNodesToChildren< dim >::isEnd().
operator*()
template<unsigned int dim> IterateNodesToChildren& ot::IterateNodesToChildren< dim >::operator* () inline
Definition at line 826 of file sfcTreeLoop.h.
operator++()
template<unsigned int dim> IterateNodesToChildren& ot::IterateNodesToChildren< dim >::operator++ () inline
Definition at line 820 of file sfcTreeLoop.h.
Member Data Documentation
m_bitExpander
template<unsigned int dim> binOp::TallBitMatrix<dim, FType> ot::IterateNodesToChildren< dim >::m_bitExpander protected
Definition at line 887 of file sfcTreeLoop.h.
m_extantChildren
template<unsigned int dim> ExtantCellFlagT ot::IterateNodesToChildren< dim >::m_extantChildren protected
FType m_incidentSubspace; FType m_incidentSubspaceDim;
Definition at line 890 of file sfcTreeLoop.h.
m_firstIncidentChild_m
template<unsigned int dim> FType ot::IterateNodesToChildren< dim >::m_firstIncidentChild_m protected
Definition at line 886 of file sfcTreeLoop.h.
m_incidentChild_m
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::m_incidentChild_m protected
Definition at line 883 of file sfcTreeLoop.h.
m_incidentChild_sfc
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::m_incidentChild_sfc protected
Definition at line 884 of file sfcTreeLoop.h.
m_incidentSubspaceVolume
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::m_incidentSubspaceVolume protected
Definition at line 881 of file sfcTreeLoop.h.
m_nodesBegin
template<unsigned int dim> const TreeNode<unsigned int, dim>* ot::IterateNodesToChildren< dim >::m_nodesBegin protected
Definition at line 874 of file sfcTreeLoop.h.
m_numParentNodes
template<unsigned int dim> size_t ot::IterateNodesToChildren< dim >::m_numParentNodes protected
Definition at line 877 of file sfcTreeLoop.h.
m_pNodeIdx
template<unsigned int dim> size_t ot::IterateNodesToChildren< dim >::m_pNodeIdx protected
Definition at line 878 of file sfcTreeLoop.h.
m_rot_inv
template<unsigned int dim> const ChildI* ot::IterateNodesToChildren< dim >::m_rot_inv protected
Definition at line 875 of file sfcTreeLoop.h.
m_subtree
template<unsigned int dim> const Element<unsigned int, dim> ot::IterateNodesToChildren< dim >::m_subtree protected
Definition at line 873 of file sfcTreeLoop.h.
m_subtreeChildren
template<unsigned int dim> const ExtantCellFlagT ot::IterateNodesToChildren< dim >::m_subtreeChildren protected
Definition at line 891 of file sfcTreeLoop.h.
m_virtChildIdx
template<unsigned int dim> ChildI ot::IterateNodesToChildren< dim >::m_virtChildIdx protected
Definition at line 879 of file sfcTreeLoop.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop.h