DENDRO: ot::MatRecord Class Reference
ot::MatRecord Class Reference
#include <matRecord.h>
Public Member Functions
RankI getColDim () const
return the col dof
RankI getColID () const
returns the col ID
DendroScalar getMatVal () const
returns the entry value
RankI getRowDim () const
return the row dof
RankI getRowID () const
returns the row ID
MatRecord ()
The default constructor.
MatRecord (RankI rowID, RankI colID, RankI rowDim, RankI colDim, DendroScalar value)
MatRecord (const MatRecord &other)
The copy constructor.
bool operator!= (MatRecord const &other) const
Overloaded != Operator.
bool operator< (MatRecord const &other) const
Overloaded < Operator.
bool operator<= (MatRecord const &other) const
Overloaded <= Operator.
MatRecord & operator= (MatRecord const &other)
The assignment operator.
bool operator== (MatRecord const &other) const
Overloaded == Operator.
bool operator> (MatRecord const &other) const
Overloaded > Operator.
bool operator>= (MatRecord const &other) const
Overloaded >= Operator.
void setColDim (RankI colDim)
sets the colDim value
void setColID (RankI colID)
sets the rowID value
void setMatValue (DendroScalar value)
sets matrix value
void setRowDim (RankI rowDim)
sets the rowDim value
void setRowID (RankI rowID)
sets the rowID value
Friends
std::ostream & operator<< (std::ostream &os, MatRecord const &re)
Detailed Description
Definition at line 26 of file matRecord.h.
Constructor & Destructor Documentation
MatRecord() [1/3]
ot::MatRecord::MatRecord () inline
The default constructor.
Definition at line 51 of file matRecord.h.
Referenced by setColDim().
MatRecord() [2/3]
ot::MatRecord::MatRecord (RankI rowID, RankI colID, RankI rowDim, RankI colDim, DendroScalar value) inline
MatRecord constructor
Parameters
[in] rowID row id
[in] colID col id
[in] rowDim row dim
[in] colDim colDim
[in] value value of for the entry.
Definition at line 118 of file matRecord.h.
MatRecord() [3/3]
ot::MatRecord::MatRecord (const MatRecord & other) inline
The copy constructor.
Definition at line 141 of file matRecord.h.
References getColDim(), getColID(), getMatVal(), getRowDim(), and getRowID().
Member Function Documentation
getColDim()
RankI ot::MatRecord::getColDim () const inline
return the col dof
Definition at line 63 of file matRecord.h.
Referenced by MatRecord(), operator<(), operator=(), and operator==().
getColID()
RankI ot::MatRecord::getColID () const inline
returns the col ID
Definition at line 59 of file matRecord.h.
Referenced by MatRecord(), operator<(), operator=(), and operator==().
getMatVal()
DendroScalar ot::MatRecord::getMatVal () const inline
returns the entry value
Definition at line 133 of file matRecord.h.
Referenced by MatRecord(), operator<(), operator=(), operator==(), and setColDim().
getRowDim()
RankI ot::MatRecord::getRowDim () const inline
return the row dof
Definition at line 61 of file matRecord.h.
Referenced by MatRecord(), operator<(), operator=(), and operator==().
getRowID()
RankI ot::MatRecord::getRowID () const inline
returns the row ID
Definition at line 57 of file matRecord.h.
Referenced by MatRecord(), operator<(), operator=(), and operator==().
operator!=()
bool ot::MatRecord::operator!= (MatRecord const & other) const inline
Overloaded != Operator.
Definition at line 168 of file matRecord.h.
operator<()
bool ot::MatRecord::operator< (MatRecord const & other) const inline
Overloaded < Operator.
Definition at line 173 of file matRecord.h.
References getColDim(), getColID(), getMatVal(), getRowDim(), and getRowID().
operator<=()
bool ot::MatRecord::operator<= (MatRecord const & other) const inline
Overloaded <= Operator.
Definition at line 207 of file matRecord.h.
operator=()
MatRecord& ot::MatRecord::operator= (MatRecord const & other) inline
The assignment operator.
Definition at line 151 of file matRecord.h.
References getColDim(), getColID(), getMatVal(), getRowDim(), and getRowID().
operator==()
bool ot::MatRecord::operator== (MatRecord const & other) const inline
Overloaded == Operator.
Definition at line 162 of file matRecord.h.
References getColDim(), getColID(), getMatVal(), getRowDim(), and getRowID().
operator>()
bool ot::MatRecord::operator> (MatRecord const & other) const inline
Overloaded > Operator.
Definition at line 202 of file matRecord.h.
operator>=()
bool ot::MatRecord::operator>= (MatRecord const & other) const inline
Overloaded >= Operator.
Definition at line 212 of file matRecord.h.
setColDim()
void ot::MatRecord::setColDim (RankI colDim) inline
sets the colDim value
Definition at line 75 of file matRecord.h.
References getMatVal(), MatRecord(), and setMatValue().
setColID()
void ot::MatRecord::setColID (RankI colID) inline
sets the rowID value
Definition at line 69 of file matRecord.h.
setMatValue()
void ot::MatRecord::setMatValue (DendroScalar value) inline
sets matrix value
Definition at line 136 of file matRecord.h.
Referenced by setColDim().
setRowDim()
void ot::MatRecord::setRowDim (RankI rowDim) inline
sets the rowDim value
Definition at line 72 of file matRecord.h.
setRowID()
void ot::MatRecord::setRowID (RankI rowID) inline
sets the rowID value
Definition at line 66 of file matRecord.h.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, MatRecord const & re) friend
Definition at line 216 of file matRecord.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/matRecord.h