DENDRO: ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType > Class Template Reference
ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType > Class Template Reference
#include <sfcTreeLoop.h>
Public Types
using C = unsigned int
using FrameT = Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >
using SubtreeInfoT = SubtreeInfo< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >
Public Member Functions
ConcreteType & asConcreteType ()
const TreeNode< C, dim > & getCurrentSubtree () const
SubtreeInfoT getSubtreeInfo ()
bool isFinished () const
bool isPre () const
bool next ()
void reset ()
bool step ()
Public Attributes
friend SubtreeInfoT
Static Public Attributes
static constexpr unsigned int NumChildren = 1u << dim
Protected Member Functions
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
const FrameT & getCurrentFrame () const
FrameT & getCurrentFrame ()
SFC_State< dim > getCurrentRotation () const
const FrameT & getRootFrame () const
FrameT & getRootFrame ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
SFC_TreeLoop (const TreeNode< C, dim > *sortedTreePart, size_t localTreeSz, unsigned int max_depth)
SFC_TreeLoop ()=delete
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Attributes
FrameInputs< dim, InputTypes >::DataStoreT m_rootInputData
FrameOutputs< dim, OutputTypes >::DataStoreT m_rootOutputData
SummaryType m_rootSummary
std::array< RankI,(1u<< dim)+1 > m_rootTreeSplitters
std::vector< FrameT > m_stack
const TreeNode< C, dim > * m_treePartPtr
Detailed Description
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType>
class ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >
Definition at line 106 of file sfcTreeLoop.h.
Member Typedef Documentation
C
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> using ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::C = unsigned int
Definition at line 218 of file sfcTreeLoop.h.
FrameT
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> using ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::FrameT = Frame<dim, InputTypes, OutputTypes, SummaryType, ConcreteType>
Definition at line 219 of file sfcTreeLoop.h.
SubtreeInfoT
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> using ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::SubtreeInfoT = SubtreeInfo<dim, InputTypes, OutputTypes, SummaryType, ConcreteType>
Definition at line 220 of file sfcTreeLoop.h.
Constructor & Destructor Documentation
SFC_TreeLoop() [1/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::SFC_TreeLoop (const TreeNode< C, dim > * sortedTreePart, size_t localTreeSz, unsigned int max_depth) inline protected
Definition at line 440 of file sfcTreeLoop.h.
SFC_TreeLoop() [2/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::SFC_TreeLoop () protected delete
Member Function Documentation
asConcreteType()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> ConcreteType& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::asConcreteType () inline
Definition at line 240 of file sfcTreeLoop.h.
bottomUpNodes()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> void ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::bottomUpNodes (FrameT & parentFrame, ExtantCellFlagT extantChildren) inline protected
bottomUpNodes() is responsible to
Resize the parent output buffers (handles to buffers are given);
Merge results from incident child output buffers (SFC order) into the parent output buffers.
The previously indicated extantChildren bit array (Morton order) will be supplied.
Utilities are provided to identify and iterate over incident children.
Definition at line 397 of file sfcTreeLoop.h.
child2Parent()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> void ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::child2Parent (FrameT & parentFrame, FrameT & childFrame) inline protected
child2Parent() is responsible to
Propagate hanging node data (possibly modified by the inspector) back to parent nodes, e.g., by applying interpolation transpose.
Definition at line 429 of file sfcTreeLoop.h.
getCurrentFrame() [1/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> const FrameT& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame () const inline protected
Definition at line 472 of file sfcTreeLoop.h.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNodesIn(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumNodesIn(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNodesIn(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNodesOut(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNodesOut(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNonhangingNodes(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNonhangingNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumNonhangingNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNonhangingNodes(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumTreeElements(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumTreeElements(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumTreeElements(), ot::MatvecBaseCoords< dim >::AccessSubtree::getSfcChildNum(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getSfcChildNum(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getSfcChildNum(), ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsIn(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::overwriteNodeValsIn(), ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsOut(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOut(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOutScalar(), ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeCoordsIn(), ot::MatvecBaseCoords< dim >::AccessSubtree::readNodeCoordsIn(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeCoordsIn(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeCoordsIn(), ot::MatvecBaseCoords< dim >::AccessSubtree::readNodeNonhangingIn(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeNonhangingIn(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeNonhangingIn(), ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeValsIn(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeValsIn(), ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeValsOut(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeValsOut().
getCurrentFrame() [2/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> FrameT& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame () inline protected
Definition at line 473 of file sfcTreeLoop.h.
getCurrentRotation()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> SFC_State<dim> ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentRotation () const inline protected
Definition at line 475 of file sfcTreeLoop.h.
getCurrentSubtree()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> const TreeNode<C,dim>& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree () const inline
Definition at line 341 of file sfcTreeLoop.h.
Referenced by ot::MatvecBase< dim, NodeT >::AccessSubtree::getCurrentSubtree(), ot::MatvecBaseCoords< dim >::AccessSubtree::getCurrentSubtree(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getCurrentSubtree(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getCurrentSubtree(), ot::MatvecBaseCoords< dim >::AccessSubtree::isElementBoundary(), ot::MatvecBase< dim, NodeT >::AccessSubtree::isElementBoundary(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isElementBoundary(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isElementBoundary().
getRootFrame() [1/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> const FrameT& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getRootFrame () const inline protected
Definition at line 468 of file sfcTreeLoop.h.
getRootFrame() [2/2]
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> FrameT& ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getRootFrame () inline protected
Definition at line 469 of file sfcTreeLoop.h.
getSubtreeInfo()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> SubtreeInfoT ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getSubtreeInfo () inline
Definition at line 253 of file sfcTreeLoop.h.
isFinished()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> bool ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::isFinished () const inline
Definition at line 336 of file sfcTreeLoop.h.
isPre()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> bool ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::isPre () const inline
Definition at line 330 of file sfcTreeLoop.h.
next()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> bool ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::next () inline
Definition at line 309 of file sfcTreeLoop.h.
parent2Child()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> void ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::parent2Child (FrameT & parentFrame, FrameT & childFrame) inline protected
parent2Child() is responsible to
Make available to the inspector any missing node data due to hanging nodes, e.g., by applying interpolation.
Definition at line 413 of file sfcTreeLoop.h.
reset()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> void ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::reset () inline
Definition at line 246 of file sfcTreeLoop.h.
step()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> bool ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::step () inline
m_stack.reserve(m_stack.size() + NumChildren); // Avoid invalidating references.
Definition at line 259 of file sfcTreeLoop.h.
topDownNodes()
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> void ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::topDownNodes (FrameT & parentFrame, ExtantCellFlagT * extantChildren) inline protected
void topDownNodes(FrameT &parentFrame, ExtantCellFlagT *extantChildren); void bottomUpNodes(FrameT &parentFrame, ExtantCellFlagT extantChildren); void parent2Child(FrameT &parentFrame, FrameT &childFrame); void child2Parent(FrameT &parentFrame, FrameT &childFrame); topDownNodes() is responsible to
Resize the child input buffers (SFC order) in the parent frame;
Duplicate elements of the parent input buffers to incident child input buffers (SFC order);
2.1. Initialize a summary object for each child (SFC order).
Indicate to SFC_TreeLoop which children to traverse, by accumulating into the extantChildren bit array (Morton order).
Restrictions
MAY NOT resize or write to parent input buffers.
MAY NOT resize or write to variably sized output buffers.
Utilities are provided to identify and iterate over incident children.
Definition at line 375 of file sfcTreeLoop.h.
Member Data Documentation
m_rootInputData
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> FrameInputs<dim, InputTypes>::DataStoreT ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_rootInputData protected
Definition at line 225 of file sfcTreeLoop.h.
m_rootOutputData
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> FrameOutputs<dim, OutputTypes>::DataStoreT ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_rootOutputData protected
Definition at line 226 of file sfcTreeLoop.h.
m_rootSummary
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> SummaryType ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_rootSummary protected
Definition at line 227 of file sfcTreeLoop.h.
m_rootTreeSplitters
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> std::array<RankI, (1u<<dim)+1> ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_rootTreeSplitters protected
Definition at line 229 of file sfcTreeLoop.h.
m_stack
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> std::vector<FrameT> ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_stack protected
Definition at line 231 of file sfcTreeLoop.h.
m_treePartPtr
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> const TreeNode<C, dim>* ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::m_treePartPtr protected
Definition at line 228 of file sfcTreeLoop.h.
NumChildren
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> constexpr unsigned int ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::NumChildren = 1u << dim static
Definition at line 236 of file sfcTreeLoop.h.
SubtreeInfoT
template<unsigned int dim, class InputTypes, class OutputTypes, typename SummaryType, class ConcreteType> friend ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::SubtreeInfoT
Definition at line 222 of file sfcTreeLoop.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop.h