DENDRO: ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost > Class Template Reference
ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost > Class Template Reference
Interface for MeshLoop templated on the type of iteration.
#include <meshLoop.h>
Classes
struct Iterator
Public Member Functions
Iterator begin ()
Iterator end ()
MeshLoopInterface_S_NS (vec_type &tnlist)
MeshLoopInterface_S_NS (TN *tnlist, size_t sz)
bool next ()
bool step ()
Public Member Functions inherited from ot::MeshLoopImpl< T, dim, TreatSorted >
const MeshLoopFrame< T, dim > & getTopConst () const
bool isFinished ()
bool isPre ()
MeshLoopImpl (TN *tnlist, size_t sz, bool vEmpty, bool vPre, bool vPost)
MeshLoopImpl ()=delete
bool next (bool vEmpty, bool vPre, bool vPost)
bool step (bool vEmpty, bool vPre, bool vPost)
Protected Member Functions
bool gotoNextPost ()
bool gotoNextPre ()
Protected Member Functions inherited from ot::MeshLoopImpl< T, dim, TreatSorted >
void bucketAndPush (RankI begin, RankI end, LevI lev, RotI pRot)
MeshLoopFrame< T, dim > & getTop ()
Additional Inherited Members
Public Types inherited from ot::MeshLoopImpl< T, dim, TreatSorted >
using TN = typename std::conditional< TreatSorted, const TreeNode< T, dim >, TreeNode< T, dim > >::type
Protected Attributes inherited from ot::MeshLoopImpl< T, dim, TreatSorted >
TN * m_ptr
std::vector< MeshLoopFrame< T, dim > > m_stack
size_t m_sz
Static Protected Attributes inherited from ot::MeshLoopImpl< T, dim, TreatSorted >
static constexpr unsigned int NumChildren = 1u << dim
Detailed Description
template<typename T, unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost>
class ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >
Interface for MeshLoop templated on the type of iteration.
Definition at line 25 of file meshLoop.h.
Constructor & Destructor Documentation
MeshLoopInterface_S_NS() [1/2]
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::MeshLoopInterface_S_NS (vec_type & tnlist) inline
Definition at line 60 of file meshLoop.h.
MeshLoopInterface_S_NS() [2/2]
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::MeshLoopInterface_S_NS (TN * tnlist, size_t sz) inline
Definition at line 64 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
Member Function Documentation
begin()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> Iterator ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::begin () inline
Definition at line 122 of file meshLoop.h.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::getTop().
end()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> Iterator ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::end () inline
Definition at line 123 of file meshLoop.h.
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::getTop().
gotoNextPost()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost () inline protected
Definition at line 133 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::next(), and ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step().
gotoNextPre()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre () inline protected
Definition at line 126 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::next(), and ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step().
next()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::next () inline
Definition at line 88 of file meshLoop.h.
References ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::next().
step()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step () inline
Definition at line 72 of file meshLoop.h.
References ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPost(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::gotoNextPre(), ot::MeshLoopImpl< T, dim, TreatSorted >::isPre(), and ot::MeshLoopImpl< T, dim, TreatSorted >::step().
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator++().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/meshLoop.h