DENDRO: Point< dim > Class Template Reference
Point< dim > Class Template Reference
A point class.
#include <point.h>
Public Member Functions
double abs ()
Point cross (Point Other)
double dot (Point other)
double dot3 (Point Other)
void normalize ()
Constructors and Destructor
Point ()
Point (double scale)
Point (const std::array< double, dim > &newCoords)
Point (const double *newCoords)
Point (double newx, double newy, double newz)
Point (int newx, int newy, int newz)
Point (unsigned int newx, unsigned int newy, unsigned int newz)
Point (const Point &newpoint)
Getters
const double & x () const
const double & y () const
const double & z () const
const double & x (unsigned d) const
int xint () const
int yint () const
int zint () const
int xint (unsigned d) const
Overloaded Operators
Point operator- () const
void operator+= (const Point &other)
void operator-= (const Point &other)
void operator/= (const int divisor)
void operator/= (const double divisor)
void operator*= (const int factor)
void operator*= (const double factor)
Point & operator= (const Point &other)
Point operator+ (const Point &other) const
Point operator- (const Point &other) const
Point operator/ (const double divisor) const
Point operator* (const double factor) const
double magnitude ()
bool operator!= (const Point &other)
{ return ((xint() != other.xint()) || (yint() != other.yint()) || (zint() != other.zint())); };
bool operator== (const Point &other)
{ return ((xint() == other.xint()) && (yint() == other.yint()) && (zint() == other.zint())); };
Static Public Member Functions
static Point TransMatMultiply (double *transMat, Point inPoint)
static Point TransMatMultiply3 (double *transMat, Point inPoint)
Static Public Attributes
static constexpr unsigned int m_uiDim = (dim > 3 ? dim : 3)
Protected Member Functions
void initialize3 (double newx, double newy, double newz)
Protected Attributes
std::array< double, m_uiDim > _coords
double & _x = _coords[0]
double & _y = _coords[1]
double & _z = _coords[2]
Detailed Description
template<unsigned int dim>
class Point< dim >
A point class.
Author
Hari Sundar
Masado Ishii
Definition at line 38 of file point.h.
Constructor & Destructor Documentation
Point() [1/8]
template<unsigned int dim> Point< dim >::Point ()
Definition at line 139 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::cross().
Point() [2/8]
template<unsigned int dim> Point< dim >::Point (double scale)
Definition at line 145 of file point.h.
References Point< dim >::_coords.
Point() [3/8]
template<unsigned int dim> Point< dim >::Point (const std::array< double, dim > & newCoords)
Definition at line 151 of file point.h.
References Point< dim >::_coords, and Point< dim >::m_uiDim.
Point() [4/8]
template<unsigned int dim> Point< dim >::Point (const double * newCoords)
Definition at line 158 of file point.h.
References Point< dim >::_coords, and Point< dim >::m_uiDim.
Point() [5/8]
template<unsigned int dim> Point< dim >::Point (double newx, double newy, double newz)
Definition at line 165 of file point.h.
References Point< dim >::initialize3().
Point() [6/8]
template<unsigned int dim> Point< dim >::Point (int newx, int newy, int newz)
Definition at line 171 of file point.h.
References Point< dim >::initialize3().
Point() [7/8]
template<unsigned int dim> Point< dim >::Point (unsigned int newx, unsigned int newy, unsigned int newz)
Definition at line 179 of file point.h.
References Point< dim >::initialize3().
Point() [8/8]
template<unsigned int dim> Point< dim >::Point (const Point< dim > & newpoint)
Definition at line 187 of file point.h.
References Point< dim >::_coords.
Member Function Documentation
abs()
template<unsigned int dim> double Point< dim >::abs () inline
Definition at line 121 of file point.h.
References Point< dim >::dot(), Point< dim >::initialize3(), Point< dim >::normalize(), Point< dim >::TransMatMultiply(), and Point< dim >::TransMatMultiply3().
Referenced by Point< dim >::magnitude(), and Point< dim >::normalize().
cross()
template<unsigned int dim> Point Point< dim >::cross (Point< dim > Other) inline
Definition at line 116 of file point.h.
References Point< dim >::_x, Point< dim >::_y, Point< dim >::_z, and Point< dim >::Point().
dot()
template<unsigned int dim> double Point< dim >::dot (Point< dim > other) inline
Definition at line 104 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::abs().
dot3()
template<unsigned int dim> double Point< dim >::dot3 (Point< dim > Other) inline
Definition at line 112 of file point.h.
References Point< dim >::_x, Point< dim >::_y, and Point< dim >::_z.
initialize3()
template<unsigned int dim> void Point< dim >::initialize3 (double newx, double newy, double newz) inline protected
Definition at line 200 of file point.h.
References Point< dim >::_x, Point< dim >::_y, and Point< dim >::_z.
Referenced by Point< dim >::abs(), and Point< dim >::Point().
magnitude()
template<unsigned int dim> double Point< dim >::magnitude ()
Definition at line 337 of file point.h.
References Point< dim >::abs().
Referenced by Point< dim >::xint().
normalize()
template<unsigned int dim> void Point< dim >::normalize ()
Definition at line 332 of file point.h.
References Point< dim >::abs(), and Point< dim >::operator/=().
Referenced by Point< dim >::abs().
operator!=()
template<unsigned int dim> bool Point< dim >::operator!= (const Point< dim > & other) inline
{ return ((xint() != other.xint()) || (yint() != other.yint()) || (zint() != other.zint())); };
Definition at line 89 of file point.h.
References Point< dim >::xint().
operator*()
template<unsigned int dim> Point< dim > Point< dim >::operator* (const double factor) const inline
Definition at line 289 of file point.h.
Referenced by Point< dim >::xint().
operator*=() [1/2]
template<unsigned int dim> void Point< dim >::operator*= (const int factor) inline
Definition at line 215 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::xint().
operator*=() [2/2]
template<unsigned int dim> void Point< dim >::operator*= (const double factor) inline
Definition at line 222 of file point.h.
References Point< dim >::_coords.
operator+()
template<unsigned int dim> Point< dim > Point< dim >::operator+ (const Point< dim > & other) const inline
Definition at line 266 of file point.h.
Referenced by Point< dim >::xint().
operator+=()
template<unsigned int dim> void Point< dim >::operator+= (const Point< dim > & other) inline
Definition at line 245 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::xint().
operator-() [1/2]
template<unsigned int dim> Point< dim > Point< dim >::operator- () const inline
Definition at line 206 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::xint().
operator-() [2/2]
template<unsigned int dim> Point< dim > Point< dim >::operator- (const Point< dim > & other) const inline
Definition at line 259 of file point.h.
operator-=()
template<unsigned int dim> void Point< dim >::operator-= (const Point< dim > & other) inline
Definition at line 252 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::xint().
operator/()
template<unsigned int dim> Point< dim > Point< dim >::operator/ (const double divisor) const inline
Definition at line 281 of file point.h.
Referenced by Point< dim >::xint().
operator/=() [1/2]
template<unsigned int dim> void Point< dim >::operator/= (const int divisor) inline
Definition at line 229 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::normalize(), and Point< dim >::xint().
operator/=() [2/2]
template<unsigned int dim> void Point< dim >::operator/= (const double divisor) inline
Definition at line 237 of file point.h.
References Point< dim >::_coords.
operator=()
template<unsigned int dim> Point< dim > & Point< dim >::operator= (const Point< dim > & other) inline
Definition at line 273 of file point.h.
References Point< dim >::_coords.
Referenced by Point< dim >::xint().
operator==()
template<unsigned int dim> bool Point< dim >::operator== (const Point< dim > & other) inline
{ return ((xint() == other.xint()) && (yint() == other.yint()) && (zint() == other.zint())); };
Definition at line 96 of file point.h.
References Point< dim >::xint().
TransMatMultiply()
template<unsigned int dim> Point< dim > Point< dim >::TransMatMultiply (double * transMat, Point< dim > inPoint) static
Definition at line 312 of file point.h.
References Point< dim >::_coords, and Point< dim >::TransMatMultiply3().
Referenced by Point< dim >::abs().
TransMatMultiply3()
template<unsigned int dim> Point< dim > Point< dim >::TransMatMultiply3 (double * transMat, Point< dim > inPoint) static
Definition at line 297 of file point.h.
References Point< dim >::_x, Point< dim >::_y, and Point< dim >::_z.
Referenced by Point< dim >::abs(), and Point< dim >::TransMatMultiply().
x() [1/2]
template<unsigned int dim> const double& Point< dim >::x () const inline
Definition at line 58 of file point.h.
References Point< dim >::_x.
x() [2/2]
template<unsigned int dim> const double& Point< dim >::x (unsigned d) const inline
Definition at line 61 of file point.h.
References Point< dim >::_coords.
xint() [1/2]
template<unsigned int dim> int Point< dim >::xint () const inline
Definition at line 63 of file point.h.
References Point< dim >::_x.
Referenced by Point< dim >::operator!=(), and Point< dim >::operator==().
xint() [2/2]
template<unsigned int dim> int Point< dim >::xint (unsigned d) const inline
Definition at line 66 of file point.h.
References Point< dim >::_coords, Point< dim >::magnitude(), Point< dim >::operator*(), Point< dim >::operator*=(), Point< dim >::operator+(), Point< dim >::operator+=(), Point< dim >::operator-(), Point< dim >::operator-=(), Point< dim >::operator/(), Point< dim >::operator/=(), and Point< dim >::operator=().
y()
template<unsigned int dim> const double& Point< dim >::y () const inline
Definition at line 59 of file point.h.
References Point< dim >::_y.
yint()
template<unsigned int dim> int Point< dim >::yint () const inline
Definition at line 64 of file point.h.
References Point< dim >::_y.
z()
template<unsigned int dim> const double& Point< dim >::z () const inline
Definition at line 60 of file point.h.
References Point< dim >::_z.
zint()
template<unsigned int dim> int Point< dim >::zint () const inline
Definition at line 65 of file point.h.
References Point< dim >::_z.
Member Data Documentation
_coords
template<unsigned int dim> std::array<double,m_uiDim> Point< dim >::_coords protected
Definition at line 132 of file point.h.
Referenced by Point< dim >::dot(), Point< dim >::operator*=(), Point< dim >::operator+=(), Point< dim >::operator-(), Point< dim >::operator-=(), Point< dim >::operator/=(), Point< dim >::operator=(), Point< dim >::Point(), Point< dim >::TransMatMultiply(), Point< dim >::x(), and Point< dim >::xint().
_x
template<unsigned int dim> double& Point< dim >::_x = _coords[0] protected
Definition at line 133 of file point.h.
Referenced by Point< dim >::cross(), Point< dim >::dot3(), Point< dim >::initialize3(), Point< dim >::TransMatMultiply3(), Point< dim >::x(), and Point< dim >::xint().
_y
template<unsigned int dim> double& Point< dim >::_y = _coords[1] protected
Definition at line 134 of file point.h.
Referenced by Point< dim >::cross(), Point< dim >::dot3(), Point< dim >::initialize3(), Point< dim >::TransMatMultiply3(), Point< dim >::y(), and Point< dim >::yint().
_z
template<unsigned int dim> double& Point< dim >::_z = _coords[2] protected
Definition at line 135 of file point.h.
Referenced by Point< dim >::cross(), Point< dim >::dot3(), Point< dim >::initialize3(), Point< dim >::TransMatMultiply3(), Point< dim >::z(), and Point< dim >::zint().
m_uiDim
template<unsigned int dim> constexpr unsigned int Point< dim >::m_uiDim = (dim > 3 ? dim : 3) static
Definition at line 40 of file point.h.
Referenced by Point< dim >::Point().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/point.h