DENDRO: periodic::PCoord< T, dim > Class Template Reference
periodic::PCoord< T, dim > Class Template Reference
Periodic integer coordinates glued by modulus operator. Specifies the period of the lattice in each axis. By default the period is the number of representable values, i.e. effectively non-periodic. If a finite period is specified, then each point is mapped to it's canonical representative upon construction.
#include <pcoord.h>
Classes
class CoordTransfer
Public Member Functions
CoordTransfer coord (int axis) const
void coord (int axis, const CoordTransfer &coord)
void coord (int axis, T coord)
const std::array< T, dim > & coords () const
operator std::array< T, dim > () const
bool operator!= (const PCoord &b) const
PCoord operator+ (const PCoord &b) const
PCoord & operator+= (const PCoord &b)
PCoord operator- (const PCoord &b) const
PCoord & operator-= (const PCoord &b)
PCoord & operator= (const PCoord &)=default
PCoord & operator= (PCoord &&)=default
bool operator== (const PCoord &b) const
PCoord ()
PCoord (const std::array< T, dim > coords)
PCoord (const PCoord &)=default
PCoord (PCoord &&)=default
void truncate (int bottomLevels)
PCoord truncated (int bottomLevels) const
Static Public Member Functions
static T map (int axis, T coord)
static T period (int axis)
static void period (int axis, T period)
static std::array< T, dim > periods ()
static void periods (const std::array< T, dim > &periods)
Detailed Description
template<typename T, int dim>
class periodic::PCoord< T, dim >
Periodic integer coordinates glued by modulus operator. Specifies the period of the lattice in each axis. By default the period is the number of representable values, i.e. effectively non-periodic. If a finite period is specified, then each point is mapped to it's canonical representative upon construction.
Definition at line 26 of file pcoord.h.
Constructor & Destructor Documentation
PCoord() [1/4]
template<typename T , int dim> periodic::PCoord< T, dim >::PCoord () inline
Definition at line 170 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::map().
PCoord() [2/4]
template<typename T, int dim> periodic::PCoord< T, dim >::PCoord (const std::array< T, dim > coords) inline
Definition at line 177 of file pcoord.h.
PCoord() [3/4]
template<typename T, int dim> periodic::PCoord< T, dim >::PCoord (const PCoord< T, dim > &) inline default
PCoord() [4/4]
template<typename T, int dim> periodic::PCoord< T, dim >::PCoord (PCoord< T, dim > &&) inline default
Member Function Documentation
coord() [1/3]
template<typename T , int dim> PCoord< T, dim >::CoordTransfer periodic::PCoord< T, dim >::coord (int axis) const inline
Definition at line 185 of file pcoord.h.
Referenced by periodic::PRange< T, dim >::closedContains(), periodic::PCoord< unsigned int, dim >::coord(), periodic::PCoord< unsigned int, dim >::map(), periodic::PCoord< T, dim >::CoordTransfer::operator T(), periodic::PCoord< unsigned int, dim >::operator!=(), periodic::PCoord< unsigned int, dim >::operator+(), periodic::PCoord< unsigned int, dim >::operator-(), periodic::PCoord< unsigned int, dim >::PCoord(), and periodic::PRange< T, dim >::PRange().
coord() [2/3]
template<typename T, int dim> void periodic::PCoord< T, dim >::coord (int axis, const CoordTransfer & coord) inline
coord() [3/3]
template<typename T, int dim> void periodic::PCoord< T, dim >::coord (int axis, T coord) inline
Definition at line 201 of file pcoord.h.
coords()
template<typename T, int dim> const std::array<T, dim>& periodic::PCoord< T, dim >::coords () const inline
Definition at line 68 of file pcoord.h.
Referenced by ot::TreeNode< T, D >::getX(), and periodic::PCoord< unsigned int, dim >::map().
map()
template<typename T, int dim> static T periodic::PCoord< T, dim >::map (int axis, T coord) inline static
Definition at line 40 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coord(), periodic::PRange< T, dim >::halfClosedContains(), periodic::PRange< T, dim >::openContains(), and periodic::PRange< T, dim >::upperEquals().
operator std::array< T, dim >()
template<typename T, int dim> periodic::PCoord< T, dim >::operator std::array< T, dim > () const inline
Definition at line 67 of file pcoord.h.
operator!=()
template<typename T , int dim> bool periodic::PCoord< T, dim >::operator!= (const PCoord< T, dim > & b) const inline
Definition at line 254 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords(), and periodic::PCoord< unsigned int, dim >::operator==().
operator+()
template<typename T , int dim> PCoord< T, dim > periodic::PCoord< T, dim >::operator+ (const PCoord< T, dim > & b) const inline
Definition at line 208 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
operator+=()
template<typename T , int dim> PCoord< T, dim > & periodic::PCoord< T, dim >::operator+= (const PCoord< T, dim > & b) inline
Definition at line 233 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
operator-()
template<typename T , int dim> PCoord< T, dim > periodic::PCoord< T, dim >::operator- (const PCoord< T, dim > & b) const inline
Definition at line 218 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
operator-=()
template<typename T , int dim> PCoord< T, dim > & periodic::PCoord< T, dim >::operator-= (const PCoord< T, dim > & b) inline
Definition at line 240 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
operator=() [1/2]
template<typename T, int dim> PCoord& periodic::PCoord< T, dim >::operator= (const PCoord< T, dim > &) inline default
Referenced by periodic::PCoord< unsigned int, dim >::map().
operator=() [2/2]
template<typename T, int dim> PCoord& periodic::PCoord< T, dim >::operator= (PCoord< T, dim > &&) inline default
operator==()
template<typename T , int dim> bool periodic::PCoord< T, dim >::operator== (const PCoord< T, dim > & b) const inline
Definition at line 247 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
period() [1/2]
template<typename T , int dim> T periodic::PCoord< T, dim >::period (int axis) inline static
Definition at line 135 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::operator-().
period() [2/2]
template<typename T, int dim> void periodic::PCoord< T, dim >::period (int axis, T period) inline static
Definition at line 142 of file pcoord.h.
periods() [1/2]
template<typename T , int dim> std::array< T, dim > periodic::PCoord< T, dim >::periods () inline static
Definition at line 152 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::periods().
periods() [2/2]
template<typename T, int dim> void periodic::PCoord< T, dim >::periods (const std::array< T, dim > & periods) inline static
Definition at line 162 of file pcoord.h.
truncate()
template<typename T , int dim> void periodic::PCoord< T, dim >::truncate (int bottomLevels) inline
Definition at line 263 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords(), and periodic::PCoord< unsigned int, dim >::truncated().
truncated()
template<typename T , int dim> PCoord< T, dim > periodic::PCoord< T, dim >::truncated (int bottomLevels) const inline
Definition at line 271 of file pcoord.h.
Referenced by periodic::PCoord< unsigned int, dim >::coords().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/pcoord.h