DENDRO: ot::DistTree< T, dim > Class Template Reference
ot::DistTree< T, dim > Class Template Reference
Intermediate container for filtering trees before creating the DA.
#include <distTree.h>
Classes
struct BoxDecider
Public Types
enum CoalesceOption : bool { NoCoalesce = false, Coalesce = true }
using LivePtr = std::weak_ptr< const DistTree >
using LivePtrOwner = std::shared_ptr< const DistTree >
Public Member Functions
template<typename T >
DistTree< C, dim > constructDistTreeByFunc (std::function< void(const T *, T *)> func, unsigned int dofSz, MPI_Comm comm, unsigned int order, double interp_tol, double sfc_tol)
void destroyTree ()
DistTree ()
DistTree (std::vector< TreeNode< T, dim >> &treePart, MPI_Comm comm, CoalesceOption coalesceSiblings=Coalesce)
DistTree (const DistTree &other)
DistTree (DistTree &&other)
void filterTree (const ::ibm::DomainDecider &domainDecider)
DistTree generateGridHierarchyDown (unsigned int numStrata, double loadFlexibility)
DistTree generateGridHierarchyUp (bool isFixedNumStrata, unsigned int lev, double loadFlexibility)
MPI_Comm getComm () const
const ::ibm::DomainDecider & getDomainDecider () const
size_t getFilteredTreePartSz (int stratum=0) const
int getNumStrata () const
TreeNode< T, dim > getTreePartBack (int stratum=0) const
const std::vector< TreeNode< T, dim > > & getTreePartFiltered (int stratum=0) const
TreeNode< T, dim > getTreePartFront (int stratum=0) const
LivePtr live_ptr () const
DistTree & operator= (const DistTree &other)
DistTree & operator= (DistTree &&other)
DistTree repartitioned (const double sfc_tol) &&
Usage: dtree = std::move(dtree).repartitioned(sfc_tol);.
~DistTree ()
Static Public Member Functions
template<typename D >
static DistTree constructDistTreeByFunc (std::function< void(const D *, D *)> func, unsigned int dofSz, MPI_Comm comm, unsigned int order, double interp_tol, double sfc_tol)
static DistTree constructSubdomainDistTree (unsigned int finestLevel, MPI_Comm comm, double sfc_tol=0.3)
static DistTree constructSubdomainDistTree (unsigned int finestLevel, const ::ibm::DomainDecider &domainDecider_phys, MPI_Comm comm, double sfc_tol=0.3)
::ibm::Partition defaultDomainDecider (const double *physCoords, double physSize)
static void defineCoarsenedGrid (DistTree &distTree, DistTree &surrDistTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, GridAlignment gridAlignment, double loadFlexibility)
static void distRefine (const DistTree &inTree, std::vector< int > &&delta_level, DistTree &outTree, double sfc_tol, bool repartition=false)
static void distRemeshSubdomain (const DistTree &inTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, DistTree &outTree, DistTree &surrogateTree, RemeshPartition remeshPartition, double loadFlexibility)
static void distRemeshSubdomainViaWhole (const DistTree &inTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, DistTree &outTree, DistTree &surrogateTree, RemeshPartition remeshPartition, double loadFlexibility)
: Uses DistTree filter function to carve out subdomain from remeshed tree.
static void filterOctList (const ::ibm::DomainDecider &domainDecider, std::vector< TreeNode< T, dim >> &treeNodeElem)
static void insertRefinedGrid (DistTree &distTree, DistTree &surrDistTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, GridAlignment gridAlignment, double loadFlexibility)
static DistTree minimalSubdomainDistTree (unsigned int finestLevel, const ::ibm::DomainDecider &domainDecider_phys, MPI_Comm comm, double sfc_tol=0.3)
static DistTree minimalSubdomainDistTreeGrain (size_t grainMin, const ::ibm::DomainDecider &domainDecider_phys, MPI_Comm comm, double sfc_tol=0.3)
Protected Member Functions
void assignDomainDecider (const ::ibm::DomainDecider &domainDecider)
::ibm::Partition conversionDomainDeciderTN_asCell (const TreeNode< T, dim > &tn)
::ibm::Partition conversionDomainDeciderTN_asPoint (const TreeNode< T, dim > &tn)
void filterStratum (int stratum)
TreeNode< T, dim > & get_m_treePartBack ()
const TreeNode< T, dim > & get_m_treePartBack () const
std::vector< TreeNode< T, dim > > & get_m_treePartFiltered ()
const std::vector< TreeNode< T, dim > > & get_m_treePartFiltered () const
TreeNode< T, dim > & get_m_treePartFront ()
const TreeNode< T, dim > & get_m_treePartFront () const
void insertStratum (int newStratum, std::vector< TreeNode< T, dim >> &treePart)
LazyPerishable< LivePtrOwner > & lazy_live_ptr () const
void replaceStratum (int atStratum, std::vector< TreeNode< T, dim >> &treePart)
Protected Attributes
LazyPerishable< LivePtrOwner > m_alive
CoalesceOption m_coalesceSiblings
MPI_Comm m_comm
::ibm::DomainDecider m_domainDecider
std::function<::ibm::Partition(const TreeNode< T, dim > &treeNodeElem)> m_domainDeciderTN_asCell
std::function<::ibm::Partition(const TreeNode< T, dim > &treeNodeElem)> m_domainDeciderTN_asPoint
std::vector< size_t > m_filteredTreePartSz
std::vector< std::vector< TreeNode< T, dim > > > m_gridStrata
bool m_hasBeenFiltered
int m_numStrata
std::vector< size_t > m_originalTreePartSz
std::vector< TreeNode< T, dim > > m_tpBackStrata
std::vector< TreeNode< T, dim > > m_tpFrontStrata
Detailed Description
template<typename T, unsigned int dim>
class ot::DistTree< T, dim >
Intermediate container for filtering trees before creating the DA.
Note
DistTree takes ownership of the provided TreeNodes and empties the provided std::vector.
It is intended that, during construction of the DA, the tree vector held by DistTree will be destroyed.
Create a DistTree from a partitioned complete tree, i.e. taking union of the TreeNodes across all processors should be the entire unit hypercube. If you want to filter the domain to a subset of the unit hypercube, use DistTree to accomplish that.
A default filter function is provided and applied upon construction. To provide a custom filter function, call filterTree().
DistTree remembers the front and back TreeNode from the original partition.
The partition cannot be changed without creating a new DistTree.
Definition at line 45 of file distTree.h.
Member Typedef Documentation
LivePtr
template<typename T, unsigned int dim> using ot::DistTree< T, dim >::LivePtr = std::weak_ptr<const DistTree>
Definition at line 260 of file distTree.h.
LivePtrOwner
template<typename T, unsigned int dim> using ot::DistTree< T, dim >::LivePtrOwner = std::shared_ptr<const DistTree>
Definition at line 261 of file distTree.h.
Member Enumeration Documentation
CoalesceOption
template<typename T, unsigned int dim> enum ot::DistTree::CoalesceOption : bool
Enumerator
NoCoalesce
Coalesce
Definition at line 48 of file distTree.h.
Constructor & Destructor Documentation
DistTree() [1/4]
template<typename T , unsigned int dim> ot::DistTree< T, dim >::DistTree ()
Definition at line 343 of file distTree.h.
DistTree() [2/4]
template<typename T, unsigned int dim> ot::DistTree< T, dim >::DistTree (std::vector< TreeNode< T, dim >> & treePart, MPI_Comm comm, CoalesceOption coalesceSiblings = Coalesce)
Definition at line 362 of file distTree.h.
DistTree() [3/4]
template<typename T, unsigned int dim> ot::DistTree< T, dim >::DistTree (const DistTree< T, dim > & other) inline
Definition at line 54 of file distTree.h.
DistTree() [4/4]
template<typename T, unsigned int dim> ot::DistTree< T, dim >::DistTree (DistTree< T, dim > && other) inline
Definition at line 55 of file distTree.h.
~DistTree()
template<typename T, unsigned int dim> ot::DistTree< T, dim >::~DistTree () inline
MPI_Comm_free(&m_comm);
Definition at line 92 of file distTree.h.
Member Function Documentation
assignDomainDecider()
template<typename T, unsigned int dim> void ot::DistTree< T, dim >::assignDomainDecider (const ::ibm::DomainDecider & domainDecider) protected
Definition at line 528 of file distTree.h.
Referenced by ot::DistTree< C, dim >::get_m_treePartBack().
constructDistTreeByFunc() [1/2]
template<typename T, unsigned int dim> template<typename D > static DistTree ot::DistTree< T, dim >::constructDistTreeByFunc (std::function< void(const D *, D *)> func, unsigned int dofSz, MPI_Comm comm, unsigned int order, double interp_tol, double sfc_tol) static
Referenced by ot::DistTree< C, dim >::DistTree().
constructDistTreeByFunc() [2/2]
template<typename T, unsigned int dim> template<typename T > DistTree<C, dim> ot::DistTree< T, dim >::constructDistTreeByFunc (std::function< void(const T *, T *)> func, unsigned int dofSz, MPI_Comm comm, unsigned int order, double interp_tol, double sfc_tol)
Definition at line 436 of file distTree.h.
constructSubdomainDistTree() [1/2]
template<typename T, unsigned int dim> static DistTree ot::DistTree< T, dim >::constructSubdomainDistTree (unsigned int finestLevel, MPI_Comm comm, double sfc_tol = 0.3) static
Referenced by ot::DistTree< C, dim >::DistTree().
constructSubdomainDistTree() [2/2]
template<typename T, unsigned int dim> static DistTree ot::DistTree< T, dim >::constructSubdomainDistTree (unsigned int finestLevel, const ::ibm::DomainDecider & domainDecider_phys, MPI_Comm comm, double sfc_tol = 0.3) static
conversionDomainDeciderTN_asCell()
template<typename T, unsigned int dim> ::ibm::Partition ot::DistTree< T, dim >::conversionDomainDeciderTN_asCell (const TreeNode< T, dim > & tn) inline protected
Definition at line 318 of file distTree.h.
conversionDomainDeciderTN_asPoint()
template<typename T, unsigned int dim> ::ibm::Partition ot::DistTree< T, dim >::conversionDomainDeciderTN_asPoint (const TreeNode< T, dim > & tn) inline protected
Definition at line 327 of file distTree.h.
defaultDomainDecider()
template<typename T, unsigned int dim> ::ibm::Partition ot::DistTree< T, dim >::defaultDomainDecider (const double * physCoords, double physSize) inline static
Definition at line 183 of file distTree.h.
defineCoarsenedGrid()
template<typename T, unsigned int dim> static void ot::DistTree< T, dim >::defineCoarsenedGrid (DistTree< T, dim > & distTree, DistTree< T, dim > & surrDistTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, GridAlignment gridAlignment, double loadFlexibility) static
Referenced by ot::DistTree< C, dim >::~DistTree().
destroyTree()
template<typename T , unsigned int dim> void ot::DistTree< T, dim >::destroyTree ()
Definition at line 513 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
distRefine()
template<typename T, unsigned int dim> static void ot::DistTree< T, dim >::distRefine (const DistTree< T, dim > & inTree, std::vector< int > && delta_level, DistTree< T, dim > & outTree, double sfc_tol, bool repartition = false) static
Referenced by ot::DistTree< C, dim >::~DistTree().
distRemeshSubdomain()
template<typename T, unsigned int dim> static void ot::DistTree< T, dim >::distRemeshSubdomain (const DistTree< T, dim > & inTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, DistTree< T, dim > & outTree, DistTree< T, dim > & surrogateTree, RemeshPartition remeshPartition, double loadFlexibility) static
Referenced by ot::DistTree< C, dim >::~DistTree().
distRemeshSubdomainViaWhole()
template<typename T, unsigned int dim> static void ot::DistTree< T, dim >::distRemeshSubdomainViaWhole (const DistTree< T, dim > & inTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, DistTree< T, dim > & outTree, DistTree< T, dim > & surrogateTree, RemeshPartition remeshPartition, double loadFlexibility) static
: Uses DistTree filter function to carve out subdomain from remeshed tree.
distRemeshSubdomain
Referenced by ot::DistTree< C, dim >::~DistTree().
filterOctList()
template<typename T, unsigned int dim> void ot::DistTree< T, dim >::filterOctList (const ::ibm::DomainDecider & domainDecider, std::vector< TreeNode< T, dim >> & treeNodeElem) static
Definition at line 568 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
filterStratum()
template<typename T , unsigned int dim> void ot::DistTree< T, dim >::filterStratum (int stratum) protected
Definition at line 557 of file distTree.h.
Referenced by ot::DistTree< C, dim >::get_m_treePartBack().
filterTree()
template<typename T , unsigned int dim> void ot::DistTree< T, dim >::filterTree (const ::ibm::DomainDecider & domainDecider)
Definition at line 543 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
generateGridHierarchyDown()
template<typename T, unsigned int dim> DistTree ot::DistTree< T, dim >::generateGridHierarchyDown (unsigned int numStrata, double loadFlexibility)
Referenced by ot::DistTree< C, dim >::~DistTree().
generateGridHierarchyUp()
template<typename T, unsigned int dim> DistTree ot::DistTree< T, dim >::generateGridHierarchyUp (bool isFixedNumStrata, unsigned int lev, double loadFlexibility)
Referenced by ot::DistTree< C, dim >::~DistTree().
get_m_treePartBack() [1/2]
template<typename T, unsigned int dim> TreeNode<T, dim>& ot::DistTree< T, dim >::get_m_treePartBack () inline protected
Definition at line 296 of file distTree.h.
get_m_treePartBack() [2/2]
template<typename T, unsigned int dim> const TreeNode<T, dim>& ot::DistTree< T, dim >::get_m_treePartBack () const inline protected
Definition at line 297 of file distTree.h.
get_m_treePartFiltered() [1/2]
template<typename T, unsigned int dim> std::vector<TreeNode<T, dim> >& ot::DistTree< T, dim >::get_m_treePartFiltered () inline protected
Definition at line 292 of file distTree.h.
get_m_treePartFiltered() [2/2]
template<typename T, unsigned int dim> const std::vector<TreeNode<T, dim> >& ot::DistTree< T, dim >::get_m_treePartFiltered () const inline protected
Definition at line 293 of file distTree.h.
get_m_treePartFront() [1/2]
template<typename T, unsigned int dim> TreeNode<T, dim>& ot::DistTree< T, dim >::get_m_treePartFront () inline protected
Definition at line 294 of file distTree.h.
get_m_treePartFront() [2/2]
template<typename T, unsigned int dim> const TreeNode<T, dim>& ot::DistTree< T, dim >::get_m_treePartFront () const inline protected
Definition at line 295 of file distTree.h.
getComm()
template<typename T, unsigned int dim> MPI_Comm ot::DistTree< T, dim >::getComm () const inline
Definition at line 178 of file distTree.h.
getDomainDecider()
template<typename T , unsigned int dim> const ::ibm::DomainDecider & ot::DistTree< T, dim >::getDomainDecider () const
Definition at line 601 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
getFilteredTreePartSz()
template<typename T , unsigned int dim> size_t ot::DistTree< T, dim >::getFilteredTreePartSz (int stratum = 0) const
Definition at line 622 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
getNumStrata()
template<typename T, unsigned int dim> int ot::DistTree< T, dim >::getNumStrata () const inline
Definition at line 176 of file distTree.h.
getTreePartBack()
template<typename T , unsigned int dim> TreeNode< T, dim > ot::DistTree< T, dim >::getTreePartBack (int stratum = 0) const
Definition at line 642 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
getTreePartFiltered()
template<typename T , unsigned int dim> const std::vector< TreeNode< T, dim > > & ot::DistTree< T, dim >::getTreePartFiltered (int stratum = 0) const
Definition at line 612 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
getTreePartFront()
template<typename T , unsigned int dim> TreeNode< T, dim > ot::DistTree< T, dim >::getTreePartFront (int stratum = 0) const
Definition at line 632 of file distTree.h.
Referenced by ot::DistTree< C, dim >::~DistTree().
insertRefinedGrid()
template<typename T, unsigned int dim> static void ot::DistTree< T, dim >::insertRefinedGrid (DistTree< T, dim > & distTree, DistTree< T, dim > & surrDistTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, GridAlignment gridAlignment, double loadFlexibility) static
Referenced by ot::DistTree< C, dim >::~DistTree().
insertStratum()
template<typename T, unsigned int dim> void ot::DistTree< T, dim >::insertStratum (int newStratum, std::vector< TreeNode< T, dim >> & treePart) protected
Definition at line 393 of file distTree.h.
Referenced by ot::DistTree< C, dim >::get_m_treePartBack().
lazy_live_ptr()
template<typename T, unsigned int dim> LazyPerishable<LivePtrOwner>& ot::DistTree< T, dim >::lazy_live_ptr () const inline protected
Definition at line 306 of file distTree.h.
Referenced by ot::DistTree< C, dim >::live_ptr().
live_ptr()
template<typename T, unsigned int dim> LivePtr ot::DistTree< T, dim >::live_ptr () const inline
Definition at line 268 of file distTree.h.
minimalSubdomainDistTree()
template<typename T, unsigned int dim> static DistTree ot::DistTree< T, dim >::minimalSubdomainDistTree (unsigned int finestLevel, const ::ibm::DomainDecider & domainDecider_phys, MPI_Comm comm, double sfc_tol = 0.3) static
Referenced by ot::DistTree< C, dim >::DistTree().
minimalSubdomainDistTreeGrain()
template<typename T, unsigned int dim> static DistTree ot::DistTree< T, dim >::minimalSubdomainDistTreeGrain (size_t grainMin, const ::ibm::DomainDecider & domainDecider_phys, MPI_Comm comm, double sfc_tol = 0.3) static
Referenced by ot::DistTree< C, dim >::DistTree().
operator=() [1/2]
template<typename T , unsigned int dim> DistTree< T, dim > & ot::DistTree< T, dim >::operator= (const DistTree< T, dim > & other)
Definition at line 471 of file distTree.h.
Referenced by ot::DistTree< C, dim >::DistTree().
operator=() [2/2]
template<typename T , unsigned int dim> DistTree< T, dim > & ot::DistTree< T, dim >::operator= (DistTree< T, dim > && other)
Definition at line 491 of file distTree.h.
repartitioned()
template<typename T, unsigned int dim> DistTree ot::DistTree< T, dim >::repartitioned (const double sfc_tol) &&
Usage: dtree = std::move(dtree).repartitioned(sfc_tol);.
Referenced by ot::DistTree< C, dim >::~DistTree().
replaceStratum()
template<typename T, unsigned int dim> void ot::DistTree< T, dim >::replaceStratum (int atStratum, std::vector< TreeNode< T, dim >> & treePart) protected
Definition at line 415 of file distTree.h.
Referenced by ot::DistTree< C, dim >::get_m_treePartBack().
Member Data Documentation
m_alive
template<typename T, unsigned int dim> LazyPerishable<LivePtrOwner> ot::DistTree< T, dim >::m_alive mutable protected
Definition at line 305 of file distTree.h.
Referenced by ot::DistTree< C, dim >::lazy_live_ptr().
m_coalesceSiblings
template<typename T, unsigned int dim> CoalesceOption ot::DistTree< T, dim >::m_coalesceSiblings protected
Definition at line 274 of file distTree.h.
m_comm
template<typename T, unsigned int dim> MPI_Comm ot::DistTree< T, dim >::m_comm protected
Definition at line 273 of file distTree.h.
Referenced by ot::DistTree< C, dim >::getComm(), and ot::DistTree< C, dim >::operator=().
m_domainDecider
template<typename T, unsigned int dim> ::ibm::DomainDecider ot::DistTree< T, dim >::m_domainDecider protected
Definition at line 275 of file distTree.h.
Referenced by ot::DistTree< C, dim >::conversionDomainDeciderTN_asCell(), ot::DistTree< C, dim >::conversionDomainDeciderTN_asPoint(), and ot::DistTree< C, dim >::operator=().
m_domainDeciderTN_asCell
template<typename T, unsigned int dim> std::function<::ibm::Partition(const TreeNode<T, dim> &treeNodeElem)> ot::DistTree< T, dim >::m_domainDeciderTN_asCell protected
Definition at line 276 of file distTree.h.
m_domainDeciderTN_asPoint
template<typename T, unsigned int dim> std::function<::ibm::Partition(const TreeNode<T, dim> &treeNodeElem)> ot::DistTree< T, dim >::m_domainDeciderTN_asPoint protected
Definition at line 277 of file distTree.h.
m_filteredTreePartSz
template<typename T, unsigned int dim> std::vector<size_t> ot::DistTree< T, dim >::m_filteredTreePartSz protected
Definition at line 287 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
m_gridStrata
template<typename T, unsigned int dim> std::vector<std::vector<TreeNode<T, dim> > > ot::DistTree< T, dim >::m_gridStrata protected
Definition at line 283 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
m_hasBeenFiltered
template<typename T, unsigned int dim> bool ot::DistTree< T, dim >::m_hasBeenFiltered protected
Definition at line 279 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
m_numStrata
template<typename T, unsigned int dim> int ot::DistTree< T, dim >::m_numStrata protected
Definition at line 289 of file distTree.h.
Referenced by ot::DistTree< C, dim >::getNumStrata(), and ot::DistTree< C, dim >::operator=().
m_originalTreePartSz
template<typename T, unsigned int dim> std::vector<size_t> ot::DistTree< T, dim >::m_originalTreePartSz protected
Definition at line 286 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
m_tpBackStrata
template<typename T, unsigned int dim> std::vector<TreeNode<T, dim> > ot::DistTree< T, dim >::m_tpBackStrata protected
Definition at line 285 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
m_tpFrontStrata
template<typename T, unsigned int dim> std::vector<TreeNode<T, dim> > ot::DistTree< T, dim >::m_tpFrontStrata protected
Definition at line 284 of file distTree.h.
Referenced by ot::DistTree< C, dim >::operator=().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/distTree.h