DENDRO: ot::MatvecBaseIn< dim, NodeT, p2c > Class Template Reference
ot::MatvecBaseIn< dim, NodeT, p2c > Class Template Reference
#include <sfcTreeLoop_matvec_io.h>
Classes
struct AccessSubtree
Public Types
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn >
Public Types inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
using C = unsigned int
using FrameT = Frame< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
using SubtreeInfoT = SubtreeInfo< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
Public Member Functions
bool isLeaf () const
bool isLeafOrLower () const
MatvecBaseIn ()=delete
MatvecBaseIn (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > *allNodeCoords, const NodeT *inputNodeVals, const TreeNode< unsigned int, dim > *treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > &firstElement, const TreeNode< unsigned int, dim > &lastElement)
AccessSubtree subtreeInfo ()
Public Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
MatvecBaseIn< dim, NodeT, p2c > & asConcreteType ()
const TreeNode< C, dim > & getCurrentSubtree () const
SubtreeInfoT getSubtreeInfo ()
bool isFinished () const
bool isPre () const
bool next ()
void reset ()
bool step ()
Static Public Attributes
static constexpr unsigned int NumChildren = 1u << dim
Static Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
static constexpr unsigned int NumChildren
Protected Member Functions
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
void fillAccessNodeCoordsFlat ()
void fillLeafNodeBdry ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Protected Member Functions inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
void bottomUpNodes (FrameT &parentFrame, ExtantCellFlagT extantChildren)
void child2Parent (FrameT &parentFrame, FrameT &childFrame)
const FrameT & getCurrentFrame () const
FrameT & getCurrentFrame ()
SFC_State< dim > getCurrentRotation () const
const FrameT & getRootFrame () const
FrameT & getRootFrame ()
void parent2Child (FrameT &parentFrame, FrameT &childFrame)
SFC_TreeLoop (const TreeNode< C, dim > *sortedTreePart, size_t localTreeSz, unsigned int max_depth)
SFC_TreeLoop ()=delete
void topDownNodes (FrameT &parentFrame, ExtantCellFlagT *extantChildren)
Static Protected Member Functions
static MatvecBaseSummary< dim > generate_node_summary (const TreeNode< unsigned int, dim > *begin, const TreeNode< unsigned int, dim > *end)
static unsigned int get_max_depth (const TreeNode< unsigned int, dim > *begin, size_t numNodes)
static const std::vector< bool > & getNodeNonhangingIn (const FrameT &frame)
static std::vector< bool > & getNodeNonhangingIn (FrameT &frame)
Protected Attributes
std::vector< double > m_accessNodeCoordsFlat
unsigned int m_eleOrder
InterpMatrices< dim, NodeT > m_interp_matrices
std::vector< bool > m_leafNodeBdry
unsigned int m_ndofs
std::vector< bool > m_parentNodeBdry
std::vector< NodeT > m_parentNodeVals
bool m_visitEmpty
Protected Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
FrameInputs< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool > >::DataStoreT m_rootInputData
FrameOutputs< dim, Outputs<> >::DataStoreT m_rootOutputData
MatvecBaseSummary< dim > m_rootSummary
std::array< RankI,(1u<< dim)+1 > m_rootTreeSplitters
std::vector< FrameT > m_stack
const TreeNode< C, dim > * m_treePartPtr
Friends
void fillLeafNodeBdry (const FrameT &, unsigned int, const std::vector< bool > &, std::vector< bool > &)
Additional Inherited Members
Public Attributes inherited from ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >
friend SubtreeInfoT
Detailed Description
template<unsigned int dim, typename NodeT, bool p2c = true>
class ot::MatvecBaseIn< dim, NodeT, p2c >
Definition at line 277 of file sfcTreeLoop_matvec_io.h.
Member Typedef Documentation
FrameT
template<unsigned int dim, typename NodeT , bool p2c = true> using ot::MatvecBaseIn< dim, NodeT, p2c >::FrameT = Frame<dim, Inputs<TreeNode<unsigned int, dim>, NodeT, bool>, Outputs<>, MatvecBaseSummary<dim>, MatvecBaseIn>
Definition at line 291 of file sfcTreeLoop_matvec_io.h.
Constructor & Destructor Documentation
MatvecBaseIn() [1/2]
template<unsigned int dim, typename NodeT , bool p2c = true> ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn () delete
MatvecBaseIn() [2/2]
template<unsigned int dim, typename NodeT , bool p2c> ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn (size_t numNodes, unsigned int ndofs, unsigned int eleOrder, bool visitEmpty, unsigned int padlevel, const TreeNode< unsigned int, dim > * allNodeCoords, const NodeT * inputNodeVals, const TreeNode< unsigned int, dim > * treePartPtr, size_t treePartSz, const TreeNode< unsigned int, dim > & firstElement, const TreeNode< unsigned int, dim > & lastElement)
Definition at line 750 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::generate_node_summary(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::getRootFrame(), intPow(), ot::MatvecBaseIn< dim, NodeT, p2c >::m_eleOrder, ot::MatvecBaseIn< dim, NodeT, p2c >::m_parentNodeBdry, ot::MatvecBaseIn< dim, NodeT, p2c >::m_parentNodeVals, and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Member Function Documentation
bottomUpNodes()
template<unsigned int dim, typename NodeT , bool p2c = true> void ot::MatvecBaseIn< dim, NodeT, p2c >::bottomUpNodes (FrameT & parentFrame, ExtantCellFlagT extantChildren) inline protected
Definition at line 419 of file sfcTreeLoop_matvec_io.h.
child2Parent()
template<unsigned int dim, typename NodeT , bool p2c = true> void ot::MatvecBaseIn< dim, NodeT, p2c >::child2Parent (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 421 of file sfcTreeLoop_matvec_io.h.
fillAccessNodeCoordsFlat()
template<unsigned int dim, typename NodeT , bool p2c> void ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat () protected
Definition at line 1975 of file sfcTreeLoop_matvec_io.h.
References ot::fillAccessNodeCoordsFlat(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_accessNodeCoordsFlat, and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodeCoords().
fillLeafNodeBdry()
template<unsigned int dim, typename NodeT , bool p2c = true> void ot::MatvecBaseIn< dim, NodeT, p2c >::fillLeafNodeBdry () inline protected
Definition at line 449 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::m_eleOrder, ot::MatvecBaseCoords< dim >::m_leafNodeBdry, and ot::MatvecBaseCoords< dim >::m_parentNodeBdry.
generate_node_summary()
template<unsigned int dim, typename NodeT , bool p2c = true> static MatvecBaseSummary<dim> ot::MatvecBaseIn< dim, NodeT, p2c >::generate_node_summary (const TreeNode< unsigned int, dim > * begin, const TreeNode< unsigned int, dim > * end) inline static protected
Definition at line 423 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBase< dim, NodeT >::generate_node_summary().
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn().
get_max_depth()
template<unsigned int dim, typename NodeT , bool p2c = true> static unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::get_max_depth (const TreeNode< unsigned int, dim > * begin, size_t numNodes) inline static protected
Definition at line 441 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), and ot::MatvecBase< dim, NodeT >::get_max_depth().
getNodeNonhangingIn() [1/2]
template<unsigned int dim, typename NodeT , bool p2c = true> static const std::vector<bool>& ot::MatvecBaseIn< dim, NodeT, p2c >::getNodeNonhangingIn (const FrameT & frame) inline static protected
Definition at line 432 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeNonhangingIn().
getNodeNonhangingIn() [2/2]
template<unsigned int dim, typename NodeT , bool p2c = true> static std::vector<bool>& ot::MatvecBaseIn< dim, NodeT, p2c >::getNodeNonhangingIn (FrameT & frame) inline static protected
Definition at line 436 of file sfcTreeLoop_matvec_io.h.
isLeaf()
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::isLeaf () const inline
Definition at line 406 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::isLeafOrLower () const inline
Definition at line 411 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentFrame(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseCoords< dim > >::getCurrentSubtree(), ot::TreeNode< T, dim >::getLevel(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, and ot::MatvecBaseCoords< dim >::topDownNodes().
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isLeafOrLower().
parent2Child()
template<unsigned int dim, typename NodeT , bool p2c = true> void ot::MatvecBaseIn< dim, NodeT, p2c >::parent2Child (FrameT & parentFrame, FrameT & childFrame) inline protected
Definition at line 420 of file sfcTreeLoop_matvec_io.h.
subtreeInfo()
template<unsigned int dim, typename NodeT , bool p2c = true> AccessSubtree ot::MatvecBaseIn< dim, NodeT, p2c >::subtreeInfo () inline
Definition at line 396 of file sfcTreeLoop_matvec_io.h.
topDownNodes()
template<unsigned int dim, typename NodeT , bool p2c> void ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes (FrameT & parentFrame, ExtantCellFlagT * extantChildren) protected
Copied from sfcTreeLoop.h:
topDownNodes() is responsible to
Resize the child input buffers (SFC order) in the parent frame;
Duplicate elements of the parent input buffers to incident child input buffers (SFC order);
2.1. Initialize a summary object for each child (SFC order).
Indicate to SFC_TreeLoop which children to traverse, by accumulating into the extantChildren bit array (Morton order).
Restrictions
MAY NOT resize or write to parent input buffers.
MAY NOT resize or write to variably sized output buffers.
Utilities are provided to identify and iterate over incident children.
std::vector<TreeNode<unsigned int, dim>> &childNodeCoords = parentFrame.template getChildInput<0>(child_sfc); childNodeCoords.clear(); Element<unsigned int, dim>(childSubtreesSFC[child_sfc]).template appendNodes<TreeNode<unsigned int, dim>>(m_eleOrder, childNodeCoords);
ExtantCellFlagT iterateChildren = (m_visitEmpty ? segmentChildren : *extantChildren);
assert(parentFrame.template getChildInput<0>(child_sfc)[nodeRank] == myNodes[nIdx]);
*extantChildren = segmentChildren;
Definition at line 1146 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_State< dim >::child_num(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::childSummaries, ot::TNPoint< T, dim >::get_lexNodeRank(), ot::TreeNode< T, dim >::getChildMorton(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentRotation(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, bool >, Outputs< NodeT, char >, MatvecBaseSummary< dim >, MatvecBaseOut< dim, NodeT, UseAccumulation > >::getCurrentSubtree(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getExtantTreeChildrenMorton(), ot::TreeNode< T, dim >::getLevel(), intPow(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_interp_matrices, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeBdry, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_parentNodeVals, ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_visitEmpty, ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle, ot::nchild(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::NumChildren.
Friends And Related Function Documentation
fillLeafNodeBdry
template<unsigned int dim, typename NodeT , bool p2c = true> void fillLeafNodeBdry (const FrameT & , unsigned int, const std::vector< bool > & , std::vector< bool > &) friend
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getLeafNodeBdry().
Member Data Documentation
m_accessNodeCoordsFlat
template<unsigned int dim, typename NodeT , bool p2c = true> std::vector<double> ot::MatvecBaseIn< dim, NodeT, p2c >::m_accessNodeCoordsFlat protected
Definition at line 461 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodeCoords().
m_eleOrder
template<unsigned int dim, typename NodeT , bool p2c = true> unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::m_eleOrder protected
Definition at line 452 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getEleOrder(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodesPerElement(), and ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn().
m_interp_matrices
template<unsigned int dim, typename NodeT , bool p2c = true> InterpMatrices<dim, NodeT> ot::MatvecBaseIn< dim, NodeT, p2c >::m_interp_matrices protected
Definition at line 463 of file sfcTreeLoop_matvec_io.h.
m_leafNodeBdry
template<unsigned int dim, typename NodeT , bool p2c = true> std::vector<bool> ot::MatvecBaseIn< dim, NodeT, p2c >::m_leafNodeBdry protected
Definition at line 458 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getLeafNodeBdry().
m_ndofs
template<unsigned int dim, typename NodeT , bool p2c = true> unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::m_ndofs protected
Definition at line 451 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNdofs(), and ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::overwriteNodeValsIn().
m_parentNodeBdry
template<unsigned int dim, typename NodeT , bool p2c = true> std::vector<bool> ot::MatvecBaseIn< dim, NodeT, p2c >::m_parentNodeBdry protected
Definition at line 459 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn().
m_parentNodeVals
template<unsigned int dim, typename NodeT , bool p2c = true> std::vector<NodeT> ot::MatvecBaseIn< dim, NodeT, p2c >::m_parentNodeVals protected
Definition at line 457 of file sfcTreeLoop_matvec_io.h.
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn().
m_visitEmpty
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::m_visitEmpty protected
Definition at line 454 of file sfcTreeLoop_matvec_io.h.
NumChildren
template<unsigned int dim, typename NodeT , bool p2c = true> constexpr unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::NumChildren = 1u << dim static
Definition at line 293 of file sfcTreeLoop_matvec_io.h.
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h