DENDRO: par::KwayBlocks Class Reference
par::KwayBlocks Class Reference
#include <comm_hierarchy.h>
Public Types
using Blk = int
using Task = int
Public Member Functions
Task blk_id_to_task (Blk blk, int blk_id) const
Task block_tasks (Blk blk) const
Task block_to_task (Blk blk) const
int comm_size () const
KwayBlocks ()=delete
KwayBlocks (int comm_size, int nblocks)
Blk nblocks () const
Blk task_to_block (Task task) const
int task_to_block_id (Task task) const
Blk task_to_next_block (Task task) const
Detailed Description
Definition at line 12 of file comm_hierarchy.h.
Member Typedef Documentation
Blk
using par::KwayBlocks::Blk = int
Definition at line 20 of file comm_hierarchy.h.
Task
using par::KwayBlocks::Task = int
Definition at line 19 of file comm_hierarchy.h.
Constructor & Destructor Documentation
KwayBlocks() [1/2]
par::KwayBlocks::KwayBlocks () delete
KwayBlocks() [2/2]
par::KwayBlocks::KwayBlocks (int comm_size, int nblocks) inline
Definition at line 23 of file comm_hierarchy.h.
Member Function Documentation
blk_id_to_task()
Task par::KwayBlocks::blk_id_to_task (Blk blk, int blk_id) const inline
Definition at line 43 of file comm_hierarchy.h.
References block_to_task().
block_tasks()
Task par::KwayBlocks::block_tasks (Blk blk) const inline
Definition at line 38 of file comm_hierarchy.h.
References block_to_task().
block_to_task()
Task par::KwayBlocks::block_to_task (Blk blk) const inline
Definition at line 33 of file comm_hierarchy.h.
References comm_size(), and nblocks().
Referenced by blk_id_to_task(), block_tasks(), task_to_block(), and task_to_block_id().
comm_size()
int par::KwayBlocks::comm_size () const inline
Definition at line 27 of file comm_hierarchy.h.
Referenced by block_to_task(), task_to_block(), and task_to_next_block().
nblocks()
Blk par::KwayBlocks::nblocks () const inline
Definition at line 30 of file comm_hierarchy.h.
Referenced by block_to_task(), task_to_block(), and task_to_next_block().
task_to_block()
Blk par::KwayBlocks::task_to_block (Task task) const inline
Definition at line 48 of file comm_hierarchy.h.
References block_to_task(), comm_size(), and nblocks().
Referenced by task_to_block_id().
task_to_block_id()
int par::KwayBlocks::task_to_block_id (Task task) const inline
Definition at line 55 of file comm_hierarchy.h.
References block_to_task(), and task_to_block().
task_to_next_block()
Blk par::KwayBlocks::task_to_next_block (Task task) const inline
Definition at line 60 of file comm_hierarchy.h.
References comm_size(), and nblocks().
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/comm_hierarchy.h