DENDRO: periodic::PCoord< T, dim >::CoordTransfer Class Reference
periodic::PCoord< T, dim >::CoordTransfer Class Reference
#include <pcoord.h>
Public Member Functions
CoordTransfer (const CoordTransfer &)=default
CoordTransfer (CoordTransfer &&)=default
operator T () const
CoordTransfer & operator= (const CoordTransfer &)=default
CoordTransfer & operator= (CoordTransfer &&)=default
Detailed Description
template<typename T, int dim>
class periodic::PCoord< T, dim >::CoordTransfer
Definition at line 50 of file pcoord.h.
Constructor & Destructor Documentation
CoordTransfer() [1/2]
template<typename T, int dim> periodic::PCoord< T, dim >::CoordTransfer::CoordTransfer (const CoordTransfer &) default
CoordTransfer() [2/2]
template<typename T, int dim> periodic::PCoord< T, dim >::CoordTransfer::CoordTransfer (CoordTransfer &&) default
Member Function Documentation
operator T()
template<typename T, int dim> periodic::PCoord< T, dim >::CoordTransfer::operator T () const inline
Definition at line 61 of file pcoord.h.
References periodic::PCoord< T, dim >::coord().
operator=() [1/2]
template<typename T, int dim> CoordTransfer& periodic::PCoord< T, dim >::CoordTransfer::operator= (const CoordTransfer &) default
Referenced by periodic::PCoord< unsigned int, dim >::operator+=(), and periodic::PCoord< unsigned int, dim >::operator-=().
operator=() [2/2]
template<typename T, int dim> CoordTransfer& periodic::PCoord< T, dim >::CoordTransfer::operator= (CoordTransfer &&) default
The documentation for this class was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/pcoord.h