DENDRO: /home/gaurav/Documents/Dendro-KT/include/mathUtils.h File Reference
mathUtils.h File Reference
#include <iostream>
#include <cmath>
#include <math.h>
#include <array>
#include "parUtils.h"
#include "mathUtils.tcc"
Functions
template<typename T >
T add (const T *v1, const T *v2, const unsigned int n, T *out)
: add two vectors.
template<typename T >
T dot (const T *v1, const T *v2, const unsigned int n)
: performs the dot product of any two given vectors
template<typename T >
T dot (const T *v1, const T *v2, const unsigned int n, MPI_Comm comm)
: performs the dot product of any two given distributed vectors Assumption : v1 and v2 are partitioned in the sameway.
template<typename T , unsigned int L>
void incrementBaseB (std::array< T, L > &digits, T B, unsigned int lstart=0)
Increments an array of numbers as if they are digits in a base B number. The reason for writing this is to traverse multidimensional lattices without using nested for-loops; for example, when the dimension is a template parameter.
template<typename T >
constexpr T intCombination (T n, T k, T p=1, T q=1)
Compile-time computation of combination "n choose k".
template<typename T >
constexpr T intFactorial (T f, T A=1)
Compile-time computation of factorial "f!".
template<typename T >
constexpr T intPow (T b, unsigned p, T A=1)
Compile-time computation of integer (A*pow(b,p)).
template<typename T >
void mul (const T alpha, const T *v, const unsigned int n, T *out)
: Scaler multiplication of a vector.
template<typename T >
T normL2 (T *vec1, T *vec2, unsigned int n, MPI_Comm comm)
Contains useful math helper routines.
template<typename T >
T normL2 (T *vec, unsigned int n, MPI_Comm comm)
computes the l2 norm of a vector.
template<typename T >
T normL2 (T *vec1, T *vec2, unsigned int n)
computes the l2 norm between two vectors.
template<typename T >
T normL2 (T *vec, unsigned int n)
computes the l2 norm of a vector.
template<typename T >
T normLInfty (T *vec1, T *vec2, unsigned int n, MPI_Comm comm)
computes the l2 norm between two vectors.
template<typename T >
T normLInfty (T *vec1, T *vec2, unsigned int n)
computes the l2 norm between two vectors.
template<typename T >
T normLInfty (T *vec, unsigned int n)
computes the l_inf norm of a vector.
template<typename T >
T normLInfty (T *vec, unsigned int n, MPI_Comm comm)
computes the l_inf norm of a vector.
template<typename T >
T subt (const T *v1, const T *v2, const unsigned int n, T *out)
: substract two vectors.
template<typename T >
T vecMax (T *vec, unsigned int n)
computes the min of a vector.
template<typename T >
T vecMax (T *vec, unsigned int n, MPI_Comm comm)
computes the min of a vector.
template<typename T >
T vecMin (T *vec, unsigned int n)
computes the min of a vector.
template<typename T >
T vecMin (T *vec, unsigned int n, MPI_Comm comm)
computes the min of a vector.
Function Documentation
add()
template<typename T > T add (const T * v1, const T * v2, const unsigned int n, T * out)
: add two vectors.
Parameters
[in] v1 input vector 1
[in] v2 input vector 2
[in] n size of the vector (dof of vector)
[out] out out=v1+v2
dot() [1/2]
template<typename T > T dot (const T * v1, const T * v2, const unsigned int n)
: performs the dot product of any two given vectors
Parameters
[in] v1 input vector 1
[in] v2 input vector 2
[in] n size of the vector (dof of vector)
Returns
v1^tv2
dot() [2/2]
template<typename T > T dot (const T * v1, const T * v2, const unsigned int n, MPI_Comm comm)
: performs the dot product of any two given distributed vectors Assumption : v1 and v2 are partitioned in the sameway.
Parameters
[in] v1 input vector 1
[in] v2 input vector 2
[in] n size of the vector (dof of vector)
Returns
v1^tv2
incrementBaseB()
template<typename T , unsigned int L> void incrementBaseB (std::array< T, L > & digits, T B, unsigned int lstart = 0)
Increments an array of numbers as if they are digits in a base B number. The reason for writing this is to traverse multidimensional lattices without using nested for-loops; for example, when the dimension is a template parameter.
Author
Masado Ishii
intCombination()
template<typename T > constexpr T intCombination (T n, T k, T p = 1, T q = 1)
Compile-time computation of combination "n choose k".
Note
Computes numerator and denominator separately; these could get large, so n and k should be small or T should be large.
Author
Masado Ishii
intFactorial()
template<typename T > constexpr T intFactorial (T f, T A = 1)
Compile-time computation of factorial "f!".
Author
Masado Ishii
intPow()
template<typename T > constexpr T intPow (T b, unsigned p, T A = 1)
Compile-time computation of integer (A*pow(b,p)).
Author
Masado Ishii
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::fillAccessNodeCoordsFlat(), ot::function2Octree(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNodesPerElement(), ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodesPerElement(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodesPerElement(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodesPerElement(), ot::MatvecBase< dim, NodeT >::MatvecBase(), ot::MatvecBaseCoords< dim >::MatvecBaseCoords(), ot::MatvecBaseIn< dim, NodeT, p2c >::MatvecBaseIn(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::MatvecBaseOut(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
mul()
template<typename T > void mul (const T alpha, const T * v, const unsigned int n, T * out)
: Scaler multiplication of a vector.
Parameters
[in] alpha scalar value
[in] v input vector.
[in] n size of the vector (dof of vector)
[in] comm : MPI communicator.
normL2() [1/4]
template<typename T > T normL2 (T * vec1, T * vec2, unsigned int n, MPI_Comm comm)
Contains useful math helper routines.
Author
Milinda Fernando School of Computing, University of Utah computes the l2 norm between two vectors.
Parameters
[in] vec1 input vector 1
[in] vec2 input vector 2
[in] dimension of the vector.
[in] comm communicator
Returns
l2 norm between two vectors.
normL2() [2/4]
template<typename T > T normL2 (T * vec, unsigned int n, MPI_Comm comm)
computes the l2 norm of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
[in] comm communicator
Returns
l2 norm of vec.
normL2() [3/4]
template<typename T > T normL2 (T * vec1, T * vec2, unsigned int n)
computes the l2 norm between two vectors.
Parameters
[in] vec1 input vector 1
[in] vec2 input vector 2
[in] dimension of the vector.
Returns
l2 norm between two vectors.
normL2() [4/4]
template<typename T > T normL2 (T * vec, unsigned int n)
computes the l2 norm of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
l2 norm of vec.
normLInfty() [1/4]
template<typename T > T normLInfty (T * vec1, T * vec2, unsigned int n, MPI_Comm comm)
computes the l2 norm between two vectors.
Parameters
[in] vec1 input vector 1
[in] vec2 input vector 2
[in] dimension of the vector.
[in] comm communicator
Returns
l1 norm between two vectors.
Referenced by ot::function2Octree().
normLInfty() [2/4]
template<typename T > T normLInfty (T * vec1, T * vec2, unsigned int n)
computes the l2 norm between two vectors.
Parameters
[in] vec1 input vector 1
[in] vec2 input vector 2
[in] dimension of the vector.
Returns
l1 norm between two vectors.
normLInfty() [3/4]
template<typename T > T normLInfty (T * vec, unsigned int n)
computes the l_inf norm of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
l2 norm of vec.
normLInfty() [4/4]
template<typename T > T normLInfty (T * vec, unsigned int n, MPI_Comm comm)
computes the l_inf norm of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
[in] comm communicator
Returns
l2 norm of vec.
subt()
template<typename T > T subt (const T * v1, const T * v2, const unsigned int n, T * out)
: substract two vectors.
Parameters
[in] v1 input vector 1
[in] v2 input vector 2
[in] n size of the vector (dof of vector)
[out] out out=v1+v2
vecMax() [1/2]
template<typename T > T vecMax (T * vec, unsigned int n)
computes the min of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
max of vec.
vecMax() [2/2]
template<typename T > T vecMax (T * vec, unsigned int n, MPI_Comm comm)
computes the min of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
max of vec.
vecMin() [1/2]
template<typename T > T vecMin (T * vec, unsigned int n)
computes the min of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
min of vec.
vecMin() [2/2]
template<typename T > T vecMin (T * vec, unsigned int n, MPI_Comm comm)
computes the min of a vector.
Parameters
[in] vec input vector
[in] dimension of the vector.
Returns
min of vec.