DENDRO: par Namespace Reference
par Namespace Reference
Collection of Generic Parallel Functions: Sorting, Partitioning, Searching,...
Classes
class KwayBlocks
class KwayComms
struct MinMeanMax
class Mpi_datatype
An abstract class used for communicating messages using user-defined datatypes. The user must implement the static member function "value()" that returns the MPI_Datatype corresponding to this user-defined datatype.
class Mpi_datatype< bool >
A template specialization of the abstract class Mpi_datatype. This can be used for communicating messages of type "bool".
class Mpi_datatype< ot::OctreeAdler32 >
class Mpi_datatype< ot::TNPoint< T, dim > >
A template specialization of the abstract class "Mpi_datatype" for communicating messages of type "ot::TNPoint".
class Mpi_datatype< ot::TreeNode< T, dim > >
A template specialization of the abstract class "Mpi_datatype" for communicating messages of type "ot::TreeNode".
class Mpi_datatype< std::complex< T > >
struct NbxSynch
struct P2PMeta
struct P2PPartners
struct P2PRequest
struct P2PScalar
struct P2PVector
struct SendRecvSchedule
Functions
template<typename T >
void bitonicSort (std::vector< T > &in, MPI_Comm comm)
An implementation of parallel bitonic sort that does not expect the number of processors to be a power of 2. In fact, the number of processors can even be odd. Moreover, we do not even expect the length of the vector (neither locally nor globally) to be a power of 2 or even. Moreover, each processor can call this with a different number of elements. However, we do expect that 'in' atleast has 1 element on each processor. This recursively calls the function bitonicSort_binary, followed by a special parallel merge.
template<typename T >
void bitonicSort_binary (std::vector< T > &in, MPI_Comm comm)
An implementation of parallel bitonic sort that expects the number of processors to be a power of 2. However, unlike most implementations, we do not expect the length of the vector (neither locally nor globally) to be a power of 2 or even. Moreover, each processor can call this with a different number of elements. However, we do expect that 'in' atleast has 1 element on each processor.
template<typename T >
int concatenate (std::vector< T > &listA, std::vector< T > &listB, MPI_Comm comm)
A parallel concatenation function. listB is appended (globally) to listA and the result is stored in listA. An useful application of this function is when listA and listB are individually sorted (globally) and the smallest element in listB is greater than the largest element in listA and we want to create a merged list that is sorted.
template<class TN >
void dbg_printTNList (const TN *tnList, unsigned int listSz, unsigned int lev, MPI_Comm comm)
Print a distributed list of treeNodes.
template<typename T >
unsigned int defaultWeight (const T *a)
template<typename WeightT >
double loadImbalance (WeightT localWeight, MPI_Comm comm)
template<typename T >
int maxLowerBound (const std::vector< T > &keys, const std::vector< T > &searchList, std::vector< T > &results, MPI_Comm comm)
A parallel search function.
template<typename T >
void MergeLists (std::vector< T > &listA, std::vector< T > &listB, int KEEP_WHAT)
Merges lists A, and B, retaining either the low or the High in list A.
template<typename T >
void MergeSplit (std::vector< T > &local_list, int which_keys, int partner, MPI_Comm comm)
The main operation in the parallel bitonic sort algorithm. This implements the compare-split operation.
template<typename T >
int Mpi_Allgather (const T *sendbuf, T *recvbuf, int count, MPI_Comm comm)
template<typename T >
int Mpi_Allgatherv (const T *sendbuf, int sendcount, T *recvbuf, int *recvcounts, int *displs, MPI_Comm comm)
template<typename T >
int Mpi_Allreduce (const T *sendbuf, T *recvbuf, int count, MPI_Op op, MPI_Comm comm)
template<typename T >
MinMeanMax< T > Mpi_AllreduceMinMeanMax (T localData, MPI_Comm comm)
template<typename T >
int Mpi_Alltoall (const T *sendbuf, T *recvbuf, int count, MPI_Comm comm)
template<typename T >
int Mpi_Alltoallv_dense (const T *sendbuf, int *sendcnts, int *sdispls, T *recvbuf, int *recvcnts, int *rdispls, MPI_Comm comm)
template<typename T >
int Mpi_Alltoallv_Kway (const T *sbuff_, int *s_cnt_, int *sdisp_, T *rbuff_, int *r_cnt_, int *rdisp_, MPI_Comm c)
template<typename T >
int Mpi_Alltoallv_sparse (const T *sendbuf, int *sendcnts, int *sdispls, T *recvbuf, int *recvcnts, int *rdispls, MPI_Comm comm)
template<typename T >
T mpi_and (const T t_, MPI_Comm comm)
template<typename T >
int Mpi_Bcast (T *buffer, int count, int root, MPI_Comm comm)
int mpi_comm_rank (MPI_Comm comm)
int mpi_comm_size (MPI_Comm comm)
template<typename T >
int Mpi_Exscan (const T *sendbuf, T *recvbuf, int count, MPI_Op op, MPI_Comm comm)
template<typename T >
int Mpi_Gather (const T *sendBuffer, T *recvBuffer, int count, int root, MPI_Comm comm)
template<typename T >
int Mpi_Iallgather (const T *sendbuf, T *recvbuf, int count, MPI_Comm comm, MPI_Request *request)
template<typename T >
int Mpi_Imrecv (T *buf, int count, MPI_Message *message, MPI_Request *request)
template<typename T >
int Mpi_Irecv (T *buf, int count, int source, int tag, MPI_Comm comm, MPI_Request *request)
template<typename T >
int Mpi_Isend (const T *buf, int count, int dest, int tag, MPI_Comm comm, MPI_Request *request)
template<typename T >
int Mpi_Issend (const T *buf, int count, int dest, int tag, MPI_Comm comm, MPI_Request *request)
template<typename T >
T mpi_max (const T t, MPI_Comm comm)
template<typename T >
T mpi_min (const T t, MPI_Comm comm)
template<typename T >
int Mpi_Mrecv (T *buf, int count, MPI_Message *message, MPI_Status *status)
template<typename T >
int Mpi_NBX (const int *destinations, const int ndest, const T *sendbuf, const int count, std::vector< int > &sources, std::vector< T > &recvbuf, MPI_Comm comm, bool sort_sources=true)
Nonblocking Consensus due to (Hoefler et al., 2010).
template<typename T >
int Mpi_NBX (const int *destinations, const int ndest, const T *sendbuf, const int count, std::vector< int > &sources, std::vector< T > &recvbuf, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources=true)
int Mpi_NBX_neighbors (const int *destinations, const int ndest, std::vector< int > &sources, MPI_Comm comm, bool sort_sources=true)
Nonblocking Consensus due to (Hoefler et al., 2010). Allows sparse alltoall exchange without calling any alltoall. A barrier is automatically called for correctness. For better control over when the barrier must complete, supply MPI_Request(s) to the appropriate overloads.
int Mpi_NBX_neighbors (const int *destinations, const int ndest, std::vector< int > &sources, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources=true)
Nonblocking Consensus due to (Hoefler et al., 2010). Allows sparse alltoall exchange without calling any alltoall. However, a non-blocking synch is needed before sending again, due to implementation of nbx with MPI_ANY_SOURCE. Must call MPI_Waitall() with synch_p2p[] before sending to destinations. Must call MPI_Wait() with synch_global before sending to others. After synch_global completes, synch_p2p[] is not needed, so synch_p2p=nullptr is ok if no middle phase for destinations only.
int Mpi_NBX_sizes (const int *destinations, const int *send_sizes, const int ndest, std::vector< int > &sources, std::vector< int > &recv_sizes, MPI_Comm comm, bool sort_sources=true)
Nonblocking Consensus due to (Hoefler et al., 2010).
int Mpi_NBX_sizes (const int *destinations, const int *send_sizes, const int ndest, std::vector< int > &sources, std::vector< int > &recv_sizes, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources=true)
std::pair< int, int > mpi_next_if (bool included, MPI_Comm comm)
Get ranks of nonempty predecessor and successor without comm split.
template<typename T >
T mpi_or (const T t_, MPI_Comm comm)
template<typename T >
int Mpi_Recv (T *buf, int count, int source, int tag, MPI_Comm comm, MPI_Status *status)
template<typename T >
int Mpi_Reduce (const T *sendbuf, T *recvbuf, int count, MPI_Op op, int root, MPI_Comm comm)
template<typename T >
MinMeanMax< T > Mpi_ReduceMinMeanMax (T localData, MPI_Comm comm)
template<typename T >
int Mpi_Scan (const T *sendbuf, T *recvbuf, int count, MPI_Op op, MPI_Comm comm)
template<typename T , typename S >
int Mpi_Sendrecv (const T *sendBuf, int sendCount, int dest, int sendTag, S *recvBuf, int recvCount, int source, int recvTag, MPI_Comm comm, MPI_Status *status)
template<typename T >
T mpi_sum (const T t, MPI_Comm comm)
template<typename T >
void Par_bitonic_merge_incr (std::vector< T > &local_list, int proc_set_size, MPI_Comm comm)
template<typename T >
void Par_bitonic_sort_decr (std::vector< T > &local_list, int proc_set_size, MPI_Comm comm)
template<typename T >
void Par_bitonic_sort_incr (std::vector< T > &local_list, int proc_set_size, MPI_Comm comm)
template<typename T >
int partitionW (std::vector< T > &vec, unsigned int(*getWeight)(const T *), MPI_Comm comm)
A parallel weighted partitioning function. In our implementation, we do not pose any restriction on the input or the number of processors. This function can be used with an odd number of processors as well. Some processors can pass an empty vector as input. The relative ordering of the elements is preserved.
template<typename T >
int scatterValues (const std::vector< T > &in, std::vector< T > &out, DendroIntL outSz, MPI_Comm comm)
Re-distributes a STL vector, preserving the relative ordering of the elements.
template<typename T >
std::vector< T > sendAll (const std::vector< T > &sdata, const std::vector< int > &sdest, MPI_Comm comm)
template<typename T >
void shift (MPI_Comm comm, const T *srcLocal, size_t srcSizeLocal, DendroIntL srcBeginGlobal, T *dstLocal, size_t dstSizeLocal, DendroIntL dstBeginGlobal, int ndofs=1)
int splitComm2way (bool iAmEmpty, MPI_Comm *new_comm, MPI_Comm orig_comm)
Removes duplicates in parallel. If the input is not sorted, sample sort will be called within the function to sort the vector and then duplicates will be removed.
int splitComm2way (const bool *isEmptyList, MPI_Comm *new_comm, MPI_Comm orig_comm)
Splits a communication group into two depending on the values in isEmptyList. Both the groups are sorted in the ascending order of their ranks in the old comm. All processors must call this function with the same 'isEmptyList' array.
unsigned int splitCommBinary (MPI_Comm orig_comm, MPI_Comm *new_comm)
Splits a communication group into two, the first having a power of 2 number of processors and the other having the remainder. The first group is sorted in the ascending order of their ranks in the old comm and the second group is sorted in the descending order of their ranks in the old comm.
unsigned int splitCommBinaryNoFlip (MPI_Comm orig_comm, MPI_Comm *new_comm)
Splits a communication group into two, the first having a power of 2 number of processors and the other having the remainder. Both the groups are sorted in the ascending order of their ranks in the old comm.
int splitCommUsingSplittingRank (int splittingRank, MPI_Comm *new_comm, MPI_Comm orig_comm)
void waitForDebugger (MPI_Comm comm, int commRank)
Utility for using gdb + mpi, based on notes by Tom Fogal.
Variables
int DBG_nProc
int DBG_rProc
Detailed Description
Collection of Generic Parallel Functions: Sorting, Partitioning, Searching,...
Author
Masado Ishii
Date
2022-02-17
Author
Rahul Sampath
Hari Sundar
Function Documentation
bitonicSort()
template<typename T > void par::bitonicSort (std::vector< T > & in, MPI_Comm comm)
An implementation of parallel bitonic sort that does not expect the number of processors to be a power of 2. In fact, the number of processors can even be odd. Moreover, we do not even expect the length of the vector (neither locally nor globally) to be a power of 2 or even. Moreover, each processor can call this with a different number of elements. However, we do expect that 'in' atleast has 1 element on each processor. This recursively calls the function bitonicSort_binary, followed by a special parallel merge.
Parameters
in the vector to be sorted
Author
Hari Sundar
See also
bitonicSort_binary
Referenced by par::NbxSynch::disable().
bitonicSort_binary()
template<typename T > void par::bitonicSort_binary (std::vector< T > & in, MPI_Comm comm)
An implementation of parallel bitonic sort that expects the number of processors to be a power of 2. However, unlike most implementations, we do not expect the length of the vector (neither locally nor globally) to be a power of 2 or even. Moreover, each processor can call this with a different number of elements. However, we do expect that 'in' atleast has 1 element on each processor.
Parameters
in the vector to be sorted
Author
Hari Sundar
Referenced by par::NbxSynch::disable().
concatenate()
template<typename T > int par::concatenate (std::vector< T > & listA, std::vector< T > & listB, MPI_Comm comm)
A parallel concatenation function. listB is appended (globally) to listA and the result is stored in listA. An useful application of this function is when listA and listB are individually sorted (globally) and the smallest element in listB is greater than the largest element in listA and we want to create a merged list that is sorted.
Parameters
listA a distributed vector, the result is stored in listA
listB another distributed vector that is appended to listA listA must not be empty on any of the calling processors. listB can be empty on some of the calling processors. listB will be cleared within the function.
comm the communicator
Author
Rahul Sampath
Referenced by par::NbxSynch::disable().
dbg_printTNList()
template<class TN > void par::dbg_printTNList (const TN * tnList, unsigned int listSz, unsigned int lev, MPI_Comm comm)
Print a distributed list of treeNodes.
Parameters
tnList Pointer to the list of treeNodes.
listSz Size of the list.
lev Level for printing. Set to 0 to print native levels.
comm The communicator to synchronize.
Referenced by par::NbxSynch::disable().
defaultWeight()
template<typename T > unsigned int par::defaultWeight (const T * a)
Referenced by par::NbxSynch::disable().
loadImbalance()
template<typename WeightT > double par::loadImbalance (WeightT localWeight, MPI_Comm comm)
Referenced by par::NbxSynch::disable().
maxLowerBound()
template<typename T > int par::maxLowerBound (const std::vector< T > & keys, const std::vector< T > & searchList, std::vector< T > & results, MPI_Comm comm)
A parallel search function.
Author
Rahul Sampath
Parameters
keys locally sorted unique list of keys
searchList globally sorted unique list. No processor must call this function with an empty list.
results maximum lower bound in searchList for the corresponding key
comm MPI communicator
Returns
int errorcode
Referenced by par::NbxSynch::disable().
MergeLists()
template<typename T > void par::MergeLists (std::vector< T > & listA, std::vector< T > & listB, int KEEP_WHAT)
Merges lists A, and B, retaining either the low or the High in list A.
Author
Hari Sundar
Parameters
listA Input list, and where the output is stored.
listB Second input list.
KEEP_WHAT determines whether to retain the High or the low values from A and B. One of KEEP_HIGH or KEEP_LOW.
Merging the two lists when their sizes are not the same is a bit involved. The major condition that needs to be used is that all elements that are less than max(min(A), min(B)) are retained by the KEEP_LOW processor, and similarly all elements that are larger larger than min(max(A), max(B)) are retained by the KEEP_HIGH processor.
The reason for this is that, on the Keep_Low side,
max(min(A), min(B)) > min(A) > max(A-)
and similarly on the Keep_high side,
min(max(A), max(B)) < max(A) < min(A+)
which guarantees that the merged lists remain bitonic.
Referenced by par::NbxSynch::disable().
MergeSplit()
template<typename T > void par::MergeSplit (std::vector< T > & local_list, int which_keys, int partner, MPI_Comm comm)
The main operation in the parallel bitonic sort algorithm. This implements the compare-split operation.
Author
Hari Sundar
Parameters
which_keys is one of KEEP_HIGH or KEEP_LOW
partner is the processor with which to Merge and Split.
local_list the input vector
comm the communicator
Referenced by par::NbxSynch::disable().
Mpi_Allgather()
template<typename T > int par::Mpi_Allgather (const T * sendbuf, T * recvbuf, int count, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by par::NbxSynch::disable().
Mpi_Allgatherv()
template<typename T > int par::Mpi_Allgatherv (const T * sendbuf, int sendcount, T * recvbuf, int * recvcounts, int * displs, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by par::NbxSynch::disable().
Mpi_Allreduce()
template<typename T > int par::Mpi_Allreduce (const T * sendbuf, T * recvbuf, int count, MPI_Op op, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by ot::checkSiblingLeafsTogether(), ot::checksum_octree(), ot::function2Octree(), Mpi_AllreduceMinMeanMax(), mpi_and(), mpi_max(), mpi_min(), mpi_or(), mpi_sum(), and par::SendRecvSchedule::resize().
Mpi_AllreduceMinMeanMax()
template<typename T > MinMeanMax<T> par::Mpi_AllreduceMinMeanMax (T localData, MPI_Comm comm)
Definition at line 829 of file parUtils.h.
References par::MinMeanMax< T >::m_glob_max, par::MinMeanMax< T >::m_glob_mean, par::MinMeanMax< T >::m_glob_min, and Mpi_Allreduce().
Mpi_Alltoall()
template<typename T > int par::Mpi_Alltoall (const T * sendbuf, T * recvbuf, int count, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by mpi_max().
Mpi_Alltoallv_dense()
template<typename T > int par::Mpi_Alltoallv_dense (const T * sendbuf, int * sendcnts, int * sdispls, T * recvbuf, int * recvcnts, int * rdispls, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by par::NbxSynch::disable().
Mpi_Alltoallv_Kway()
template<typename T > int par::Mpi_Alltoallv_Kway (const T * sbuff_, int * s_cnt_, int * sdisp_, T * rbuff_, int * r_cnt_, int * rdisp_, MPI_Comm c)
Referenced by par::NbxSynch::disable().
Mpi_Alltoallv_sparse()
template<typename T > int par::Mpi_Alltoallv_sparse (const T * sendbuf, int * sendcnts, int * sdispls, T * recvbuf, int * recvcnts, int * rdispls, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by par::NbxSynch::disable().
mpi_and()
template<typename T > T par::mpi_and (const T t_, MPI_Comm comm)
Definition at line 358 of file parUtils.h.
References Mpi_Allreduce().
Mpi_Bcast()
template<typename T > int par::Mpi_Bcast (T * buffer, int count, int root, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by ot::function2Octree(), and par::SendRecvSchedule::resize().
mpi_comm_rank()
int par::mpi_comm_rank (MPI_Comm comm)
Referenced by par::SendRecvSchedule::resize().
mpi_comm_size()
int par::mpi_comm_size (MPI_Comm comm)
Referenced by par::SendRecvSchedule::resize().
Mpi_Exscan()
template<typename T > int par::Mpi_Exscan (const T * sendbuf, T * recvbuf, int count, MPI_Op op, MPI_Comm comm)
Referenced by par::SendRecvSchedule::resize().
Mpi_Gather()
template<typename T > int par::Mpi_Gather (const T * sendBuffer, T * recvBuffer, int count, int root, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by par::SendRecvSchedule::resize().
Mpi_Iallgather()
template<typename T > int par::Mpi_Iallgather (const T * sendbuf, T * recvbuf, int count, MPI_Comm comm, MPI_Request * request)
Author
Masado Ishii
Referenced by mpi_max().
Mpi_Imrecv()
template<typename T > int par::Mpi_Imrecv (T * buf, int count, MPI_Message * message, MPI_Request * request)
Referenced by par::SendRecvSchedule::resize().
Mpi_Irecv()
template<typename T > int par::Mpi_Irecv (T * buf, int count, int source, int tag, MPI_Comm comm, MPI_Request * request)
Referenced by par::SendRecvSchedule::resize().
Mpi_Isend()
template<typename T > int par::Mpi_Isend (const T * buf, int count, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Referenced by par::SendRecvSchedule::resize(), par::P2PScalar< ScalarT, LEN >::send(), and par::P2PVector< X >::send().
Mpi_Issend()
template<typename T > int par::Mpi_Issend (const T * buf, int count, int dest, int tag, MPI_Comm comm, MPI_Request * request)
Referenced by par::SendRecvSchedule::resize().
mpi_max()
template<typename T > T par::mpi_max (const T t, MPI_Comm comm)
Definition at line 383 of file parUtils.h.
References Mpi_Allreduce(), Mpi_Alltoall(), Mpi_Iallgather(), Mpi_NBX(), Mpi_NBX_neighbors(), and Mpi_NBX_sizes().
mpi_min()
template<typename T > T par::mpi_min (const T t, MPI_Comm comm)
Definition at line 376 of file parUtils.h.
References Mpi_Allreduce().
Mpi_Mrecv()
template<typename T > int par::Mpi_Mrecv (T * buf, int count, MPI_Message * message, MPI_Status * status)
Referenced by par::SendRecvSchedule::resize().
Mpi_NBX() [1/2]
template<typename T > int par::Mpi_NBX (const int * destinations, const int ndest, const T * sendbuf, const int count, std::vector< int > & sources, std::vector< T > & recvbuf, MPI_Comm comm, bool sort_sources = true) inline
Nonblocking Consensus due to (Hoefler et al., 2010).
Author
Masado Ishii
Referenced by par::NbxSynch::disable(), and mpi_max().
Mpi_NBX() [2/2]
template<typename T > int par::Mpi_NBX (const int * destinations, const int ndest, const T * sendbuf, const int count, std::vector< int > & sources, std::vector< T > & recvbuf, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources = true) inline
Mpi_NBX_neighbors() [1/2]
int par::Mpi_NBX_neighbors (const int * destinations, const int ndest, std::vector< int > & sources, MPI_Comm comm, bool sort_sources = true) inline
Nonblocking Consensus due to (Hoefler et al., 2010). Allows sparse alltoall exchange without calling any alltoall. A barrier is automatically called for correctness. For better control over when the barrier must complete, supply MPI_Request(s) to the appropriate overloads.
Author
Masado Ishii
Referenced by par::NbxSynch::disable(), and mpi_max().
Mpi_NBX_neighbors() [2/2]
int par::Mpi_NBX_neighbors (const int * destinations, const int ndest, std::vector< int > & sources, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources = true) inline
Nonblocking Consensus due to (Hoefler et al., 2010). Allows sparse alltoall exchange without calling any alltoall. However, a non-blocking synch is needed before sending again, due to implementation of nbx with MPI_ANY_SOURCE. Must call MPI_Waitall() with synch_p2p[] before sending to destinations. Must call MPI_Wait() with synch_global before sending to others. After synch_global completes, synch_p2p[] is not needed, so synch_p2p=nullptr is ok if no middle phase for destinations only.
Author
Masado Ishii
Mpi_NBX_sizes() [1/2]
int par::Mpi_NBX_sizes (const int * destinations, const int * send_sizes, const int ndest, std::vector< int > & sources, std::vector< int > & recv_sizes, MPI_Comm comm, bool sort_sources = true) inline
Nonblocking Consensus due to (Hoefler et al., 2010).
Author
Masado Ishii
Referenced by par::NbxSynch::disable(), and mpi_max().
Mpi_NBX_sizes() [2/2]
int par::Mpi_NBX_sizes (const int * destinations, const int * send_sizes, const int ndest, std::vector< int > & sources, std::vector< int > & recv_sizes, MPI_Comm comm, NbxSynch synch_p2p, NbxSynch synch_global, bool sort_sources = true) inline
mpi_next_if()
std::pair<int, int> par::mpi_next_if (bool included, MPI_Comm comm)
Get ranks of nonempty predecessor and successor without comm split.
mpi_next_if()
Author
Masado Ishii
Date
2022-03-23
Returns
Rank of {predecessor, successor} or MPI_PROC_NULL
Referenced by par::NbxSynch::disable().
mpi_or()
template<typename T > T par::mpi_or (const T t_, MPI_Comm comm)
Definition at line 367 of file parUtils.h.
References Mpi_Allreduce().
Mpi_Recv()
template<typename T > int par::Mpi_Recv (T * buf, int count, int source, int tag, MPI_Comm comm, MPI_Status * status)
Referenced by par::P2PVector< X >::recv(), par::P2PScalar< ScalarT, LEN >::recv_all(), and par::SendRecvSchedule::resize().
Mpi_Reduce()
template<typename T > int par::Mpi_Reduce (const T * sendbuf, T * recvbuf, int count, MPI_Op op, int root, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by Mpi_ReduceMinMeanMax(), and par::SendRecvSchedule::resize().
Mpi_ReduceMinMeanMax()
template<typename T > MinMeanMax<T> par::Mpi_ReduceMinMeanMax (T localData, MPI_Comm comm)
Definition at line 803 of file parUtils.h.
References par::MinMeanMax< T >::m_glob_max, par::MinMeanMax< T >::m_glob_mean, par::MinMeanMax< T >::m_glob_min, and Mpi_Reduce().
Mpi_Scan()
template<typename T > int par::Mpi_Scan (const T * sendbuf, T * recvbuf, int count, MPI_Op op, MPI_Comm comm)
Author
Rahul S. Sampath
Referenced by ot::quadTreeToGnuplot(), and par::SendRecvSchedule::resize().
Mpi_Sendrecv()
template<typename T , typename S > int par::Mpi_Sendrecv (const T * sendBuf, int sendCount, int dest, int sendTag, S * recvBuf, int recvCount, int source, int recvTag, MPI_Comm comm, MPI_Status * status)
Author
Rahul S. Sampath
Referenced by par::SendRecvSchedule::resize().
mpi_sum()
template<typename T > T par::mpi_sum (const T t, MPI_Comm comm)
Definition at line 350 of file parUtils.h.
References Mpi_Allreduce().
Par_bitonic_merge_incr()
template<typename T > void par::Par_bitonic_merge_incr (std::vector< T > & local_list, int proc_set_size, MPI_Comm comm)
Author
Hari Sundar
Referenced by par::NbxSynch::disable().
Par_bitonic_sort_decr()
template<typename T > void par::Par_bitonic_sort_decr (std::vector< T > & local_list, int proc_set_size, MPI_Comm comm)
Author
Hari Sundar
Referenced by par::NbxSynch::disable().
Par_bitonic_sort_incr()
template<typename T > void par::Par_bitonic_sort_incr (std::vector< T > & local_list, int proc_set_size, MPI_Comm comm)
Author
Hari Sundar
Referenced by par::NbxSynch::disable().
partitionW()
template<typename T > int par::partitionW (std::vector< T > & vec, unsigned int(*)(const T *) getWeight, MPI_Comm comm)
A parallel weighted partitioning function. In our implementation, we do not pose any restriction on the input or the number of processors. This function can be used with an odd number of processors as well. Some processors can pass an empty vector as input. The relative ordering of the elements is preserved.
Author
Hari Sundar
Rahul Sampath
Parameters
vec the input vector
getWeight function pointer to compute the weight of each element. If you pass NULL, then every element will get a weight equal to 1.
comm the communicator
Referenced by par::NbxSynch::disable().
scatterValues()
template<typename T > int par::scatterValues (const std::vector< T > & in, std::vector< T > & out, DendroIntL outSz, MPI_Comm comm)
Re-distributes a STL vector, preserving the relative ordering of the elements.
Author
Rahul S. Sampath
Parameters
in The input vector
out The output vector. Memory for this vector will be allocated within the function.
outSz The local size of the output vector on the calling processor.
comm The communicator
Returns
error flag
Referenced by par::NbxSynch::disable().
sendAll()
template<typename T > std::vector<T> par::sendAll (const std::vector< T > & sdata, const std::vector< int > & sdest, MPI_Comm comm)
Referenced by par::NbxSynch::disable().
shift()
template<typename T > void par::shift (MPI_Comm comm, const T * srcLocal, size_t srcSizeLocal, DendroIntL srcBeginGlobal, T * dstLocal, size_t dstSizeLocal, DendroIntL dstBeginGlobal, int ndofs = 1)
Referenced by ot::dbgCoordStr(), par::NbxSynch::disable(), binOp::reflectHyperplane(), and binOp::selectHyperplanes().
splitComm2way() [1/2]
int par::splitComm2way (bool iAmEmpty, MPI_Comm * new_comm, MPI_Comm orig_comm)
Removes duplicates in parallel. If the input is not sorted, sample sort will be called within the function to sort the vector and then duplicates will be removed.
Parameters
nodes the input vector.
isSorted pass 'true' if the vector is globally sorted.
comm The communicator
Author
Rahul Sampath Splits a communication group into two, one containing processors that passed a value of 'false' for the parameter 'iAmEmpty' and the another containing processors that passed a value of 'true' for the parameter. Both the groups are sorted in the ascending order of their ranks in the old comm.
Rahul Sampath
Parameters
iAmEmpty Some flag to determine which group the calling processor will be combined into.
orig_comm The comm group that needs to be split.
new_comm The new comm group.
Referenced by par::NbxSynch::disable().
splitComm2way() [2/2]
int par::splitComm2way (const bool * isEmptyList, MPI_Comm * new_comm, MPI_Comm orig_comm)
Splits a communication group into two depending on the values in isEmptyList. Both the groups are sorted in the ascending order of their ranks in the old comm. All processors must call this function with the same 'isEmptyList' array.
Author
Rahul Sampath
Parameters
isEmptyList flags (of length equal to the number of processors) to determine whether each processor is active or not.
orig_comm The comm group that needs to be split.
new_comm The new comm group.
splitCommBinary()
unsigned int par::splitCommBinary (MPI_Comm orig_comm, MPI_Comm * new_comm)
Splits a communication group into two, the first having a power of 2 number of processors and the other having the remainder. The first group is sorted in the ascending order of their ranks in the old comm and the second group is sorted in the descending order of their ranks in the old comm.
Author
Hari Sundar
Parameters
orig_comm The comm group that needs to be split.
new_comm The new comm group.
Referenced by par::NbxSynch::disable().
splitCommBinaryNoFlip()
unsigned int par::splitCommBinaryNoFlip (MPI_Comm orig_comm, MPI_Comm * new_comm)
Splits a communication group into two, the first having a power of 2 number of processors and the other having the remainder. Both the groups are sorted in the ascending order of their ranks in the old comm.
Author
Hari Sundar
Parameters
orig_comm The comm group that needs to be split.
new_comm The new comm group.
Referenced by par::NbxSynch::disable().
splitCommUsingSplittingRank()
int par::splitCommUsingSplittingRank (int splittingRank, MPI_Comm * new_comm, MPI_Comm orig_comm)
Referenced by par::NbxSynch::disable().
waitForDebugger()
void par::waitForDebugger (MPI_Comm comm, int commRank)
Utility for using gdb + mpi, based on notes by Tom Fogal.
Debugging MPI programs with the GNU debugger
Author
Tom Fogal, University of Utah
Masado Ishii
Date
2014-02-19 2019-10-30
Precondition
Building and running on Unix systems. Add waitForDebugger(comm, rank) right after MPI_Init(). (If using mpich): mpirun -np 2 -env USE_MPI_DEBUGGER 1 ./my_program pid=$(pgrep my_program | head -n 1) ; gdb -q -ex "attach ${pid}" -ex "set variable goAhead=1" -ex "finish"
Referenced by par::NbxSynch::disable().
Variable Documentation
DBG_nProc
int par::DBG_nProc
DBG_rProc
int par::DBG_rProc