DENDRO: ot Namespace Reference
ot Namespace Reference
Simple class to manage async data transfer in the ODA class.
Namespaces
DA_FLAGS
OCT_FLAGS
sfc
sfc_tree_utils
Classes
class AsyncExchangeContex
struct CellType
Identification of face-interior/edge-interior etc., for nodes. There are OuterDim+1 cell dimensions and pow(2,OuterDim) total cell orientations. The less-significant bits are used to store orientation, while the more-significant bits are used as redundant quick-access flags for the dimension. Orientation is represented as a bitvector, with a bit being set if that axis is part of the cell volume. A 0-cell (point) has all bits set to 0, while a OuterDim-cell (whole volume) has all bits set to 1. The cell dimension is how many bits are set to 1.
struct CompressedTree
class DA
class DefaultSummary
class DistTree
Intermediate container for filtering trees before creating the DA.
class Element
class Frame
struct FrameInputs
struct FrameInputs< dim, Inputs< Types... > >
struct FrameOutputs
struct FrameOutputs< dim, Outputs< Types... > >
struct GatherMap
class Inputs
struct IntRange
class IterateNodesToChildren
struct Keeper
struct KeyFunIdentity_maxDepth
struct KeyFunIdentity_Pt
struct KeyFunIdentity_TN
struct LevelSegment
class MatCompactRows
Store entries of the matrix in chunks corresponding to rows of elemental matrices.
class MatRecord
class MatvecBase
class MatvecBaseCoords
class MatvecBaseIn
class MatvecBaseOut
class MatvecBaseSummary
class MeshLoopFrame
class MeshLoopImpl
Iterator over TreeNodes (cells in the mesh) with in-place bucketing.
class MeshLoopInterface_S_NS
Interface for MeshLoop templated on the type of iteration.
struct OctreeAdler32
class Outputs
class Overlaps
struct PartitionFront
struct PartitionFrontBack
struct ScatterMap
struct Segment
struct SegmentSample
struct SFC_NodeSort
struct SFC_Search
struct SFC_State
struct SFC_Tree
class SFC_TreeLoop
class SubtreeInfo
class TNPoint
TreeNode + extra attributes to keep track of node uniqueness.
class TreeNode
A class to manage octants.
Typedefs
using ChildI = char
using ExtantCellFlagT = unsigned short
template<typename SrcType , typename RsltType >
using KeyFunInboundsContainer_t = std::function< RsltType(const SrcType &)>
using LevI = unsigned int
template<typename T , unsigned int dim, bool visitEmpty, bool visitPre, bool visitPost>
using MeshLoopInterface_Sorted = MeshLoopInterface_S_NS< T, dim, true, visitEmpty, visitPre, visitPost >
template<typename T , unsigned int dim, bool visitEmpty, bool visitPre, bool visitPost>
using MeshLoopInterface_Unsorted = MeshLoopInterface_S_NS< T, dim, false, visitEmpty, visitPre, visitPost >
template<typename T , unsigned int dim>
using MeshLoopPostSkipEmpty = MeshLoopInterface_Unsorted< T, dim, false, false, true >
template<typename T , unsigned int dim>
using MeshLoopPreSkipEmpty = MeshLoopInterface_Unsorted< T, dim, false, true, false >
template<unsigned int dim>
using MultiDA = std::vector< DA< dim > >
using RankI = DendroIntL
using RotI = int
Enumerations
enum GridAlignment { CoarseByFine, FineByCoarse }
enum RemeshPartition { SurrogateOutByIn, SurrogateInByOut }
Functions
template<typename T , unsigned int dim>
int checkSiblingLeafsTogether (std::vector< TreeNode< T, dim >> &tree, MPI_Comm nonempty_comm)
If there is a complete set of sibling leafs in a distributed sorted list, make sure they end up on the same rank. Makes it simpler to do mesh coarsening. Compare with Dendro-5.0 enforceSiblingsAreNotPartitioned(). In the below version, it is assumed that separated siblings might be partitioned across a consecutive sequence of two or more ranks. The old version assumed at most two ranks.
template<typename T , unsigned int dim>
void checkSiblingLeafsTogether (std::vector< TreeNode< T, dim >> &tree, MPI_Comm nonemptys, bool &isReceiver, bool &isSender, RankI &srcRankFirst, RankI &srcRankLast, RankI &destRank, unsigned int &countFront, unsigned int &countBack)
template<typename T , unsigned int dim>
OctreeAdler32 checksum_octant (const TreeNode< T, dim > &oct)
template<typename T , unsigned int dim>
OctreeAdler32 checksum_octants (const TreeNode< T, dim > *octs, size_t len)
template<typename T , unsigned int dim>
OctreeAdler32 checksum_octants (const std::vector< TreeNode< T, dim >> &octs)
template<typename T , unsigned int dim>
OctreeAdler32 checksum_octree (const TreeNode< T, dim > *octs, size_t len, MPI_Comm comm)
template<typename T , unsigned int dim>
OctreeAdler32 checksum_octree (const std::vector< TreeNode< T, dim >> &octs, MPI_Comm comm)
template<typename T , unsigned int dim>
std::array< T, dim > clampCoords (const std::array< T, dim > &coords, unsigned int cellLevel)
template<typename T , unsigned int dim>
int compareMorton (const TreeNode< T, dim > &a, const TreeNode< T, dim > &b)
size_t computeTotalSendSz (const ScatterMap &sm)
template<unsigned int dim>
DendroIntL constructRegularSubdomainDA (DA< dim > &newSubDA, unsigned int level, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, double sfc_tol=0.3)
Construct a DA representing the nodes of a hypercuboid with grid extents pow(2,a) * pow(2,b) * pow(2,c) * pow(2,d) (in 4D).
template<unsigned int dim>
DendroIntL constructRegularSubdomainDA (DA< dim > &newSubDA, std::vector< TreeNode< unsigned int, dim >> &newTreePart, unsigned int level, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, double sfc_tol=0.3)
template<unsigned int dim>
void constructRegularSubdomainDAHierarchy (std::vector< DA< dim >> &newMultiSubDA, std::vector< DA< dim >> &newSurrogateMultiSubDA, unsigned int coarsestLevel, unsigned int finestLevel, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, size_t grainSz=100, double sfc_tol=0.3)
Creates a uniform coarse grid at level coarsestLevel, having the extents determined by extentPowers, then generates a grid hierarchy by subdividing uniformly the coarse grid until finestLevel is reached.
template<template< typename TNT, unsigned TND > typename TN, typename T , unsigned dim>
constexpr unsigned coordDim (const TN< T, dim > *)
template<typename T , unsigned dim>
bool coversUnitCube (const std::vector< TreeNode< T, dim >> &tree, MPI_Comm comm)
template<typename T , unsigned int dim>
int createRegularOctree (std::vector< TreeNode< T, dim >> &out, unsigned int lev, MPI_Comm comm)
Create a distributed octree for a regular grid of specified depth.
template<typename T , unsigned int dim>
std::string dbgCoordStr (const std::array< T, dim > &tnCoords, unsigned int refLev)
template<typename T , unsigned int dim>
std::string dbgCoordStr (const TreeNode< T, dim > &tnCoords, unsigned int refLev)
template<unsigned int dim, typename DofT >
void distShiftNodes (const DA< dim > &srcDA, const DofT *srcLocal, const DA< dim > &destDA, DofT *destLocal, unsigned int ndofs=1)
Transfer data to an identically-structured but differently-partitioned grid, e.g. surrogate.
template<typename T , unsigned int dim>
void distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> &octants, const double sfc_tol=0.3)
template<typename T , unsigned int dim, typename X >
void distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> &octants, std::vector< X > &xs, const double sfc_tol=0.3)
template<typename T , unsigned int dim, typename X , typename Y >
void distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> &octants, std::vector< X > &xs, std::vector< Y > &ys, const double sfc_tol=0.3)
template<typename T , unsigned int dim>
TreeNode< T, dim > dld (const TreeNode< T, dim > &oct)
template<unsigned int dim>
const TreeNode< unsigned int, dim > & dummyOctant ()
template<typename T , unsigned int dim>
void fillAccessNodeCoordsFlat (bool useTNCoords, const std::vector< TreeNode< T, dim >> &nodeCoords, const TreeNode< T, dim > &subtree, unsigned int eleOrder, std::vector< double > &floatCoords)
template<unsigned int dim, class FrameT >
void fillLeafNodeBdry (const FrameT &frame, unsigned int eleOrder, std::vector< bool > &leafNodeBdry)
template<class TreeLoopT , unsigned int dim, class FrameT >
void fillLeafNodeBdry (const FrameT &frame, unsigned int eleOrder, const std::vector< bool > &parentNodeBdry, std::vector< bool > &leafNodeBdry)
template<typename DofT , typename TNT , unsigned int dim>
std::vector< TreeNode< TNT, dim > > function2BalancedOctree (std::function< void(const DofT *, DofT *)> func, const unsigned int dofSz, const unsigned int maxDepth, const double interp_tol, const double sfc_tol, const unsigned int order, MPI_Comm comm)
template<typename T , unsigned int dim>
void function2Octree (std::function< void(const double *, double *)> fx, const unsigned int numVars, const unsigned int *varIndex, const unsigned int numInterpVars, std::vector< TreeNode< T, dim >> &nodes, unsigned int maxDepth, const double &interp_tol, const double sfc_tol, unsigned int elementOrder, MPI_Comm comm)
Generates an octree based on a function provided by the user based on the Wavelet method to decide on adaptivity.
template<typename T , unsigned int dim, bool useRandom = true>
std::vector< TreeNode< T, dim > > getPts (unsigned int numPoints, unsigned int sLev=m_uiMaxDepth, unsigned int eLev=m_uiMaxDepth)
: generate random set of treeNodes for a specified dimension
template<typename T , unsigned int dim>
bool is2to1Balanced (const std::vector< TreeNode< T, dim >> &tree, MPI_Comm comm)
template<typename T , unsigned int dim>
bool isLocallySorted (const std::vector< TreeNode< T, dim >> &octList)
template<typename T , unsigned int dim>
bool isLocallySorted (const TreeNode< T, dim > *octList, size_t begin, size_t end)
template<typename T , unsigned dim>
bool isPartitioned (std::vector< TreeNode< T, dim >> octants, MPI_Comm comm)
template<typename T , unsigned int dim>
void keepSiblingLeafsTogether (std::vector< TreeNode< T, dim >> &tree, MPI_Comm comm)
template<typename T , unsigned int dim>
size_t lenContainedSorted (const TreeNode< T, dim > *octList, size_t begin, size_t end, TreeNode< T, dim > subtree, SFC_State< dim > sfc)
constexpr int nchild (int dim)
template <int dim>=""> constexpr int nchild() { return 1 << dim; }
template<typename T , unsigned int dim>
bool noLocalConsecutiveDups (const std::vector< TreeNode< T, dim >> &octants)
template<typename T , unsigned int dim>
bool noRemoteEdgeDups (const std::vector< TreeNode< T, dim >> &octants, MPI_Comm comm)
template<unsigned int dim>
const TreeNode< unsigned int, dim > & nullOctant ()
template<typename T , unsigned int dim>
std::ostream & operator<< (std::ostream &os, TreeNode< T, dim > const &other)
std::ostream & operator<< (std::ostream &out, const ScatterMap &sm)
std::ostream & operator<< (std::ostream &out, const GatherMap &gm)
template<typename T , unsigned int sdim, unsigned int ddim>
void permuteDims (unsigned int nDims, const ot::TreeNode< T, sdim > &srcNode, unsigned int *srcDims, ot::TreeNode< T, ddim > &dstNode, unsigned int *dstDims)
Add, remove, or permute dimensions from one TreeNode to another TreeNode.
template<typename T , unsigned int dim>
TreeNode< T, dim > physical2TreeNode (const double *physCoords, double physSize)
template<typename T , unsigned int dim>
std::ostream & printNodeCoords (const TreeNode< T, dim > *coordBegin, const TreeNode< T, dim > *coordEnd, unsigned int order=1, std::ostream &out=std::cout)
template<typename T , unsigned int dim, typename NodeT >
std::ostream & printNodes (const TreeNode< T, dim > *coordBegin, const TreeNode< T, dim > *coordEnd, const NodeT *valBegin, unsigned int order=1, std::ostream &out=std::cout)
template<typename T , unsigned int dim, typename NodeT >
std::ostream & printNodes (const TreeNode< T, dim > *coordBegin, const TreeNode< T, dim > *coordEnd, const NodeT *valBegin, const char **colors, unsigned int order=1, std::ostream &out=std::cout)
template<typename T , unsigned int dim>
void printtn (const TreeNode< T, dim > &tn, unsigned int eLev, FILE *out=stdout)
template<typename T , unsigned int dim>
std::ostream & printtn (const TreeNode< T, dim > &tn, unsigned int eLev, std::ostream &out=std::cout)
template<typename T , unsigned int dim>
void projectSliceKTree (const TreeNode< T, dim > *in, std::vector< TreeNode< T, dim-1 >> &out, unsigned int numNodes, unsigned int sliceDim, T sliceVal)
perform a slicing operation and also lower the dimension.
template<typename T , unsigned int dim>
void quadTreeToGnuplot (const std::vector< TreeNode< T, dim >> &treePart, const int fineLev, const std::string &fileprefix, MPI_Comm comm)
std::vector< int > recvFromActive (const std::vector< int > &activeList, const std::vector< int > &sendToActive, MPI_Comm comm)
template<typename X >
Segment< X > segment_all (std::vector< X > &vec)
template<typename X >
Segment< const X > segment_all (const std::vector< X > &vec)
template<typename T , unsigned int dim>
void sliceKTree (const TreeNode< T, dim > *in, std::vector< TreeNode< T, dim >> &out, unsigned int numNodes, unsigned int sDim, T sliceVal)
perform slicing operation on k trees.
template<typename T , unsigned int dim>
std::vector< std::vector< TreeNode< T, dim > > > stratifyTree (const std::vector< TreeNode< T, dim >> &tree)
Separate a list of TreeNodes into separate vectors by level.
size_t totalRecvSz (const GatherMap &gm)
template<typename T , unsigned int dim>
void treeNode2Physical (const ot::TreeNode< T, dim > &octCoords, unsigned int eleOrder, double *physCoords)
Uses the level to identify the node on an element, then compute coords.
template<typename T , unsigned int dim>
void treeNode2Physical (const ot::TreeNode< T, dim > &octCoords, double *physCoords, double &physSize)
Get physical coordinates and physical size of an element.
template<unsigned int dim>
std::bitset<(1u<< dim)> vertexBoundary (const std::vector< bool > &nodeBdry, unsigned int eleOrder)
Variables
constexpr bool debug_have_periodic = true
Detailed Description
Simple class to manage async data transfer in the ODA class.
#include "tensor.h"
#include <vector>
#include "refel.h" #include "tensor.h"
Typedef Documentation
ChildI
using ot::ChildI = typedef char
Definition at line 58 of file tsort.h.
ExtantCellFlagT
using ot::ExtantCellFlagT = typedef unsigned short
Definition at line 38 of file treeNode.h.
KeyFunInboundsContainer_t
template<typename SrcType , typename RsltType > using ot::KeyFunInboundsContainer_t = typedef std::function<RsltType(const SrcType &)>
Definition at line 151 of file nsort.h.
LevI
using ot::LevI = typedef unsigned int
Definition at line 55 of file tsort.h.
MeshLoopInterface_Sorted
template<typename T , unsigned int dim, bool visitEmpty, bool visitPre, bool visitPost> using ot::MeshLoopInterface_Sorted = typedef MeshLoopInterface_S_NS<T, dim, true, visitEmpty, visitPre, visitPost>
Definition at line 29 of file meshLoop.h.
MeshLoopInterface_Unsorted
template<typename T , unsigned int dim, bool visitEmpty, bool visitPre, bool visitPost> using ot::MeshLoopInterface_Unsorted = typedef MeshLoopInterface_S_NS<T, dim, false, visitEmpty, visitPre, visitPost>
Definition at line 33 of file meshLoop.h.
MeshLoopPostSkipEmpty
template<typename T , unsigned int dim> using ot::MeshLoopPostSkipEmpty = typedef MeshLoopInterface_Unsorted<T, dim, false, false, true>
Definition at line 40 of file meshLoop.h.
MeshLoopPreSkipEmpty
template<typename T , unsigned int dim> using ot::MeshLoopPreSkipEmpty = typedef MeshLoopInterface_Unsorted<T, dim, false, true, false>
Definition at line 37 of file meshLoop.h.
MultiDA
template<unsigned int dim> using ot::MultiDA = typedef std::vector<DA<dim> >
Definition at line 80 of file oda.h.
RankI
using ot::RankI = typedef DendroIntL
Definition at line 56 of file tsort.h.
RotI
using ot::RotI = typedef int
Definition at line 57 of file tsort.h.
Enumeration Type Documentation
GridAlignment
enum ot::GridAlignment
Enumerator
CoarseByFine
FineByCoarse
Definition at line 65 of file tsort.h.
RemeshPartition
enum ot::RemeshPartition
Enumerator
SurrogateOutByIn
SurrogateInByOut
Definition at line 66 of file tsort.h.
Function Documentation
checkSiblingLeafsTogether() [1/2]
template<typename T , unsigned int dim> int ot::checkSiblingLeafsTogether (std::vector< TreeNode< T, dim >> & tree, MPI_Comm nonempty_comm)
If there is a complete set of sibling leafs in a distributed sorted list, make sure they end up on the same rank. Makes it simpler to do mesh coarsening. Compare with Dendro-5.0 enforceSiblingsAreNotPartitioned(). In the below version, it is assumed that separated siblings might be partitioned across a consecutive sequence of two or more ranks. The old version assumed at most two ranks.
Author
Masado Ishii
Parameters
[in] tree Distributed sorted complete tree of TreeNodes.
[in] comm MPI communicator.
Returns
the global number of ranks holding broken siblings.
Definition at line 806 of file octUtils.h.
References par::Mpi_Allreduce().
Referenced by keepSiblingLeafsTogether().
checkSiblingLeafsTogether() [2/2]
template<typename T , unsigned int dim> void ot::checkSiblingLeafsTogether (std::vector< TreeNode< T, dim >> & tree, MPI_Comm nonemptys, bool & isReceiver, bool & isSender, RankI & srcRankFirst, RankI & srcRankLast, RankI & destRank, unsigned int & countFront, unsigned int & countBack)
Definition at line 829 of file octUtils.h.
References ot::TreeNode< T, dim >::getParent().
checksum_octant()
template<typename T , unsigned int dim> OctreeAdler32 ot::checksum_octant (const TreeNode< T, dim > & oct)
Definition at line 1226 of file octUtils.h.
References ot::OctreeAdler32::code, ot::TreeNode< T, dim >::coords(), ot::TreeNode< T, dim >::getLevel(), and ot::OctreeAdler32::len.
Referenced by checksum_octants().
checksum_octants() [1/2]
template<typename T , unsigned int dim> OctreeAdler32 ot::checksum_octants (const TreeNode< T, dim > * octs, size_t len)
Definition at line 1239 of file octUtils.h.
References checksum_octant().
Referenced by checksum_octants(), and checksum_octree().
checksum_octants() [2/2]
template<typename T , unsigned int dim> OctreeAdler32 ot::checksum_octants (const std::vector< TreeNode< T, dim >> & octs)
Definition at line 1258 of file octUtils.h.
References checksum_octants().
checksum_octree() [1/2]
template<typename T , unsigned int dim> OctreeAdler32 ot::checksum_octree (const TreeNode< T, dim > * octs, size_t len, MPI_Comm comm)
Definition at line 1249 of file octUtils.h.
References checksum_octants(), and par::Mpi_Allreduce().
Referenced by checksum_octree().
checksum_octree() [2/2]
template<typename T , unsigned int dim> OctreeAdler32 ot::checksum_octree (const std::vector< TreeNode< T, dim >> & octs, MPI_Comm comm)
Definition at line 1265 of file octUtils.h.
References checksum_octree().
clampCoords()
template<typename T , unsigned int dim> std::array<T, dim> ot::clampCoords (const std::array< T, dim > & coords, unsigned int cellLevel)
Definition at line 152 of file tnUtils.h.
References m_uiMaxDepth.
compareMorton()
template<typename T , unsigned int dim> int ot::compareMorton (const TreeNode< T, dim > & a, const TreeNode< T, dim > & b)
Definition at line 82 of file tnUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getMortonIndex(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
computeTotalSendSz()
size_t ot::computeTotalSendSz (const ScatterMap & sm) inline
Definition at line 242 of file nsort.h.
References ot::ScatterMap::m_sendCounts.
constructRegularSubdomainDA() [1/2]
template<unsigned int dim> DendroIntL ot::constructRegularSubdomainDA (DA< dim > & newSubDA, unsigned int level, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, double sfc_tol = 0.3)
Construct a DA representing the nodes of a hypercuboid with grid extents pow(2,a) * pow(2,b) * pow(2,c) * pow(2,d) (in 4D).
Parameters
level Level of the uniform refinement.
extentPowers Array of powers {a,b,c,...} depending on the dimension. a,b,c,... <= level.
eleOrder Elemental order.
[out] newSubDA The resulting DA object.
constructRegularSubdomainDA() [2/2]
template<unsigned int dim> DendroIntL ot::constructRegularSubdomainDA (DA< dim > & newSubDA, std::vector< TreeNode< unsigned int, dim >> & newTreePart, unsigned int level, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, double sfc_tol = 0.3)
constructRegularSubdomainDAHierarchy()
template<unsigned int dim> void ot::constructRegularSubdomainDAHierarchy (std::vector< DA< dim >> & newMultiSubDA, std::vector< DA< dim >> & newSurrogateMultiSubDA, unsigned int coarsestLevel, unsigned int finestLevel, std::array< unsigned int, dim > extentPowers, unsigned int eleOrder, MPI_Comm comm, size_t grainSz = 100, double sfc_tol = 0.3)
Creates a uniform coarse grid at level coarsestLevel, having the extents determined by extentPowers, then generates a grid hierarchy by subdividing uniformly the coarse grid until finestLevel is reached.
coordDim()
template<template< typename TNT, unsigned TND > typename TN, typename T , unsigned dim> constexpr unsigned ot::coordDim (const TN< T, dim > *)
Definition at line 44 of file treeNode.h.
coversUnitCube()
template<typename T , unsigned dim> bool ot::coversUnitCube (const std::vector< TreeNode< T, dim >> & tree, MPI_Comm comm)
createRegularOctree()
template<typename T , unsigned int dim> int ot::createRegularOctree (std::vector< TreeNode< T, dim >> & out, unsigned int lev, MPI_Comm comm)
Create a distributed octree for a regular grid of specified depth.
Definition at line 157 of file octUtils.h.
References ot::SFC_Tree< T, dim >::distTreeSort(), function2Octree(), ot::TreeNode< T, dim >::getChildMorton(), ot::TreeNode< T, dim >::getLevel(), and m_uiMaxDepth.
dbgCoordStr() [1/2]
template<typename T , unsigned int dim> std::string ot::dbgCoordStr (const std::array< T, dim > & tnCoords, unsigned int refLev)
Definition at line 126 of file tnUtils.h.
References m_uiMaxDepth, and par::shift().
dbgCoordStr() [2/2]
template<typename T , unsigned int dim> std::string ot::dbgCoordStr (const TreeNode< T, dim > & tnCoords, unsigned int refLev)
Definition at line 143 of file tnUtils.h.
References ot::TreeNode< T, dim >::getAnchor().
distShiftNodes()
template<unsigned int dim, typename DofT > void ot::distShiftNodes (const DA< dim > & srcDA, const DofT * srcLocal, const DA< dim > & destDA, DofT * destLocal, unsigned int ndofs = 1)
Transfer data to an identically-structured but differently-partitioned grid, e.g. surrogate.
Parameters
srcDA Mesh-free representation of the source grid.
srcLocal Pointer to local segment of the source vector.
destDA Mesh-free representation of the destination grid.
destLocal Pointer to the local segment of the destination vector.
comm MPI communicator over which the transfer takes place. Need not equal the src/dest DA comms.
distTreePartition_kway() [1/3]
template<typename T , unsigned int dim> void ot::distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> & octants, const double sfc_tol = 0.3)
distTreePartition_kway() [2/3]
template<typename T , unsigned int dim, typename X > void ot::distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> & octants, std::vector< X > & xs, const double sfc_tol = 0.3)
distTreePartition_kway() [3/3]
template<typename T , unsigned int dim, typename X , typename Y > void ot::distTreePartition_kway (MPI_Comm comm, std::vector< TreeNode< T, dim >> & octants, std::vector< X > & xs, std::vector< Y > & ys, const double sfc_tol = 0.3)
dld()
template<typename T , unsigned int dim> TreeNode<T, dim> ot::dld (const TreeNode< T, dim > & oct)
Definition at line 233 of file tnUtils.h.
References ot::SFC_State< dim >::child_curve(), ot::SFC_State< dim >::child_num(), ot::TreeNode< T, dim >::getChildMorton(), ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getMortonIndex(), m_uiMaxDepth, and nchild().
dummyOctant()
template<unsigned int dim> const TreeNode<unsigned int, dim>& ot::dummyOctant ()
Definition at line 104 of file sfcTreeLoop_matvec_io.h.
fillAccessNodeCoordsFlat()
template<typename T , unsigned int dim> void ot::fillAccessNodeCoordsFlat (bool useTNCoords, const std::vector< TreeNode< T, dim >> & nodeCoords, const TreeNode< T, dim > & subtree, unsigned int eleOrder, std::vector< double > & floatCoords)
Definition at line 859 of file sfcTreeLoop_matvec.h.
References ot::TNPoint< T, dim >::get_relNodeCoords(), ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), intPow(), and m_uiMaxDepth.
Referenced by ot::MatvecBase< dim, NodeT >::child2Parent(), ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat(), ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat().
fillLeafNodeBdry() [1/2]
template<unsigned int dim, class FrameT > void ot::fillLeafNodeBdry (const FrameT & frame, unsigned int eleOrder, std::vector< bool > & leafNodeBdry)
fillLeafNodeBdry() [2/2]
template<class TreeLoopT , unsigned int dim, class FrameT > void ot::fillLeafNodeBdry (const FrameT & frame, unsigned int eleOrder, const std::vector< bool > & parentNodeBdry, std::vector< bool > & leafNodeBdry)
Definition at line 943 of file sfcTreeLoop_matvec.h.
References ot::TreeNode< T, dim >::getIsOnTreeBdry(), ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getParent(), and ot::TreeNode< T, dim >::getX().
function2BalancedOctree()
template<typename DofT , typename TNT , unsigned int dim> std::vector<TreeNode<TNT, dim> > ot::function2BalancedOctree (std::function< void(const DofT *, DofT *)> func, const unsigned int dofSz, const unsigned int maxDepth, const double interp_tol, const double sfc_tol, const unsigned int order, MPI_Comm comm)
Definition at line 271 of file octUtils.h.
function2Octree()
template<typename T , unsigned int dim> void ot::function2Octree (std::function< void(const double *, double *)> fx, const unsigned int numVars, const unsigned int * varIndex, const unsigned int numInterpVars, std::vector< TreeNode< T, dim >> & nodes, unsigned int maxDepth, const double & interp_tol, const double sfc_tol, unsigned int elementOrder, MPI_Comm comm)
Generates an octree based on a function provided by the user based on the Wavelet method to decide on adaptivity.
Author
Hari Sundar
Milinda Fernando
Masado Ishii
Parameters
[in] fx the function that taxes $x,y,z$ coordinates and returns the the value at that point
[in] numVars number of total variables computed from fx function.
[in] varIndex variable index location that can be used to ascess double * pointer in fx, to determine the refinement of octree.
[in] numInterpVars Number of variables considered during the refinement
[in] maxDepth The maximum depth that the octree should be refined to.
[in] interp_tol user specified tolerance for the wavelet representation of the function.
[in] sfc_tol sfc tree partitioning tolerance to control communication/load balance tradeoff.
[in] elementOrder order of the element when defining the wavelet representation of the function.
[in] comm The MPI communicator to be use for parallel computation.
TODO Make this function conform to xyzxyz ordering of dofs.
Generates an octree based on a function provided by the user. The function is expected to return the signed distance to the surface that needs to be meshed. The coordinates are expected to be in [0,1]^3.
Works on arbitrary dimensionality.
Ported from Dendro-5.0.
size
SFC_Tree<T,dim>::distTreeConstruction(nodes, nodes_new, 1, sfc_tol, comm);
size
SFC_Tree<T,dim>::distTreeConstruction(nodes, nodes_new, 1, sfc_tol, comm);
Definition at line 293 of file octUtils.h.
References DendroIntL, ot::SFC_Tree< T, dim >::distRemoveDuplicates(), ot::TreeNode< T, dim >::getChildMorton(), intPow(), m_uiMaxDepth, par::Mpi_Allreduce(), par::Mpi_Bcast(), and normLInfty().
Referenced by createRegularOctree().
getPts()
template<typename T , unsigned int dim, bool useRandom = true> std::vector<TreeNode<T,dim> > ot::getPts (unsigned int numPoints, unsigned int sLev = m_uiMaxDepth, unsigned int eLev = m_uiMaxDepth) inline
: generate random set of treeNodes for a specified dimension
Author
: Masado Ishi
Parameters
[in] numPoints number of treeNodes need to be generated.
std::uniform_int_distribution<T> distCoord(0, maxCoord);
Definition at line 37 of file octUtils.h.
References m_uiMaxDepth.
is2to1Balanced()
template<typename T , unsigned int dim> bool ot::is2to1Balanced (const std::vector< TreeNode< T, dim >> & tree, MPI_Comm comm)
Assumes tree is a distributed tree with no overlaps.
isLocallySorted() [1/2]
template<typename T , unsigned int dim> bool ot::isLocallySorted (const std::vector< TreeNode< T, dim >> & octList)
isLocallySorted() [2/2]
template<typename T , unsigned int dim> bool ot::isLocallySorted (const TreeNode< T, dim > * octList, size_t begin, size_t end)
isPartitioned()
template<typename T , unsigned dim> bool ot::isPartitioned (std::vector< TreeNode< T, dim >> octants, MPI_Comm comm)
keepSiblingLeafsTogether()
template<typename T , unsigned int dim> void ot::keepSiblingLeafsTogether (std::vector< TreeNode< T, dim >> & tree, MPI_Comm comm)
Definition at line 1003 of file octUtils.h.
References checkSiblingLeafsTogether().
lenContainedSorted()
template<typename T , unsigned int dim> size_t ot::lenContainedSorted (const TreeNode< T, dim > * octList, size_t begin, size_t end, TreeNode< T, dim > subtree, SFC_State< dim > sfc)
nchild()
constexpr int ot::nchild (int dim)
template <int dim>=""> constexpr int nchild() { return 1 << dim; }
Definition at line 41 of file treeNode.h.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::SFC_State< dim >::child_curve(), ot::SFC_State< dim >::child_num(), ot::SFC_State< dim >::child_rank(), dld(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getExtantTreeChildrenMorton(), ot::SFC_Tree< T, dim >::locTreeSortMaxDepth(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
noLocalConsecutiveDups()
template<typename T , unsigned int dim> bool ot::noLocalConsecutiveDups (const std::vector< TreeNode< T, dim >> & octants)
noRemoteEdgeDups()
template<typename T , unsigned int dim> bool ot::noRemoteEdgeDups (const std::vector< TreeNode< T, dim >> & octants, MPI_Comm comm)
nullOctant()
template<unsigned int dim> const TreeNode<unsigned int, dim>& ot::nullOctant ()
Definition at line 98 of file sfcTreeLoop_matvec_io.h.
operator<<() [1/3]
template<typename T , unsigned int dim> std::ostream& ot::operator<< (std::ostream & os, TreeNode< T, dim > const & other)
operator<<() [2/3]
std::ostream& ot::operator<< (std::ostream & out, const ScatterMap & sm)
Referenced by totalRecvSz().
operator<<() [3/3]
std::ostream& ot::operator<< (std::ostream & out, const GatherMap & gm)
permuteDims()
template<typename T , unsigned int sdim, unsigned int ddim> void ot::permuteDims (unsigned int nDims, const ot::TreeNode< T, sdim > & srcNode, unsigned int * srcDims, ot::TreeNode< T, ddim > & dstNode, unsigned int * dstDims) inline
Add, remove, or permute dimensions from one TreeNode to another TreeNode.
Author
Masado Ishii
Definition at line 15 of file tnUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), ot::TreeNode< T, dim >::setLevel(), and ot::TreeNode< T, dim >::setX().
Referenced by projectSliceKTree().
physical2TreeNode()
template<typename T , unsigned int dim> TreeNode<T, dim> ot::physical2TreeNode (const double * physCoords, double physSize)
Definition at line 65 of file tnUtils.h.
References m_uiMaxDepth.
printNodeCoords()
template<typename T , unsigned int dim> std::ostream& ot::printNodeCoords (const TreeNode< T, dim > * coordBegin, const TreeNode< T, dim > * coordEnd, unsigned int order = 1, std::ostream & out = std::cout)
if (numNodes) subdomain = *coordBegin;
while (!(Element<T,dim>(subdomain).isIncident(coordBegin[ii]))) subdomain = subdomain.getParent();
const unsigned int charBound = (numTiles1D * 10 + 4)*numTiles1D + 2;
std::vector<char> charBuffer(charBound + 10, '\0');
const char * bufEnd = &(*charBuffer.end()) - 10;
Definition at line 517 of file octUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
printNodes() [1/2]
template<typename T , unsigned int dim, typename NodeT > std::ostream& ot::printNodes (const TreeNode< T, dim > * coordBegin, const TreeNode< T, dim > * coordEnd, const NodeT * valBegin, unsigned int order = 1, std::ostream & out = std::cout)
if (numNodes) subdomain = *coordBegin;
while (!(Element<T,dim>(subdomain).isIncident(coordBegin[ii]))) subdomain = subdomain.getParent();
const unsigned int charBound = (numTiles1D * 10 + 4)*numTiles1D + 2;
std::vector<char> charBuffer(charBound + 10, '\0');
const char * bufEnd = &(*charBuffer.end()) - 10;
Definition at line 609 of file octUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
printNodes() [2/2]
template<typename T , unsigned int dim, typename NodeT > std::ostream& ot::printNodes (const TreeNode< T, dim > * coordBegin, const TreeNode< T, dim > * coordEnd, const NodeT * valBegin, const char ** colors, unsigned int order = 1, std::ostream & out = std::cout)
if (numNodes) subdomain = *coordBegin;
while (!(Element<T,dim>(subdomain).isIncident(coordBegin[ii]))) subdomain = subdomain.getParent();
const unsigned int charBound = (numTiles1D * 10 + 4)*numTiles1D + 2;
std::vector<char> charBuffer(charBound + 10, '\0');
const char * bufEnd = &(*charBuffer.end()) - 10;
Definition at line 696 of file octUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), m_uiMaxDepth, and NRM.
printtn() [1/2]
template<typename T , unsigned int dim> void ot::printtn (const TreeNode< T, dim > & tn, unsigned int eLev, FILE * out = stdout)
Definition at line 165 of file tnUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
printtn() [2/2]
template<typename T , unsigned int dim> std::ostream& ot::printtn (const TreeNode< T, dim > & tn, unsigned int eLev, std::ostream & out = std::cout)
Definition at line 192 of file tnUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
projectSliceKTree()
template<typename T , unsigned int dim> void ot::projectSliceKTree (const TreeNode< T, dim > * in, std::vector< TreeNode< T, dim-1 >> & out, unsigned int numNodes, unsigned int sliceDim, T sliceVal)
perform a slicing operation and also lower the dimension.
Author
Masado Ishii
Precondition
template parameter dim must be greater than 1.
Definition at line 126 of file octUtils.h.
References permuteDims(), and sliceKTree().
quadTreeToGnuplot()
template<typename T , unsigned int dim> void ot::quadTreeToGnuplot (const std::vector< TreeNode< T, dim >> & treePart, const int fineLev, const std::string & fileprefix, MPI_Comm comm)
Definition at line 1079 of file octUtils.h.
References m_uiMaxDepth, and par::Mpi_Scan().
recvFromActive()
std::vector<int> ot::recvFromActive (const std::vector< int > & activeList, const std::vector< int > & sendToActive, MPI_Comm comm)
Discover sources from destinations within active list in comm
segment_all() [1/2]
template<typename X > Segment<X> ot::segment_all (std::vector< X > & vec)
Definition at line 144 of file tsort.h.
segment_all() [2/2]
template<typename X > Segment<const X> ot::segment_all (const std::vector< X > & vec)
Definition at line 150 of file tsort.h.
sliceKTree()
template<typename T , unsigned int dim> void ot::sliceKTree (const TreeNode< T, dim > * in, std::vector< TreeNode< T, dim >> & out, unsigned int numNodes, unsigned int sDim, T sliceVal)
perform slicing operation on k trees.
Parameters
[in] in input k-tree
[out] out sliced k-tree
[in] numNodes number of input nodes
[in] sDim slicing dimention.
[in] sliceVal extraction value for the slice
[in] tolernace tolerance value for slice extraction.
Definition at line 107 of file octUtils.h.
Referenced by projectSliceKTree().
stratifyTree()
template<typename T , unsigned int dim> std::vector<std::vector<TreeNode<T,dim> > > ot::stratifyTree (const std::vector< TreeNode< T, dim >> & tree) inline
Separate a list of TreeNodes into separate vectors by level.
Author
Masado Ishii
Definition at line 84 of file octUtils.h.
References m_uiMaxDepth.
totalRecvSz()
size_t ot::totalRecvSz (const GatherMap & gm) inline
Definition at line 250 of file nsort.h.
References ot::GatherMap::m_locCount, ot::GatherMap::m_totalCount, and operator<<().
treeNode2Physical() [1/2]
template<typename T , unsigned int dim> void ot::treeNode2Physical (const ot::TreeNode< T, dim > & octCoords, unsigned int eleOrder, double * physCoords)
Uses the level to identify the node on an element, then compute coords.
Definition at line 27 of file tnUtils.h.
References ot::TNPoint< T, dim >::get_nodeRank1D(), ot::TreeNode< T, dim >::getAncestor(), ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
Referenced by ot::DistTree< C, dim >::conversionDomainDeciderTN_asCell(), ot::DistTree< C, dim >::conversionDomainDeciderTN_asPoint(), and ot::DistTree< C, dim >::filterOctList().
treeNode2Physical() [2/2]
template<typename T , unsigned int dim> void ot::treeNode2Physical (const ot::TreeNode< T, dim > & octCoords, double * physCoords, double & physSize)
Get physical coordinates and physical size of an element.
Definition at line 50 of file tnUtils.h.
References ot::TreeNode< T, dim >::getLevel(), ot::TreeNode< T, dim >::getX(), and m_uiMaxDepth.
vertexBoundary()
template<unsigned int dim> std::bitset<(1u << dim)> ot::vertexBoundary (const std::vector< bool > & nodeBdry, unsigned int eleOrder)
Definition at line 921 of file sfcTreeLoop_matvec.h.
Variable Documentation
debug_have_periodic
constexpr bool ot::debug_have_periodic = true
Definition at line 29 of file treeNode.h.