DENDRO: binOp Namespace Reference
binOp Namespace Reference
A set of functions for fast binary operations.
Classes
class TallBitMatrix
Expand/collapse bits in a bit string. TallBitMatrix expands bits in a bit string.
Functions
unsigned long long binLength (unsigned long long num)
unsigned int binToDec (unsigned int *numBin, unsigned int binLen)
template<typename U >
unsigned int countOnes (U y)
unsigned int fastLog2 (unsigned int num)
template<typename T >
unsigned int getBit (T val, unsigned int i)
gets the i^th bit on the value val
int getNextHighestPowerOfTwo (unsigned int n)
int getPrevHighestPowerOfTwo (unsigned int n)
template<typename B , unsigned int dim>
constexpr B hyperplaneHiMask (unsigned int d, B multiplier=1u)
template<typename B , unsigned int dim>
constexpr B hyperplaneLoMask (unsigned int d, B multiplier=1u)
bool isPowerOfTwo (unsigned int n)
unsigned int lowestOnePos (unsigned int num)
Finds the 0-based index of the least-significant 1, starting from least significant bits.
template<typename T >
T next_power_of_2 (T i)
template<int dim, typename T >
T next_power_of_pow_2_dim (T i)
template<typename B >
B reflectHyperplane (B binaryHypercube, unsigned int d)
Partial reversal of the bits, by reflecting across a hyperplane.
template<typename B >
void selectHyperplanes (B binaryHypercube, unsigned int d, B &loPlane, B &hiPlane, unsigned int &shift)
If each bit is a vertex in a hypercube in lexicographic order, select the plane x_d = 1 and move it to the plane x_d = 0.
template<typename T >
void setBit (T &val, unsigned int i)
sets the i^th bit on the value val
int toBin (unsigned int dec, unsigned int binLen, std::vector< bool > &result)
Converts a decimal number to binary.
Detailed Description
A set of functions for fast binary operations.
Author
Hari Sundar
Masado Ishii
Function Documentation
binLength()
unsigned long long binOp::binLength (unsigned long long num)
Returns
the minimum number of digits required to represent num in binary
binToDec()
unsigned int binOp::binToDec (unsigned int * numBin, unsigned int binLen)
Parameters
numBin binary representation of the number
binLen length of numBin
Returns
the decimal representation of the binary number
countOnes()
template<typename U > unsigned int binOp::countOnes (U y) inline
Definition at line 126 of file binUtils.h.
fastLog2()
unsigned int binOp::fastLog2 (unsigned int num)
return log to base 2 of num
getBit()
template<typename T > unsigned int binOp::getBit (T val, unsigned int i) inline
gets the i^th bit on the value val
Definition at line 119 of file binUtils.h.
getNextHighestPowerOfTwo()
int binOp::getNextHighestPowerOfTwo (unsigned int n)
Returns
compute the next highest power of 2 of 32-bit v
getPrevHighestPowerOfTwo()
int binOp::getPrevHighestPowerOfTwo (unsigned int n)
Returns
compute the prev highest power of 2 of 32-bit v
hyperplaneHiMask()
template<typename B , unsigned int dim> constexpr B binOp::hyperplaneHiMask (unsigned int d, B multiplier = 1u)
Definition at line 197 of file binUtils.h.
hyperplaneLoMask()
template<typename B , unsigned int dim> constexpr B binOp::hyperplaneLoMask (unsigned int d, B multiplier = 1u)
Definition at line 188 of file binUtils.h.
isPowerOfTwo()
bool binOp::isPowerOfTwo (unsigned int n)
Returns
true if n is a power of 2.
lowestOnePos()
unsigned int binOp::lowestOnePos (unsigned int num)
Finds the 0-based index of the least-significant 1, starting from least significant bits.
Author
Masado Ishii
Referenced by next_power_of_pow_2_dim().
next_power_of_2()
template<typename T > T binOp::next_power_of_2 (T i) inline
next_power_of_2()
Author
Masado Ishii
Definition at line 67 of file binUtils.h.
Referenced by next_power_of_pow_2_dim().
next_power_of_pow_2_dim()
template<int dim, typename T > T binOp::next_power_of_pow_2_dim (T i) inline
next_power_of_pow_2_dim()
Author
Masado Ishii
Definition at line 86 of file binUtils.h.
References lowestOnePos(), and next_power_of_2().
reflectHyperplane()
template<typename B > B binOp::reflectHyperplane (B binaryHypercube, unsigned int d)
Partial reversal of the bits, by reflecting across a hyperplane.
Definition at line 238 of file binUtils.h.
References selectHyperplanes(), and par::shift().
selectHyperplanes()
template<typename B > void binOp::selectHyperplanes (B binaryHypercube, unsigned int d, B & loPlane, B & hiPlane, unsigned int & shift)
If each bit is a vertex in a hypercube in lexicographic order, select the plane x_d = 1 and move it to the plane x_d = 0.
Definition at line 209 of file binUtils.h.
References par::shift().
Referenced by reflectHyperplane().
setBit()
template<typename T > void binOp::setBit (T & val, unsigned int i) inline
sets the i^th bit on the value val
Definition at line 112 of file binUtils.h.
toBin()
int binOp::toBin (unsigned int dec, unsigned int binLen, std::vector< bool > & result)
Converts a decimal number to binary.
Parameters
dec the decimal number
binLen the number of digits required in the binary representation
result the binary representation
Returns
error flag