DENDRO: ot::sfc_tree_utils Namespace Reference
ot::sfc_tree_utils Namespace Reference
Classes
struct Copier
struct Resizer
Functions
template<unsigned int dim, class InputTypes , class OutputTypes , typename SummaryType , class ConcreteTreeLoop >
void topDownNodes (Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop > &parentFrame, ot::ExtantCellFlagT *extantChildren)
template<unsigned int dim, typename ... ITypes, class OutputTypes , typename S , class CTL >
void topDownNodes (Frame< dim, Inputs< TreeNode< unsigned int, dim >, ITypes... >, OutputTypes, S, CTL > &parentFrame, ot::ExtantCellFlagT *extantChildren)
Function Documentation
topDownNodes() [1/2]
template<unsigned int dim, class InputTypes , class OutputTypes , typename SummaryType , class ConcreteTreeLoop > void ot::sfc_tree_utils::topDownNodes (Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop > & parentFrame, ot::ExtantCellFlagT * extantChildren)
Referenced by ot::MatvecBase< dim, NodeT >::getNodeNonhangingIn().
topDownNodes() [2/2]
template<unsigned int dim, typename ... ITypes, class OutputTypes , typename S , class CTL > void ot::sfc_tree_utils::topDownNodes (Frame< dim, Inputs< TreeNode< unsigned int, dim >, ITypes... >, OutputTypes, S, CTL > & parentFrame, ot::ExtantCellFlagT * extantChildren)
Definition at line 941 of file sfcTreeLoop.h.
References litb::TupleExtractor< RetType, Types >::applied_to(), litb::BiTupleExtractor< RetType, Types >::applied_to(), ot::sfc_tree_utils::Resizer< Types >::set(), and ot::sfc_tree_utils::Copier< Types >::set().
Referenced by ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::step().