DENDRO: ot::SFC_Tree< T, dim > Struct Template Reference
ot::SFC_Tree< T, dim > Struct Template Reference
#include <tsort.h>
Classes
struct PartitionFrontBackRequest
Static Public Member Functions
static PartitionFront< T, dim > allgatherSplitters (bool nonempty, const TreeNode< T, dim > &front, MPI_Comm comm, std::vector< int > *activeList=nullptr)
Allgather the first TreeNode from every processor. An empty rank is represented by getting its successor's splitter, or the root TreeNode if it has no successor. This method does not call MPI_Comm_split().
static PartitionFrontBack< T, dim > allgatherSplitters (bool nonempty, const TreeNode< T, dim > &front, const TreeNode< T, dim > &back, MPI_Comm comm, std::vector< int > *activeList=nullptr)
Allgather first and last TreeNode. An empty rank's front and back are both set to successor's front.
static std::vector< TreeNode< T, dim > > dist_bcastSplitters (const TreeNode< T, dim > *start, MPI_Comm comm)
Broadcast the first TreeNode from every processor so we have global access to the splitter list.
static std::vector< TreeNode< T, dim > > dist_bcastSplitters (const TreeNode< T, dim > *start, MPI_Comm globalComm, MPI_Comm activeComm, bool isActive, std::vector< int > &activeList)
static void distAdoptAncestors (std::vector< TreeNode< T, dim >> &tree, MPI_Comm comm)
static void distCoalesceSiblings (std::vector< TreeNode< T, dim >> &tree, MPI_Comm comm)
If all siblings are leafs, push them onto the last incident rank. (last, not first, so that algorithm is same as distAdoptAncestors).
static void distMinimalBalanced (std::vector< TreeNode< T, dim >> &tree, double sfc_tol, MPI_Comm comm)
static void distMinimalBalancedGlobalSort (std::vector< TreeNode< T, dim >> &tree, double sfc_tol, MPI_Comm comm)
static void distMinimalComplete (std::vector< TreeNode< T, dim >> &tree, double sfc_tol, MPI_Comm comm)
static void distRemeshSubdomain (const std::vector< TreeNode< T, dim >> &inTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, std::vector< TreeNode< T, dim >> &outTree, double loadFlexibility, MPI_Comm comm)
static void distRemeshWholeDomain (const std::vector< TreeNode< T, dim >> &inTree, const std::vector< OCT_FLAGS::Refine > &refnFlags, std::vector< TreeNode< T, dim >> &outTree, double loadFlexibility, MPI_Comm comm)
static void distRemoveDuplicates (std::vector< TreeNode< T, dim >> &tree, double loadFlexibility, bool strict, MPI_Comm comm)
static void distTreeBalancing (std::vector< TreeNode< T, dim >> &points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm)
static void distTreeBalancingWithFilter (const ibm::DomainDecider &decider, std::vector< TreeNode< T, dim >> &points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm)
static void distTreeConstruction (std::vector< TreeNode< T, dim >> &points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm)
static void distTreeConstructionWithFilter (const ibm::DomainDecider &decider, std::vector< TreeNode< T, dim >> &points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm)
static void distTreeConstructionWithFilter (const ibm::DomainDecider &decider, bool refineAll, std::vector< TreeNode< T, dim >> &tree, LevI eLev, double loadFlexibility, MPI_Comm comm)
static void distTreePartition (std::vector< TreeNode< T, dim >> &points, unsigned int, double loadFlexibility, MPI_Comm comm)
static void distTreePartition (std::vector< TreeNode< T, dim >> &points, double loadFlexibility, MPI_Comm comm)
static void distTreeSort (std::vector< TreeNode< T, dim >> &points, double loadFlexibility, MPI_Comm comm)
static void firstDescendant (TreeNode< T, dim > &parent, RotI &pRot, LevI descendantLev)
Successively computes 0th child in SFC order to given level.
static void getContainingBlocks (TreeNode< T, dim > *points, RankI begin, RankI end, const TreeNode< T, dim > *splitters, RankI sBegin, RankI sEnd, LevI lev, SFC_State< dim > sfc, int &numPrevBlocks, const int startSize, std::vector< int > &outBlocks)
Given partition splitters and a list of (unordered) points, finds every block that contains at least some of the points.
static std::vector< TreeNode< T, dim > > getSurrogateGrid (RemeshPartition remeshPartition, const std::vector< TreeNode< T, dim >> &oldTree, const std::vector< TreeNode< T, dim >> &newTree, MPI_Comm comm)
static std::vector< TreeNode< T, dim > > getSurrogateGrid (const std::vector< TreeNode< T, dim >> &replicateGrid, const std::vector< TreeNode< T, dim >> &splittersFromGrid, MPI_Comm comm)
static void lastDescendant (TreeNode< T, dim > &parent, RotI &pRot, LevI descendantLev)
Successively computes (n-1)th child in SFC order to given level.
static std::vector< TreeNode< T, dim > > locCoarsen (const std::vector< TreeNode< T, dim >> &tree, std::vector< int > &&delta_level)
static void locCompleteResolved (const TreeNode< T, dim > *octants, std::vector< TreeNode< T, dim >> &tree, RankI begin, RankI end, SFC_State< dim > sfc, TreeNode< T, dim > pNode)
static void locMatchResolution (std::vector< TreeNode< T, dim >> &tree, const std::vector< TreeNode< T, dim >> &res)
static void locMinimalBalanced (std::vector< TreeNode< T, dim >> &tree)
static std::vector< TreeNode< T, dim > > locRefine (const std::vector< TreeNode< T, dim >> &tree, std::vector< int > &&delta_level)
static void locRemoveDuplicates (std::vector< TreeNode< T, dim >> &tnodes)
static void locRemoveDuplicatesStrict (std::vector< TreeNode< T, dim >> &tnodes)
static void locResolveTree (std::vector< TreeNode< T, dim >> &tree, std::vector< TreeNode< T, dim >> &&res)
static void locTreeBalancing (std::vector< TreeNode< T, dim >> &points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion)
static void locTreeConstruction (TreeNode< T, dim > *points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode)
static void locTreeConstructionWithFilter (const ibm::DomainDecider &decider, TreeNode< T, dim > *points, std::vector< TreeNode< T, dim >> &tree, RankI maxPtsPerRegion, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode)
static void locTreeConstructionWithFilter (const ibm::DomainDecider &decider, bool refineAll, std::vector< TreeNode< T, dim >> &tree, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode)
template<class PointType >
static void locTreeSort (std::vector< PointType > &points)
template<class PointType , typename... CompanionT>
static void locTreeSort (std::vector< PointType > &points, std::vector< CompanionT > &... companions)
template<class PointType >
static void locTreeSort (PointType *points, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc)
template<class KeyFun , typename PointType , typename KeyType , bool useCompanions, typename... Companion>
static void locTreeSort (PointType *points, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, KeyFun keyfun, Companion *... companions)
template<class PointType >
static void locTreeSortInUnitCube (std::vector< PointType > &points)
template<class PointType >
static void locTreeSortMaxDepth (std::vector< PointType > &points)
template<class PointType , typename... CompanionT>
static void locTreeSortMaxDepth (std::vector< PointType > &points, std::vector< CompanionT > &... companions)
static std::vector< size_t > lower_bound (const std::vector< TreeNode< T, dim >> &sortedOcts, const std::vector< TreeNode< T, dim >> &sortedKeys)
static void propagateNeighbours (std::vector< TreeNode< T, dim >> &tree)
Create auxiliary octants in bottom-up order to close the 2:1-balancing constraint.
static void removeDescendants (std::vector< TreeNode< T, dim >> &sortedOcts, const std::vector< TreeNode< T, dim >> &sortedKeys)
static void removeEqual (std::vector< TreeNode< T, dim >> &sortedOcts, const std::vector< TreeNode< T, dim >> &sortedKeys)
static void retainDescendants (std::vector< TreeNode< T, dim >> &sortedOcts, const std::vector< TreeNode< T, dim >> &sortedKeys)
static void SFC_bucketing (TreeNode< T, dim > *points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, std::array< RankI, 1+nchild(dim)> &outSplitters, RankI &outAncStart, RankI &outAncEnd)
template<class KeyFun , typename PointType , typename KeyType , bool useCompanions, typename... Companion>
static void SFC_bucketing_general (PointType *points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> &outSplitters, RankI &outAncStart, RankI &outAncEnd, Companion *... companions)
template<class KeyFun , typename PointType , typename KeyType >
static void SFC_bucketing_impl (PointType *points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> &outSplitters, RankI &outAncStart, RankI &outAncEnd)
template<class KeyFun , typename PointType , typename KeyType , typename ValueType >
static void SFC_bucketStable (const PointType *points, RankI begin, RankI end, LevI lev, KeyFun keyfun, bool separateAncestors, std::array< RankI, nchild(dim)+1 > offsets, const std::array< RankI, nchild(dim)+1 > &bucketEnds, ValueType *values)
template<class KeyFun , typename PointType , typename KeyType , typename CompanionHead , typename... CompanionTail>
static void SFC_bucketStable (const PointType *points, RankI begin, RankI end, LevI lev, KeyFun keyfun, bool separateAncestors, const std::array< RankI, nchild(dim)+1 > &offsets, const std::array< RankI, nchild(dim)+1 > &bucketEnds, CompanionHead *companionHead, CompanionTail *... companionTail)
static void SFC_locateBuckets (const TreeNode< T, dim > *points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, std::array< RankI, 1+nchild(dim)> &outSplitters, RankI &outAncStart, RankI &outAncEnd)
template<class KeyFun , typename PointType , typename KeyType >
static void SFC_locateBuckets_impl (const PointType *points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> &outSplitters, RankI &outAncStart, RankI &outAncEnd)
static void splitParents (std::vector< TreeNode< T, dim >> &tree)
static std::vector< int > treeNode2PartitionRank (const std::vector< TreeNode< T, dim >> &treeNodes, const PartitionFront< T, dim > &partitionSplitters)
Map a set of treeNodes in the domain to the partition ranks that own them. Repeat splitters are allowed. Empty ranks in the partition are allowed.
static std::vector< int > treeNode2PartitionRank (const std::vector< TreeNode< T, dim >> &treeNodes, const std::vector< TreeNode< T, dim >> &partitionFrontSplitters)
Map any collection of treeNodes in the domain to the partition ranks that own them. The rank ids are returned in the range [0 .. partitionFrontSplitters.size()-1].
static std::vector< IntRange<> > treeNode2PartitionRanks (const std::vector< TreeNode< T, dim >> &treeNodes, const PartitionFrontBack< T, dim > &partitionSplitters, const std::vector< int > *active)
Map a set of treeNodes in the domain to ranges of the partition ranks that they overlap. Repeat splitters are allowed. Empty ranks in the partition are allowed. To avoid sending data to inactive ranks, the return indices are relative to the active list.
static std::pair< size_t, size_t > tsearch_equal_range (const std::vector< TreeNode< T, dim >> &sortedOcts, const TreeNode< T, dim > &key)
static std::pair< size_t, size_t > tsearch_equal_range (const TreeNode< T, dim > *sortedOcts, const TreeNode< T, dim > &key, size_t begin, size_t end, LevI sLev, SFC_State< dim > sfc)
static size_t tsearch_lower_bound (const std::vector< TreeNode< T, dim >> &sortedOcts, const TreeNode< T, dim > &key)
static size_t tsearch_upper_bound (const std::vector< TreeNode< T, dim >> &sortedOcts, const TreeNode< T, dim > &key)
static std::vector< TreeNode< T, dim > > unstableOctants (const std::vector< TreeNode< T, dim >> &tree, const bool dangerLeft=true, const bool dangerRight=true)
Static Public Attributes
static std::vector< char > bucketStableAux
static constexpr bool RM_DUPS_AND_ANC = false
static constexpr bool RM_DUPS_ONLY = true
Detailed Description
template<typename T, unsigned int dim>
struct ot::SFC_Tree< T, dim >
Definition at line 282 of file tsort.h.
Member Function Documentation
allgatherSplitters() [1/2]
template<typename T, unsigned int dim> static PartitionFront<T, dim> ot::SFC_Tree< T, dim >::allgatherSplitters (bool nonempty, const TreeNode< T, dim > & front, MPI_Comm comm, std::vector< int > * activeList = nullptr) static
Allgather the first TreeNode from every processor. An empty rank is represented by getting its successor's splitter, or the root TreeNode if it has no successor. This method does not call MPI_Comm_split().
allgatherSplitters() [2/2]
template<typename T, unsigned int dim> static PartitionFrontBack<T, dim> ot::SFC_Tree< T, dim >::allgatherSplitters (bool nonempty, const TreeNode< T, dim > & front, const TreeNode< T, dim > & back, MPI_Comm comm, std::vector< int > * activeList = nullptr) static
Allgather first and last TreeNode. An empty rank's front and back are both set to successor's front.
dist_bcastSplitters() [1/2]
template<typename T, unsigned int dim> static std::vector<TreeNode<T,dim> > ot::SFC_Tree< T, dim >::dist_bcastSplitters (const TreeNode< T, dim > * start, MPI_Comm comm) static
Broadcast the first TreeNode from every processor so we have global access to the splitter list.
dist_bcastSplitters() [2/2]
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::dist_bcastSplitters (const TreeNode< T, dim > * start, MPI_Comm globalComm, MPI_Comm activeComm, bool isActive, std::vector< int > & activeList) static
distAdoptAncestors()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distAdoptAncestors (std::vector< TreeNode< T, dim >> & tree, MPI_Comm comm) static
distCoalesceSiblings()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distCoalesceSiblings (std::vector< TreeNode< T, dim >> & tree, MPI_Comm comm) static
If all siblings are leafs, push them onto the last incident rank. (last, not first, so that algorithm is same as distAdoptAncestors).
distCoalesceSiblings()
Enforcing this criterion is a prerequisite to intergrid transfer.
Simpler than keepSiblingLeafsTogether.
distMinimalBalanced()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distMinimalBalanced (std::vector< TreeNode< T, dim >> & tree, double sfc_tol, MPI_Comm comm) static
distMinimalBalancedGlobalSort()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distMinimalBalancedGlobalSort (std::vector< TreeNode< T, dim >> & tree, double sfc_tol, MPI_Comm comm) static
distMinimalComplete()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distMinimalComplete (std::vector< TreeNode< T, dim >> & tree, double sfc_tol, MPI_Comm comm) static
distRemeshSubdomain()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distRemeshSubdomain (const std::vector< TreeNode< T, dim >> & inTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, std::vector< TreeNode< T, dim >> & outTree, double loadFlexibility, MPI_Comm comm) static
distRemeshWholeDomain()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distRemeshWholeDomain (const std::vector< TreeNode< T, dim >> & inTree, const std::vector< OCT_FLAGS::Refine > & refnFlags, std::vector< TreeNode< T, dim >> & outTree, double loadFlexibility, MPI_Comm comm) static
Note
Whichever of the input and output grids is controlling partitioning of the surrogate grid, it is assumed to either be coarser or have coalesced siblings. Old default was SurrogateInByOut .
distRemoveDuplicates()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distRemoveDuplicates (std::vector< TreeNode< T, dim >> & tree, double loadFlexibility, bool strict, MPI_Comm comm) static
Referenced by ot::function2Octree().
distTreeBalancing()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeBalancing (std::vector< TreeNode< T, dim >> & points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm) static
Referenced by ot::DistTree< C, dim >::constructDistTreeByFunc().
distTreeBalancingWithFilter()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeBalancingWithFilter (const ibm::DomainDecider & decider, std::vector< TreeNode< T, dim >> & points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm) static
distTreeConstruction()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeConstruction (std::vector< TreeNode< T, dim >> & points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm) static
distTreeConstructionWithFilter() [1/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeConstructionWithFilter (const ibm::DomainDecider & decider, std::vector< TreeNode< T, dim >> & points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, double loadFlexibility, MPI_Comm comm) static
distTreeConstructionWithFilter() [2/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeConstructionWithFilter (const ibm::DomainDecider & decider, bool refineAll, std::vector< TreeNode< T, dim >> & tree, LevI eLev, double loadFlexibility, MPI_Comm comm) static
distTreePartition() [1/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreePartition (std::vector< TreeNode< T, dim >> & points, unsigned int, double loadFlexibility, MPI_Comm comm) static
distTreePartition() [2/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreePartition (std::vector< TreeNode< T, dim >> & points, double loadFlexibility, MPI_Comm comm) static
distTreeSort()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::distTreeSort (std::vector< TreeNode< T, dim >> & points, double loadFlexibility, MPI_Comm comm) static
Referenced by ot::createRegularOctree().
firstDescendant()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::firstDescendant (TreeNode< T, dim > & parent, RotI & pRot, LevI descendantLev) static
Successively computes 0th child in SFC order to given level.
getContainingBlocks()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::getContainingBlocks (TreeNode< T, dim > * points, RankI begin, RankI end, const TreeNode< T, dim > * splitters, RankI sBegin, RankI sEnd, LevI lev, SFC_State< dim > sfc, int & numPrevBlocks, const int startSize, std::vector< int > & outBlocks) static
Given partition splitters and a list of (unordered) points, finds every block that contains at least some of the points.
Parameters
splitters an array that holds the leading boundary of each block.
Note
Assumes that the points are at the deepest level.
Assumes that the partition splitters are already SFC-sorted.
getSurrogateGrid() [1/2]
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::getSurrogateGrid (RemeshPartition remeshPartition, const std::vector< TreeNode< T, dim >> & oldTree, const std::vector< TreeNode< T, dim >> & newTree, MPI_Comm comm) static
getSurrogateGrid() [2/2]
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::getSurrogateGrid (const std::vector< TreeNode< T, dim >> & replicateGrid, const std::vector< TreeNode< T, dim >> & splittersFromGrid, MPI_Comm comm) static
lastDescendant()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::lastDescendant (TreeNode< T, dim > & parent, RotI & pRot, LevI descendantLev) static
Successively computes (n-1)th child in SFC order to given level.
locCoarsen()
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::locCoarsen (const std::vector< TreeNode< T, dim >> & tree, std::vector< int > && delta_level) static
locCompleteResolved()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locCompleteResolved (const TreeNode< T, dim > * octants, std::vector< TreeNode< T, dim >> & tree, RankI begin, RankI end, SFC_State< dim > sfc, TreeNode< T, dim > pNode) static
locMatchResolution()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locMatchResolution (std::vector< TreeNode< T, dim >> & tree, const std::vector< TreeNode< T, dim >> & res) static
Maintains or expands domain, splitting or coarsening the tree to match the finest level in each leaf subtree of res.
locMinimalBalanced()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locMinimalBalanced (std::vector< TreeNode< T, dim >> & tree) static
Maintains effective domain, splitting octants that violate 2:1-balance.
locRefine()
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::locRefine (const std::vector< TreeNode< T, dim >> & tree, std::vector< int > && delta_level) static
locRemoveDuplicates()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locRemoveDuplicates (std::vector< TreeNode< T, dim >> & tnodes) static
locRemoveDuplicatesStrict()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locRemoveDuplicatesStrict (std::vector< TreeNode< T, dim >> & tnodes) static
locResolveTree()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locResolveTree (std::vector< TreeNode< T, dim >> & tree, std::vector< TreeNode< T, dim >> && res) static
Maintains effective domain, splitting octants larger than res octants.
locTreeBalancing()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locTreeBalancing (std::vector< TreeNode< T, dim >> & points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion) static
locTreeConstruction()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locTreeConstruction (TreeNode< T, dim > * points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode) static
locTreeConstructionWithFilter() [1/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locTreeConstructionWithFilter (const ibm::DomainDecider & decider, TreeNode< T, dim > * points, std::vector< TreeNode< T, dim >> & tree, RankI maxPtsPerRegion, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode) static
locTreeConstructionWithFilter() [2/2]
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::locTreeConstructionWithFilter (const ibm::DomainDecider & decider, bool refineAll, std::vector< TreeNode< T, dim >> & tree, LevI sLev, LevI eLev, SFC_State< dim > sfc, TreeNode< T, dim > pNode) static
locTreeSort() [1/4]
template<typename T, unsigned int dim> template<class PointType > static void ot::SFC_Tree< T, dim >::locTreeSort (std::vector< PointType > & points) inline static
Definition at line 291 of file tsort.h.
References m_uiMaxDepth.
locTreeSort() [2/4]
template<typename T, unsigned int dim> template<class PointType , typename... CompanionT> static void ot::SFC_Tree< T, dim >::locTreeSort (std::vector< PointType > & points, std::vector< CompanionT > &... companions) inline static
Definition at line 298 of file tsort.h.
References m_uiMaxDepth.
locTreeSort() [3/4]
template<typename T, unsigned int dim> template<class PointType > static void ot::SFC_Tree< T, dim >::locTreeSort (PointType * points, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc) static
locTreeSort() [4/4]
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType , bool useCompanions, typename... Companion> static void ot::SFC_Tree< T, dim >::locTreeSort (PointType * points, RankI begin, RankI end, LevI sLev, LevI eLev, SFC_State< dim > sfc, KeyFun keyfun, Companion *... companions) static
locTreeSortInUnitCube()
template<typename T, unsigned int dim> template<class PointType > static void ot::SFC_Tree< T, dim >::locTreeSortInUnitCube (std::vector< PointType > & points) inline static
Definition at line 285 of file tsort.h.
References m_uiMaxDepth.
locTreeSortMaxDepth() [1/2]
template<typename T, unsigned int dim> template<class PointType > static void ot::SFC_Tree< T, dim >::locTreeSortMaxDepth (std::vector< PointType > & points) inline static
Definition at line 317 of file tsort.h.
References m_uiMaxDepth.
locTreeSortMaxDepth() [2/2]
template<typename T, unsigned int dim> template<class PointType , typename... CompanionT> static void ot::SFC_Tree< T, dim >::locTreeSortMaxDepth (std::vector< PointType > & points, std::vector< CompanionT > &... companions) inline static
Definition at line 326 of file tsort.h.
References m_uiMaxDepth, and ot::nchild().
lower_bound()
template<typename T, unsigned int dim> static std::vector<size_t> ot::SFC_Tree< T, dim >::lower_bound (const std::vector< TreeNode< T, dim >> & sortedOcts, const std::vector< TreeNode< T, dim >> & sortedKeys) static
Returns lower bound (rank) of each key relative to sortedOcts, performing all searches simultaneously in a single pass.
propagateNeighbours()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::propagateNeighbours (std::vector< TreeNode< T, dim >> & tree) static
Create auxiliary octants in bottom-up order to close the 2:1-balancing constraint.
removeDescendants()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::removeDescendants (std::vector< TreeNode< T, dim >> & sortedOcts, const std::vector< TreeNode< T, dim >> & sortedKeys) static
Removes octs in sortedOcts that descend from any key in sortedKeys.
removeEqual()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::removeEqual (std::vector< TreeNode< T, dim >> & sortedOcts, const std::vector< TreeNode< T, dim >> & sortedKeys) static
Removes octs in sortedOcts that equal any key in sortedKeys.
retainDescendants()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::retainDescendants (std::vector< TreeNode< T, dim >> & sortedOcts, const std::vector< TreeNode< T, dim >> & sortedKeys) static
Removes octs in sortedOcts that do not descend from any key in sortedKeys.
SFC_bucketing()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::SFC_bucketing (TreeNode< T, dim > * points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, std::array< RankI, 1+nchild(dim)> & outSplitters, RankI & outAncStart, RankI & outAncEnd) static
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush().
SFC_bucketing_general()
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType , bool useCompanions, typename... Companion> static void ot::SFC_Tree< T, dim >::SFC_bucketing_general (PointType * points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> & outSplitters, RankI & outAncStart, RankI & outAncEnd, Companion *... companions) static
SFC_bucketing_impl()
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType > static void ot::SFC_Tree< T, dim >::SFC_bucketing_impl (PointType * points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> & outSplitters, RankI & outAncStart, RankI & outAncEnd) static
Template Parameters
KeyFun KeyType KeyFun::operator()(PointType);
KeyType must support the public interface of TreeNode<T,dim>.
PointType passive data type.
Parameters
ancestorsFirst If true, ancestor bucket precedes all siblings, else follows all siblings.
SFC_bucketStable() [1/2]
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType , typename ValueType > static void ot::SFC_Tree< T, dim >::SFC_bucketStable (const PointType * points, RankI begin, RankI end, LevI lev, KeyFun keyfun, bool separateAncestors, std::array< RankI, nchild(dim)+1 > offsets, const std::array< RankI, nchild(dim)+1 > & bucketEnds, ValueType * values) static
SFC_bucketStable() [2/2]
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType , typename CompanionHead , typename... CompanionTail> static void ot::SFC_Tree< T, dim >::SFC_bucketStable (const PointType * points, RankI begin, RankI end, LevI lev, KeyFun keyfun, bool separateAncestors, const std::array< RankI, nchild(dim)+1 > & offsets, const std::array< RankI, nchild(dim)+1 > & bucketEnds, CompanionHead * companionHead, CompanionTail *... companionTail) static
SFC_locateBuckets()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::SFC_locateBuckets (const TreeNode< T, dim > * points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, std::array< RankI, 1+nchild(dim)> & outSplitters, RankI & outAncStart, RankI & outAncEnd) static
Referenced by ot::MeshLoopImpl< T, dim, TreatSorted >::bucketAndPush(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::Frame(), and ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::SFC_TreeLoop().
SFC_locateBuckets_impl()
template<typename T, unsigned int dim> template<class KeyFun , typename PointType , typename KeyType > static void ot::SFC_Tree< T, dim >::SFC_locateBuckets_impl (const PointType * points, RankI begin, RankI end, LevI lev, SFC_State< dim > sfc, KeyFun keyfun, bool separateAncestors, bool ancestorsFirst, std::array< RankI, 1+nchild(dim)> & outSplitters, RankI & outAncStart, RankI & outAncEnd) static
Template Parameters
KeyFun KeyType KeyFun::operator()(PointType);
KeyType must support the public interface of TreeNode<T,dim>.
PointType passive data type.
Parameters
ancestorsFirst If true, ancestor bucket precedes all siblings, else follows all siblings.
splitParents()
template<typename T, unsigned int dim> static void ot::SFC_Tree< T, dim >::splitParents (std::vector< TreeNode< T, dim >> & tree) static
treeNode2PartitionRank() [1/2]
template<typename T, unsigned int dim> static std::vector<int> ot::SFC_Tree< T, dim >::treeNode2PartitionRank (const std::vector< TreeNode< T, dim >> & treeNodes, const PartitionFront< T, dim > & partitionSplitters) static
Map a set of treeNodes in the domain to the partition ranks that own them. Repeat splitters are allowed. Empty ranks in the partition are allowed.
treeNode2PartitionRank() [2/2]
template<typename T, unsigned int dim> static std::vector<int> ot::SFC_Tree< T, dim >::treeNode2PartitionRank (const std::vector< TreeNode< T, dim >> & treeNodes, const std::vector< TreeNode< T, dim >> & partitionFrontSplitters) static
Map any collection of treeNodes in the domain to the partition ranks that own them. The rank ids are returned in the range [0 .. partitionFrontSplitters.size()-1].
treeNode2PartitionRanks()
template<typename T, unsigned int dim> static std::vector<IntRange<> > ot::SFC_Tree< T, dim >::treeNode2PartitionRanks (const std::vector< TreeNode< T, dim >> & treeNodes, const PartitionFrontBack< T, dim > & partitionSplitters, const std::vector< int > * active) static
Map a set of treeNodes in the domain to ranges of the partition ranks that they overlap. Repeat splitters are allowed. Empty ranks in the partition are allowed. To avoid sending data to inactive ranks, the return indices are relative to the active list.
tsearch_equal_range() [1/2]
template<typename T, unsigned int dim> static std::pair<size_t, size_t> ot::SFC_Tree< T, dim >::tsearch_equal_range (const std::vector< TreeNode< T, dim >> & sortedOcts, const TreeNode< T, dim > & key) static
Find first geq and first greater.
tsearch_equal_range() [2/2]
template<typename T, unsigned int dim> static std::pair<size_t, size_t> ot::SFC_Tree< T, dim >::tsearch_equal_range (const TreeNode< T, dim > * sortedOcts, const TreeNode< T, dim > & key, size_t begin, size_t end, LevI sLev, SFC_State< dim > sfc) static
Find first geq and first greater.
tsearch_lower_bound()
template<typename T, unsigned int dim> static size_t ot::SFC_Tree< T, dim >::tsearch_lower_bound (const std::vector< TreeNode< T, dim >> & sortedOcts, const TreeNode< T, dim > & key) static
Return index to first element not less than key.
tsearch_upper_bound()
template<typename T, unsigned int dim> static size_t ot::SFC_Tree< T, dim >::tsearch_upper_bound (const std::vector< TreeNode< T, dim >> & sortedOcts, const TreeNode< T, dim > & key) static
Return index to first element greater than key.
unstableOctants()
template<typename T, unsigned int dim> static std::vector<TreeNode<T, dim> > ot::SFC_Tree< T, dim >::unstableOctants (const std::vector< TreeNode< T, dim >> & tree, const bool dangerLeft = true, const bool dangerRight = true) static
Assumes sorted balanced tree. Returns octants whose potential neighbors are not strictly contained in the SFC domain spanned by {first..last}.
Member Data Documentation
bucketStableAux
template<typename T, unsigned int dim> std::vector<char> ot::SFC_Tree< T, dim >::bucketStableAux static
Definition at line 418 of file tsort.h.
RM_DUPS_AND_ANC
template<typename T, unsigned int dim> constexpr bool ot::SFC_Tree< T, dim >::RM_DUPS_AND_ANC = false static
Definition at line 713 of file tsort.h.
RM_DUPS_ONLY
template<typename T, unsigned int dim> constexpr bool ot::SFC_Tree< T, dim >::RM_DUPS_ONLY = true static
Definition at line 714 of file tsort.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/tsort.h