DENDRO: par::SendRecvSchedule Struct Reference
par::SendRecvSchedule Struct Reference
#include <parUtils.h>
Public Member Functions
void clear ()
void resize (int npes)
SendRecvSchedule ()=default
SendRecvSchedule (const SendRecvSchedule &)=default
Public Attributes
std::vector< int > rcounts
std::vector< int > rdispls
std::vector< int > scounts
std::vector< int > sdispls
Detailed Description
Definition at line 259 of file parUtils.h.
Constructor & Destructor Documentation
SendRecvSchedule() [1/2]
par::SendRecvSchedule::SendRecvSchedule () default
SendRecvSchedule() [2/2]
par::SendRecvSchedule::SendRecvSchedule (const SendRecvSchedule &) default
Member Function Documentation
clear()
void par::SendRecvSchedule::clear () inline
Definition at line 269 of file parUtils.h.
resize()
void par::SendRecvSchedule::resize (int npes) inline
Definition at line 277 of file parUtils.h.
References par::Mpi_Allreduce(), par::Mpi_Bcast(), par::mpi_comm_rank(), par::mpi_comm_size(), par::Mpi_Exscan(), par::Mpi_Gather(), par::Mpi_Imrecv(), par::Mpi_Irecv(), par::Mpi_Isend(), par::Mpi_Issend(), par::Mpi_Mrecv(), par::Mpi_Recv(), par::Mpi_Reduce(), par::Mpi_Scan(), and par::Mpi_Sendrecv().
Member Data Documentation
rcounts
std::vector<int> par::SendRecvSchedule::rcounts
Definition at line 263 of file parUtils.h.
rdispls
std::vector<int> par::SendRecvSchedule::rdispls
Definition at line 264 of file parUtils.h.
Referenced by par::NbxSynch::disable().
scounts
std::vector<int> par::SendRecvSchedule::scounts
Definition at line 261 of file parUtils.h.
sdispls
std::vector<int> par::SendRecvSchedule::sdispls
Definition at line 262 of file parUtils.h.
Referenced by par::NbxSynch::disable().
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/parUtils.h