DENDRO: ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree Struct Reference
ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree Struct Reference
#include <sfcTreeLoop_matvec_io.h>
Public Member Functions
const TreeNode< unsigned int, dim > & getCurrentSubtree () const
unsigned int getEleOrder () const
const std::vector< bool > & getLeafNodeBdry () const
unsigned int getNdofs () const
const double * getNodeCoords ()
unsigned int getNodesPerElement () const
size_t getNumNodesIn () const
size_t getNumNodesOut () const
size_t getNumNonhangingNodes () const
size_t getNumTreeElements () const
ChildI getSfcChildNum () const
bool isElementBoundary () const
bool isLeaf () const
bool isLeafOrLower () const
void overwriteNodeValsOut (const NodeT *newVals)
void overwriteNodeValsOut (const NodeT *newVals, const char *isDirty)
void overwriteNodeValsOutScalar (const NodeT *newDofs)
const TreeNode< unsigned int, dim > * readNodeCoordsIn () const
const std::vector< bool > & readNodeNonhangingIn () const
const NodeT * readNodeValsOut () const
Public Attributes
MatvecBaseOut & treeloop
Detailed Description
template<unsigned int dim, typename NodeT, bool UseAccumulation>
struct ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree
Definition at line 500 of file sfcTreeLoop_matvec_io.h.
Member Function Documentation
getCurrentSubtree()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const TreeNode<unsigned int, dim>& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getCurrentSubtree () const inline
getCurrentSubtree()
Definition at line 511 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree().
getEleOrder()
template<unsigned int dim, typename NodeT , bool UseAccumulation> unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getEleOrder () const inline
getEleOrder()
Definition at line 600 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder.
getLeafNodeBdry()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const std::vector<bool>& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getLeafNodeBdry () const inline
getLeafNodeBdry()
Definition at line 613 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillLeafNodeBdry, and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_leafNodeBdry.
getNdofs()
template<unsigned int dim, typename NodeT , bool UseAccumulation> unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNdofs () const inline
getNdofs()
Definition at line 597 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs.
getNodeCoords()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const double* ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodeCoords () inline
getNodeCoords()
Definition at line 505 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::fillAccessNodeCoordsFlat(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_accessNodeCoordsFlat.
getNodesPerElement()
template<unsigned int dim, typename NodeT , bool UseAccumulation> unsigned int ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNodesPerElement () const inline
getNodesPerElement()
Definition at line 603 of file sfcTreeLoop_matvec_io.h.
References intPow(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_eleOrder.
getNumNodesIn()
template<unsigned int dim, typename NodeT , bool UseAccumulation> size_t ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNodesIn () const inline
getNumNodesIn()
Definition at line 534 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
getNumNodesOut()
template<unsigned int dim, typename NodeT , bool UseAccumulation> size_t ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNodesOut () const inline
getNumNodesOut()
Definition at line 554 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
getNumNonhangingNodes()
template<unsigned int dim, typename NodeT , bool UseAccumulation> size_t ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumNonhangingNodes () const inline
getNumNonhangingNodes()
Definition at line 539 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
getNumTreeElements()
template<unsigned int dim, typename NodeT , bool UseAccumulation> size_t ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumTreeElements () const inline
getNumTreeElements()
Definition at line 521 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getNumLowerTreeElements(), and ot::MatvecBaseCoords< dim >::AccessSubtree::isLeaf().
getSfcChildNum()
template<unsigned int dim, typename NodeT , bool UseAccumulation> ChildI ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getSfcChildNum () const inline
getSfcChildNum()
Definition at line 516 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getSfcChildNum().
isElementBoundary()
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isElementBoundary () const inline
isElementBoundary()
Definition at line 608 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree(), and ot::TreeNode< T, dim >::getIsOnTreeBdry().
isLeaf()
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isLeaf () const inline
isLeaf()
Definition at line 524 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT , bool UseAccumulation> bool ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::isLeafOrLower () const inline
isLeafOrLower()
Definition at line 529 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::isLeafOrLower().
overwriteNodeValsOut() [1/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOut (const NodeT * newVals) inline
overwriteNodeValsOut()
Definition at line 564 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs.
overwriteNodeValsOut() [2/2]
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOut (const NodeT * newVals, const char * isDirty) inline
overwriteNodeValsOut() with isDirty flags (#flags == #nodes)
Definition at line 574 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs.
overwriteNodeValsOutScalar()
template<unsigned int dim, typename NodeT , bool UseAccumulation> void ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOutScalar (const NodeT * newDofs) inline
overwriteNodeValsOutScalar()
Definition at line 584 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::m_ndofs.
readNodeCoordsIn()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const TreeNode<unsigned int, dim>* ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeCoordsIn () const inline
readNodeCoordsIn()
Definition at line 544 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
readNodeNonhangingIn()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const std::vector<bool>& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeNonhangingIn () const inline
readNodeNonhangingIn()
Definition at line 549 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::getNodeNonhangingIn().
readNodeValsOut()
template<unsigned int dim, typename NodeT , bool UseAccumulation> const NodeT* ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::readNodeValsOut () const inline
readNodeValsOut()
Definition at line 559 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
Member Data Documentation
treeloop
template<unsigned int dim, typename NodeT , bool UseAccumulation> MatvecBaseOut& ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::treeloop
Definition at line 502 of file sfcTreeLoop_matvec_io.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h