DENDRO: ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator Struct Reference
ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator Struct Reference
#include <meshLoop.h>
Public Member Functions
const MeshLoopFrame< T, dim > & getTopConst () const
bool operator!= (const Iterator &other)
const MeshLoopFrame< T, dim > & operator* () const
Iterator & operator++ ()
Public Attributes
bool m_markEnd
MeshLoopInterface_S_NS & m_ref
Detailed Description
template<typename T, unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost>
struct ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator
Definition at line 104 of file meshLoop.h.
Member Function Documentation
getTopConst()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> const MeshLoopFrame<T, dim>& ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::getTopConst () const inline
Definition at line 119 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::getTopConst().
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator*().
operator!=()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator!= (const Iterator & other) inline
Definition at line 111 of file meshLoop.h.
References ot::MeshLoopImpl< T, dim, TreatSorted >::isFinished(), ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::m_markEnd, and ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::m_ref.
operator*()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> const MeshLoopFrame<T, dim>& ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator* () const inline
Definition at line 117 of file meshLoop.h.
References ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::getTopConst().
operator++()
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> Iterator& ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator++ () inline
Definition at line 109 of file meshLoop.h.
References ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::step().
Member Data Documentation
m_markEnd
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> bool ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::m_markEnd
Definition at line 107 of file meshLoop.h.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator!=().
m_ref
template<typename T , unsigned int dim, bool TreatSorted, bool visitEmpty, bool visitPre, bool visitPost> MeshLoopInterface_S_NS& ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::m_ref
Definition at line 106 of file meshLoop.h.
Referenced by ot::MeshLoopInterface_S_NS< T, dim, TreatSorted, visitEmpty, visitPre, visitPost >::Iterator::operator!=().
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/meshLoop.h