DENDRO: ot::SFC_State< dim > Struct Template Reference
ot::SFC_State< dim > Struct Template Reference
#include <tsort.h>
Public Member Functions
SFC_State child_curve (sfc::ChildNum cn) const
sfc::ChildNum child_num (sfc::SubIndex i) const
sfc::SubIndex child_rank (sfc::ChildNum cn) const
SFC_State ()=default
SFC_State (const sfc::RotIndex rotation)
sfc::RotIndex state () const
SFC_State subcurve (sfc::SubIndex i) const
Static Public Member Functions
static constexpr int nchild ()
static SFC_State root ()
Public Attributes
sfc::RotIndex m_rotation = sfc::RotIndex{0}
Detailed Description
template<int dim>
struct ot::SFC_State< dim >
Definition at line 77 of file tsort.h.
Constructor & Destructor Documentation
SFC_State() [1/2]
template<int dim> ot::SFC_State< dim >::SFC_State () default
SFC_State() [2/2]
template<int dim> ot::SFC_State< dim >::SFC_State (const sfc::RotIndex rotation) inline
Definition at line 84 of file tsort.h.
Member Function Documentation
child_curve()
template<int dim> SFC_State< dim > ot::SFC_State< dim >::child_curve (sfc::ChildNum cn) const inline
Definition at line 111 of file tsort.h.
References HILBERT_TABLE, and ot::nchild().
Referenced by ot::dld(), and ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::step().
child_num()
template<int dim> sfc::ChildNum ot::SFC_State< dim >::child_num (sfc::SubIndex i) const inline
Definition at line 99 of file tsort.h.
References ot::nchild(), and rotations.
Referenced by ot::MatvecBase< dim, NodeT >::bottomUpNodes(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::bottomUpNodes(), ot::dld(), ot::SFC_TreeLoop< dim, Inputs< TreeNode< unsigned int, dim >, NodeT, bool >, Outputs<>, MatvecBaseSummary< dim >, MatvecBaseIn< dim, NodeT, p2c > >::step(), ot::MatvecBaseCoords< dim >::topDownNodes(), ot::MatvecBase< dim, NodeT >::topDownNodes(), ot::MatvecBaseIn< dim, NodeT, p2c >::topDownNodes(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::topDownNodes().
child_rank()
template<int dim> sfc::SubIndex ot::SFC_State< dim >::child_rank (sfc::ChildNum cn) const inline
Definition at line 105 of file tsort.h.
References ot::nchild(), and rotations.
nchild()
template<int dim> static constexpr int ot::SFC_State< dim >::nchild () inline static
Definition at line 79 of file tsort.h.
root()
template<int dim> static SFC_State ot::SFC_State< dim >::root () inline static
Definition at line 80 of file tsort.h.
state()
template<int dim> sfc::RotIndex ot::SFC_State< dim >::state () const inline
Definition at line 87 of file tsort.h.
subcurve()
template<int dim> SFC_State< dim > ot::SFC_State< dim >::subcurve (sfc::SubIndex i) const inline
Definition at line 117 of file tsort.h.
Member Data Documentation
m_rotation
template<int dim> sfc::RotIndex ot::SFC_State< dim >::m_rotation = sfc::RotIndex{0}
Definition at line 94 of file tsort.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/tsort.h