DENDRO: par::P2PPartners Struct Reference
par::P2PPartners Struct Reference
#include <p2p.h>
Public Member Functions
MPI_Comm comm () const
int comm_rank () const
int comm_size () const
int dest (size_t i) const
void dest (size_t i, int d)
size_t nDest () const
void nDest (size_t size)
size_t nSrc () const
void nSrc (size_t size)
P2PPartners ()=default
P2PPartners (const std::vector< int > &dest, const std::vector< int > &src, MPI_Comm comm)
void reserve (size_t ndest, size_t nsrc)
void reset (size_t ndest, size_t nsrc, MPI_Comm comm)
int src (size_t i) const
void src (size_t i, int s)
Public Attributes
MPI_Comm m_comm
int m_comm_rank
int m_comm_size
std::vector< int > m_dest
std::vector< int > m_src
Detailed Description
Definition at line 18 of file p2p.h.
Constructor & Destructor Documentation
P2PPartners() [1/2]
par::P2PPartners::P2PPartners () default
P2PPartners() [2/2]
par::P2PPartners::P2PPartners (const std::vector< int > & dest, const std::vector< int > & src, MPI_Comm comm)
Member Function Documentation
comm()
MPI_Comm par::P2PPartners::comm () const inline
Referenced by par::P2PScalar< ScalarT, LEN >::comm(), par::P2PScalar< ScalarT, LEN >::recv_all(), and par::P2PScalar< ScalarT, LEN >::send().
comm_rank()
int par::P2PPartners::comm_rank () const inline
comm_size()
int par::P2PPartners::comm_size () const inline
dest() [1/2]
int par::P2PPartners::dest (size_t i) const inline
Referenced by par::P2PScalar< ScalarT, LEN >::dest(), and par::P2PScalar< ScalarT, LEN >::send().
dest() [2/2]
void par::P2PPartners::dest (size_t i, int d) inline
nDest() [1/2]
size_t par::P2PPartners::nDest () const inline
Referenced by par::P2PMeta::P2PMeta(), par::P2PScalar< ScalarT, LEN >::reset(), and par::P2PScalar< ScalarT, LEN >::send().
nDest() [2/2]
void par::P2PPartners::nDest (size_t size) inline
nSrc() [1/2]
size_t par::P2PPartners::nSrc () const inline
Referenced by par::P2PMeta::P2PMeta(), par::P2PScalar< ScalarT, LEN >::recv_all(), and par::P2PScalar< ScalarT, LEN >::reset().
nSrc() [2/2]
void par::P2PPartners::nSrc (size_t size) inline
reserve()
void par::P2PPartners::reserve (size_t ndest, size_t nsrc)
Referenced by par::P2PMeta::P2PMeta().
reset()
void par::P2PPartners::reset (size_t ndest, size_t nsrc, MPI_Comm comm)
Referenced by par::P2PMeta::P2PMeta(), and par::P2PScalar< ScalarT, LEN >::P2PScalar().
src() [1/2]
int par::P2PPartners::src (size_t i) const inline
Referenced by par::P2PScalar< ScalarT, LEN >::recv_all(), and par::P2PScalar< ScalarT, LEN >::src().
src() [2/2]
void par::P2PPartners::src (size_t i, int s) inline
Member Data Documentation
m_comm
MPI_Comm par::P2PPartners::m_comm
Definition at line 22 of file p2p.h.
Referenced by par::P2PVector< X >::recv(), and par::P2PVector< X >::send().
m_comm_rank
int par::P2PPartners::m_comm_rank
Definition at line 24 of file p2p.h.
m_comm_size
int par::P2PPartners::m_comm_size
Definition at line 23 of file p2p.h.
m_dest
std::vector<int> par::P2PPartners::m_dest
Definition at line 20 of file p2p.h.
m_src
std::vector<int> par::P2PPartners::m_src
Definition at line 21 of file p2p.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/p2p.h