DENDRO: ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree Struct Reference
ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree Struct Reference
#include <sfcTreeLoop_matvec_io.h>
Public Member Functions
const TreeNode< unsigned int, dim > & getCurrentSubtree () const
unsigned int getEleOrder () const
const std::vector< bool > & getLeafNodeBdry () const
unsigned int getNdofs () const
const double * getNodeCoords () const
unsigned int getNodesPerElement () const
size_t getNumNodesIn () const
size_t getNumNonhangingNodes () const
size_t getNumTreeElements () const
ChildI getSfcChildNum () const
bool isElementBoundary () const
bool isLeaf () const
bool isLeafOrLower () const
void overwriteNodeValsIn (const NodeT *newVals)
const TreeNode< unsigned int, dim > * readNodeCoordsIn () const
const std::vector< bool > & readNodeNonhangingIn () const
const NodeT * readNodeValsIn () const
Public Attributes
MatvecBaseIn & treeloop
Detailed Description
template<unsigned int dim, typename NodeT, bool p2c = true>
struct ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree
Definition at line 308 of file sfcTreeLoop_matvec_io.h.
Member Function Documentation
getCurrentSubtree()
template<unsigned int dim, typename NodeT , bool p2c = true> const TreeNode<unsigned int, dim>& ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getCurrentSubtree () const inline
getCurrentSubtree()
Definition at line 319 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree().
getEleOrder()
template<unsigned int dim, typename NodeT , bool p2c = true> unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getEleOrder () const inline
getEleOrder()
Definition at line 377 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::m_eleOrder.
getLeafNodeBdry()
template<unsigned int dim, typename NodeT , bool p2c = true> const std::vector<bool>& ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getLeafNodeBdry () const inline
getLeafNodeBdry()
Definition at line 390 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::fillLeafNodeBdry, and ot::MatvecBaseIn< dim, NodeT, p2c >::m_leafNodeBdry.
getNdofs()
template<unsigned int dim, typename NodeT , bool p2c = true> unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNdofs () const inline
getNdofs()
Definition at line 374 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::m_ndofs.
getNodeCoords()
template<unsigned int dim, typename NodeT , bool p2c = true> const double* ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodeCoords () const inline
getNodeCoords()
Definition at line 313 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::fillAccessNodeCoordsFlat(), and ot::MatvecBaseIn< dim, NodeT, p2c >::m_accessNodeCoordsFlat.
getNodesPerElement()
template<unsigned int dim, typename NodeT , bool p2c = true> unsigned int ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNodesPerElement () const inline
getNodesPerElement()
Definition at line 380 of file sfcTreeLoop_matvec_io.h.
References intPow(), and ot::MatvecBaseIn< dim, NodeT, p2c >::m_eleOrder.
getNumNodesIn()
template<unsigned int dim, typename NodeT , bool p2c = true> size_t ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumNodesIn () const inline
getNumNodesIn()
Definition at line 342 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
getNumNonhangingNodes()
template<unsigned int dim, typename NodeT , bool p2c = true> size_t ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumNonhangingNodes () const inline
getNumNonhangingNodes()
Definition at line 347 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
getNumTreeElements()
template<unsigned int dim, typename NodeT , bool p2c = true> size_t ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumTreeElements () const inline
getNumTreeElements()
Definition at line 329 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getNumLowerTreeElements(), and ot::MatvecBaseCoords< dim >::AccessSubtree::isLeaf().
getSfcChildNum()
template<unsigned int dim, typename NodeT , bool p2c = true> ChildI ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getSfcChildNum () const inline
getSfcChildNum()
Definition at line 324 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getSfcChildNum().
isElementBoundary()
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isElementBoundary () const inline
isElementBoundary()
Definition at line 385 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree(), and ot::TreeNode< T, dim >::getIsOnTreeBdry().
isLeaf()
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isLeaf () const inline
isLeaf()
Definition at line 332 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT , bool p2c = true> bool ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::isLeafOrLower () const inline
isLeafOrLower()
Definition at line 337 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseIn< dim, NodeT, p2c >::isLeafOrLower().
overwriteNodeValsIn()
template<unsigned int dim, typename NodeT , bool p2c = true> void ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::overwriteNodeValsIn (const NodeT * newVals) inline
overwriteNodeValsIn()
Definition at line 367 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn(), and ot::MatvecBaseIn< dim, NodeT, p2c >::m_ndofs.
readNodeCoordsIn()
template<unsigned int dim, typename NodeT , bool p2c = true> const TreeNode<unsigned int, dim>* ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeCoordsIn () const inline
readNodeCoordsIn()
Definition at line 352 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
readNodeNonhangingIn()
template<unsigned int dim, typename NodeT , bool p2c = true> const std::vector<bool>& ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeNonhangingIn () const inline
readNodeNonhangingIn()
Definition at line 362 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::MatvecBaseIn< dim, NodeT, p2c >::getNodeNonhangingIn().
readNodeValsIn()
template<unsigned int dim, typename NodeT , bool p2c = true> const NodeT* ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::readNodeValsIn () const inline
readNodeValsIn()
Definition at line 357 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
Member Data Documentation
treeloop
template<unsigned int dim, typename NodeT , bool p2c = true> MatvecBaseIn& ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::treeloop
Definition at line 310 of file sfcTreeLoop_matvec_io.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h