DENDRO: par::P2PScalar< ScalarT, LEN > Struct Template Reference
par::P2PScalar< ScalarT, LEN > Struct Template Reference
#include <p2p.h>
Public Types
using Request = P2PRequest< P2PScalar >
Public Member Functions
MPI_Comm comm () const
int dest (size_t i) const
P2PScalar ()=default
P2PScalar (const P2PPartners *partners)
template<int IDX = 0>
ScalarT recv (int srcIdx)
template<typename... X>
void recv_all (int srcIdx, X &...scalars)
void reserve (int ndest, int nsrc)
void reset (const P2PPartners *partners)
template<typename... X>
void send (int destIdx, const X &...scalars)
int src (size_t i) const
void wait_all ()
Public Attributes
const P2PPartners * m_partners = nullptr
std::vector< char > m_rcvd
std::vector< ScalarT > m_recvScalar
std::vector< Request > m_requests
std::vector< ScalarT > m_sendScalar
std::vector< char > m_sent
Detailed Description
template<typename ScalarT = int, int LEN = 1>
struct par::P2PScalar< ScalarT, LEN >
Definition at line 64 of file p2p.h.
Member Typedef Documentation
Request
template<typename ScalarT = int, int LEN = 1> using par::P2PScalar< ScalarT, LEN >::Request = P2PRequest<P2PScalar>
Definition at line 66 of file p2p.h.
Constructor & Destructor Documentation
P2PScalar() [1/2]
template<typename ScalarT = int, int LEN = 1> par::P2PScalar< ScalarT, LEN >::P2PScalar () default
P2PScalar() [2/2]
template<typename ScalarT = int, int LEN = 1> par::P2PScalar< ScalarT, LEN >::P2PScalar (const P2PPartners * partners) inline
Definition at line 92 of file p2p.h.
References par::P2PPartners::reset().
Member Function Documentation
comm()
template<typename ScalarT = int, int LEN = 1> MPI_Comm par::P2PScalar< ScalarT, LEN >::comm () const inline
Definition at line 70 of file p2p.h.
References par::P2PPartners::comm().
dest()
template<typename ScalarT = int, int LEN = 1> int par::P2PScalar< ScalarT, LEN >::dest (size_t i) const inline
Definition at line 71 of file p2p.h.
References par::P2PPartners::dest().
recv()
template<typename ScalarT = int, int LEN = 1> template<int IDX = 0> ScalarT par::P2PScalar< ScalarT, LEN >::recv (int srcIdx) inline
Definition at line 132 of file p2p.h.
recv_all()
template<typename ScalarT = int, int LEN = 1> template<typename... X> void par::P2PScalar< ScalarT, LEN >::recv_all (int srcIdx, X &... scalars) inline
Definition at line 120 of file p2p.h.
References par::P2PPartners::comm(), DENDRO_FOR_PACK, par::Mpi_Recv(), par::P2PPartners::nSrc(), and par::P2PPartners::src().
reserve()
template<typename ScalarT = int, int LEN = 1> void par::P2PScalar< ScalarT, LEN >::reserve (int ndest, int nsrc) inline
Definition at line 80 of file p2p.h.
reset()
template<typename ScalarT = int, int LEN = 1> void par::P2PScalar< ScalarT, LEN >::reset (const P2PPartners * partners) inline
Definition at line 94 of file p2p.h.
References par::P2PPartners::nDest(), and par::P2PPartners::nSrc().
send()
template<typename ScalarT = int, int LEN = 1> template<typename... X> void par::P2PScalar< ScalarT, LEN >::send (int destIdx, const X &... scalars) inline
Definition at line 108 of file p2p.h.
References par::P2PPartners::comm(), DENDRO_FOR_PACK, par::P2PPartners::dest(), par::Mpi_Isend(), and par::P2PPartners::nDest().
src()
template<typename ScalarT = int, int LEN = 1> int par::P2PScalar< ScalarT, LEN >::src (size_t i) const inline
Definition at line 72 of file p2p.h.
References par::P2PPartners::src().
wait_all()
template<typename ScalarT = int, int LEN = 1> void par::P2PScalar< ScalarT, LEN >::wait_all () inline
Definition at line 137 of file p2p.h.
Member Data Documentation
m_partners
template<typename ScalarT = int, int LEN = 1> const P2PPartners* par::P2PScalar< ScalarT, LEN >::m_partners = nullptr
Definition at line 69 of file p2p.h.
m_rcvd
template<typename ScalarT = int, int LEN = 1> std::vector<char> par::P2PScalar< ScalarT, LEN >::m_rcvd
Definition at line 78 of file p2p.h.
m_recvScalar
template<typename ScalarT = int, int LEN = 1> std::vector<ScalarT> par::P2PScalar< ScalarT, LEN >::m_recvScalar
Definition at line 75 of file p2p.h.
m_requests
template<typename ScalarT = int, int LEN = 1> std::vector<Request> par::P2PScalar< ScalarT, LEN >::m_requests
Definition at line 76 of file p2p.h.
m_sendScalar
template<typename ScalarT = int, int LEN = 1> std::vector<ScalarT> par::P2PScalar< ScalarT, LEN >::m_sendScalar
Definition at line 74 of file p2p.h.
m_sent
template<typename ScalarT = int, int LEN = 1> std::vector<char> par::P2PScalar< ScalarT, LEN >::m_sent
Definition at line 77 of file p2p.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/p2p.h