DENDRO: par::NbxSynch Struct Reference
par::NbxSynch Struct Reference
#include <parUtils.h>
Static Public Member Functions
static NbxSynch disable ()
static NbxSynch enable (MPI_Request *ptr)
Public Attributes
bool const enabled
MPI_Request *const ptr
Detailed Description
Definition at line 441 of file parUtils.h.
Member Function Documentation
disable()
static NbxSynch par::NbxSynch::disable () inline static
Definition at line 446 of file parUtils.h.
References par::bitonicSort(), par::bitonicSort_binary(), par::concatenate(), par::dbg_printTNList(), par::defaultWeight(), DendroIntL, par::loadImbalance(), par::maxLowerBound(), par::MergeLists(), par::MergeSplit(), par::Mpi_Allgather(), par::Mpi_Allgatherv(), par::Mpi_Alltoallv_dense(), par::Mpi_Alltoallv_Kway(), par::Mpi_Alltoallv_sparse(), par::Mpi_NBX(), par::Mpi_NBX_neighbors(), par::Mpi_NBX_sizes(), par::mpi_next_if(), par::Par_bitonic_merge_incr(), par::Par_bitonic_sort_decr(), par::Par_bitonic_sort_incr(), par::partitionW(), par::SendRecvSchedule::rdispls, par::scatterValues(), par::SendRecvSchedule::sdispls, par::sendAll(), par::shift(), par::splitComm2way(), par::splitCommBinary(), par::splitCommBinaryNoFlip(), par::splitCommUsingSplittingRank(), and par::waitForDebugger().
enable()
static NbxSynch par::NbxSynch::enable (MPI_Request * ptr) inline static
Definition at line 445 of file parUtils.h.
Member Data Documentation
enabled
bool const par::NbxSynch::enabled
Definition at line 443 of file parUtils.h.
ptr
MPI_Request* const par::NbxSynch::ptr
Definition at line 444 of file parUtils.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/parUtils.h