DENDRO: ot::MatvecBaseCoords< dim >::AccessSubtree Struct Reference
ot::MatvecBaseCoords< dim >::AccessSubtree Struct Reference
#include <sfcTreeLoop_matvec_io.h>
Public Member Functions
const TreeNode< unsigned int, dim > & getCurrentSubtree () const
unsigned int getEleOrder () const
const std::vector< bool > & getLeafNodeBdry () const
const double * getNodeCoords () const
unsigned int getNodesPerElement () const
size_t getNumNodesIn () const
size_t getNumNonhangingNodes () const
size_t getNumTreeElements () const
ChildI getSfcChildNum () const
bool isElementBoundary () const
bool isLeaf () const
bool isLeafOrLower () const
const TreeNode< unsigned int, dim > * readNodeCoordsIn () const
const std::vector< bool > & readNodeNonhangingIn () const
Public Attributes
MatvecBaseCoords & treeloop
Detailed Description
template<unsigned int dim>
struct ot::MatvecBaseCoords< dim >::AccessSubtree
Definition at line 140 of file sfcTreeLoop_matvec_io.h.
Member Function Documentation
getCurrentSubtree()
template<unsigned int dim> const TreeNode<unsigned int, dim>& ot::MatvecBaseCoords< dim >::AccessSubtree::getCurrentSubtree () const inline
getCurrentSubtree()
Definition at line 151 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree().
getEleOrder()
template<unsigned int dim> unsigned int ot::MatvecBaseCoords< dim >::AccessSubtree::getEleOrder () const inline
getEleOrder()
Definition at line 194 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::m_eleOrder.
getLeafNodeBdry()
template<unsigned int dim> const std::vector<bool>& ot::MatvecBaseCoords< dim >::AccessSubtree::getLeafNodeBdry () const inline
getLeafNodeBdry()
Definition at line 207 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::fillLeafNodeBdry, and ot::MatvecBaseCoords< dim >::m_leafNodeBdry.
getNodeCoords()
template<unsigned int dim> const double* ot::MatvecBaseCoords< dim >::AccessSubtree::getNodeCoords () const inline
getNodeCoords()
Definition at line 145 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::fillAccessNodeCoordsFlat(), and ot::MatvecBaseCoords< dim >::m_accessNodeCoordsFlat.
getNodesPerElement()
template<unsigned int dim> unsigned int ot::MatvecBaseCoords< dim >::AccessSubtree::getNodesPerElement () const inline
getNodesPerElement()
Definition at line 197 of file sfcTreeLoop_matvec_io.h.
References intPow(), and ot::MatvecBaseCoords< dim >::m_eleOrder.
getNumNodesIn()
template<unsigned int dim> size_t ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNodesIn () const inline
getNumNodesIn()
Definition at line 174 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
Referenced by ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::overwriteNodeValsIn(), ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOut(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::overwriteNodeValsOutScalar().
getNumNonhangingNodes()
template<unsigned int dim> size_t ot::MatvecBaseCoords< dim >::AccessSubtree::getNumNonhangingNodes () const inline
getNumNonhangingNodes()
Definition at line 179 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
getNumTreeElements()
template<unsigned int dim> size_t ot::MatvecBaseCoords< dim >::AccessSubtree::getNumTreeElements () const inline
getNumTreeElements()
Definition at line 161 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getNumLowerTreeElements(), and ot::MatvecBaseCoords< dim >::AccessSubtree::isLeaf().
getSfcChildNum()
template<unsigned int dim> ChildI ot::MatvecBaseCoords< dim >::AccessSubtree::getSfcChildNum () const inline
getSfcChildNum()
Definition at line 156 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::getSfcChildNum().
isElementBoundary()
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::AccessSubtree::isElementBoundary () const inline
isElementBoundary()
Definition at line 202 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree(), and ot::TreeNode< T, dim >::getIsOnTreeBdry().
isLeaf()
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::AccessSubtree::isLeaf () const inline
isLeaf()
Definition at line 164 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::isLeaf().
Referenced by ot::MatvecBaseCoords< dim >::AccessSubtree::getNumTreeElements(), ot::MatvecBaseIn< dim, NodeT, p2c >::AccessSubtree::getNumTreeElements(), and ot::MatvecBaseOut< dim, NodeT, UseAccumulation >::AccessSubtree::getNumTreeElements().
isLeafOrLower()
template<unsigned int dim> bool ot::MatvecBaseCoords< dim >::AccessSubtree::isLeafOrLower () const inline
isLeafOrLower()
Definition at line 169 of file sfcTreeLoop_matvec_io.h.
References ot::MatvecBaseCoords< dim >::isLeafOrLower().
readNodeCoordsIn()
template<unsigned int dim> const TreeNode<unsigned int, dim>* ot::MatvecBaseCoords< dim >::AccessSubtree::readNodeCoordsIn () const inline
readNodeCoordsIn()
Definition at line 184 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
readNodeNonhangingIn()
template<unsigned int dim> const std::vector<bool>& ot::MatvecBaseCoords< dim >::AccessSubtree::readNodeNonhangingIn () const inline
readNodeNonhangingIn()
Definition at line 189 of file sfcTreeLoop_matvec_io.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::MatvecBaseCoords< dim >::getNodeNonhangingIn().
Member Data Documentation
treeloop
template<unsigned int dim> MatvecBaseCoords& ot::MatvecBaseCoords< dim >::AccessSubtree::treeloop
Definition at line 142 of file sfcTreeLoop_matvec_io.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec_io.h