DENDRO: par::P2PMeta Struct Reference
par::P2PMeta Struct Reference
#include <p2p.h>
Public Types
using Request = P2PRequest< P2PMeta >
Public Member Functions
long long unsigned bytes_rcvd () const
long long unsigned bytes_sent () const
MPI_Comm comm () const
int dest (size_t i) const
P2PMeta ()=default
P2PMeta (const P2PPartners *partners, int layers=1)
template<typename X >
void recv (X *recv_buffer)
template<typename X >
void recv_dofs (X *recv_buffer, const int ndofs)
int * recv_offsets ()
void recv_size (int srcIdx, int size)
int * recv_sizes ()
int recv_total () const
void reserve (int ndest, int nsrc, int layers=1)
void reset (const P2PPartners *partners)
void schedule_send (int destIdx, int size, int offset)
int self_offset () const
int self_size () const
void self_size (int srcIdx, int size)
template<typename X >
void send (const X *send_buffer)
template<typename X >
void send_dofs (const X *send_buffer, const int ndofs)
int * send_offsets ()
int * send_sizes ()
int src (size_t i) const
void tally_recvs ()
void wait_all ()
Public Attributes
long long unsigned m_bytes_rcvd = 0
long long unsigned m_bytes_sent = 0
const P2PPartners * m_partners = nullptr
std::vector< int > m_recv_meta
int m_recv_tag = 0
int m_recv_total = 0
std::vector< Request > m_requests
int m_self_offset = 0
int m_self_pos = 0
int m_self_size = 0
std::vector< int > m_send_meta
int m_send_tag = 0
Detailed Description
Definition at line 180 of file p2p.h.
Member Typedef Documentation
Request
using par::P2PMeta::Request = P2PRequest<P2PMeta>
Definition at line 184 of file p2p.h.
Constructor & Destructor Documentation
P2PMeta() [1/2]
par::P2PMeta::P2PMeta () default
P2PMeta() [2/2]
par::P2PMeta::P2PMeta (const P2PPartners * partners, int layers = 1) inline
Definition at line 220 of file p2p.h.
References par::P2PPartners::nDest(), par::P2PPartners::nSrc(), par::P2PPartners::reserve(), and par::P2PPartners::reset().
Member Function Documentation
bytes_rcvd()
long long unsigned par::P2PMeta::bytes_rcvd () const inline
bytes_sent()
long long unsigned par::P2PMeta::bytes_sent () const inline
comm()
MPI_Comm par::P2PMeta::comm () const inline
dest()
int par::P2PMeta::dest (size_t i) const inline
recv()
template<typename X > void par::P2PMeta::recv (X * recv_buffer)
recv_dofs()
template<typename X > void par::P2PMeta::recv_dofs (X * recv_buffer, const int ndofs)
recv_offsets()
int* par::P2PMeta::recv_offsets () inline
recv_size()
void par::P2PMeta::recv_size (int srcIdx, int size) inline
Definition at line 234 of file p2p.h.
recv_sizes()
int* par::P2PMeta::recv_sizes () inline
recv_total()
int par::P2PMeta::recv_total () const inline
reserve()
void par::P2PMeta::reserve (int ndest, int nsrc, int layers = 1)
reset()
void par::P2PMeta::reset (const P2PPartners * partners)
schedule_send()
void par::P2PMeta::schedule_send (int destIdx, int size, int offset) inline
Definition at line 229 of file p2p.h.
self_offset()
int par::P2PMeta::self_offset () const inline
self_size() [1/2]
int par::P2PMeta::self_size () const inline
self_size() [2/2]
void par::P2PMeta::self_size (int srcIdx, int size) inline
Definition at line 238 of file p2p.h.
send()
template<typename X > void par::P2PMeta::send (const X * send_buffer)
send_dofs()
template<typename X > void par::P2PMeta::send_dofs (const X * send_buffer, const int ndofs)
send_offsets()
int* par::P2PMeta::send_offsets () inline
send_sizes()
int* par::P2PMeta::send_sizes () inline
src()
int par::P2PMeta::src (size_t i) const inline
tally_recvs()
void par::P2PMeta::tally_recvs ()
wait_all()
void par::P2PMeta::wait_all ()
Member Data Documentation
m_bytes_rcvd
long long unsigned par::P2PMeta::m_bytes_rcvd = 0
Definition at line 199 of file p2p.h.
m_bytes_sent
long long unsigned par::P2PMeta::m_bytes_sent = 0
Definition at line 198 of file p2p.h.
m_partners
const P2PPartners* par::P2PMeta::m_partners = nullptr
Definition at line 182 of file p2p.h.
m_recv_meta
std::vector<int> par::P2PMeta::m_recv_meta
Definition at line 187 of file p2p.h.
m_recv_tag
int par::P2PMeta::m_recv_tag = 0
Definition at line 196 of file p2p.h.
m_recv_total
int par::P2PMeta::m_recv_total = 0
Definition at line 189 of file p2p.h.
m_requests
std::vector<Request> par::P2PMeta::m_requests
Definition at line 188 of file p2p.h.
m_self_offset
int par::P2PMeta::m_self_offset = 0
Definition at line 192 of file p2p.h.
m_self_pos
int par::P2PMeta::m_self_pos = 0
Definition at line 193 of file p2p.h.
m_self_size
int par::P2PMeta::m_self_size = 0
Definition at line 191 of file p2p.h.
m_send_meta
std::vector<int> par::P2PMeta::m_send_meta
Definition at line 186 of file p2p.h.
m_send_tag
int par::P2PMeta::m_send_tag = 0
Definition at line 195 of file p2p.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/p2p.h