DENDRO: ot::MatvecBase< dim, NodeT >::AccessSubtree Struct Reference
ot::MatvecBase< dim, NodeT >::AccessSubtree Struct Reference
#include <sfcTreeLoop_matvec.h>
Public Member Functions
const TreeNode< unsigned int, dim > & getCurrentSubtree () const
unsigned int getEleOrder () const
const std::vector< bool > & getLeafNodeBdry () const
unsigned int getNdofs () const
const double * getNodeCoords ()
unsigned int getNodesPerElement () const
size_t getNumNodesIn () const
size_t getNumNodesOut () const
size_t getNumNonhangingNodes () const
bool isElementBoundary () const
bool isLeaf () const
bool isLeafOrLower () const
void overwriteNodeValsIn (const NodeT *newVals)
void overwriteNodeValsOut (const NodeT *newVals)
const TreeNode< unsigned int, dim > * readNodeCoordsIn () const
const NodeT * readNodeValsIn () const
const NodeT * readNodeValsOut () const
Public Attributes
MatvecBase & treeloop
Detailed Description
template<unsigned int dim, typename NodeT>
struct ot::MatvecBase< dim, NodeT >::AccessSubtree
Definition at line 133 of file sfcTreeLoop_matvec.h.
Member Function Documentation
getCurrentSubtree()
template<unsigned int dim, typename NodeT > const TreeNode<unsigned int, dim>& ot::MatvecBase< dim, NodeT >::AccessSubtree::getCurrentSubtree () const inline
getCurrentSubtree()
Definition at line 144 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree().
getEleOrder()
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::AccessSubtree::getEleOrder () const inline
getEleOrder()
Definition at line 206 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::m_eleOrder.
getLeafNodeBdry()
template<unsigned int dim, typename NodeT > const std::vector<bool>& ot::MatvecBase< dim, NodeT >::AccessSubtree::getLeafNodeBdry () const inline
getLeafNodeBdry()
Definition at line 219 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::fillLeafNodeBdry(), and ot::MatvecBase< dim, NodeT >::m_leafNodeBdry.
getNdofs()
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::AccessSubtree::getNdofs () const inline
getNdofs()
Definition at line 203 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::m_ndofs.
getNodeCoords()
template<unsigned int dim, typename NodeT > const double* ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodeCoords () inline
getNodeCoords()
Definition at line 138 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::fillAccessNodeCoordsFlat(), and ot::MatvecBase< dim, NodeT >::m_accessNodeCoordsFlat.
getNodesPerElement()
template<unsigned int dim, typename NodeT > unsigned int ot::MatvecBase< dim, NodeT >::AccessSubtree::getNodesPerElement () const inline
getNodesPerElement()
Definition at line 209 of file sfcTreeLoop_matvec.h.
References intPow(), and ot::MatvecBase< dim, NodeT >::m_eleOrder.
getNumNodesIn()
template<unsigned int dim, typename NodeT > size_t ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNodesIn () const inline
getNumNodesIn()
Definition at line 159 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
getNumNodesOut()
template<unsigned int dim, typename NodeT > size_t ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNodesOut () const inline
getNumNodesOut()
Definition at line 179 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
getNumNonhangingNodes()
template<unsigned int dim, typename NodeT > size_t ot::MatvecBase< dim, NodeT >::AccessSubtree::getNumNonhangingNodes () const inline
getNumNonhangingNodes()
Definition at line 164 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::Frame< dim, InputTypes, OutputTypes, SummaryType, ConcreteTreeLoop >::mySummaryHandle.
isElementBoundary()
template<unsigned int dim, typename NodeT > bool ot::MatvecBase< dim, NodeT >::AccessSubtree::isElementBoundary () const inline
isElementBoundary()
Definition at line 214 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentSubtree(), and ot::TreeNode< T, dim >::getIsOnTreeBdry().
isLeaf()
template<unsigned int dim, typename NodeT > bool ot::MatvecBase< dim, NodeT >::AccessSubtree::isLeaf () const inline
isLeaf()
Definition at line 149 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::isLeaf().
isLeafOrLower()
template<unsigned int dim, typename NodeT > bool ot::MatvecBase< dim, NodeT >::AccessSubtree::isLeafOrLower () const inline
isLeafOrLower()
Definition at line 154 of file sfcTreeLoop_matvec.h.
References ot::MatvecBase< dim, NodeT >::isLeafOrLower().
overwriteNodeValsIn()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsIn (const NodeT * newVals) inline
overwriteNodeValsIn()
Definition at line 189 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::MatvecBase< dim, NodeT >::m_ndofs.
overwriteNodeValsOut()
template<unsigned int dim, typename NodeT > void ot::MatvecBase< dim, NodeT >::AccessSubtree::overwriteNodeValsOut (const NodeT * newVals) inline
overwriteNodeValsOut()
Definition at line 195 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame(), and ot::MatvecBase< dim, NodeT >::m_ndofs.
readNodeCoordsIn()
template<unsigned int dim, typename NodeT > const TreeNode<unsigned int, dim>* ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeCoordsIn () const inline
readNodeCoordsIn()
Definition at line 169 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
readNodeValsIn()
template<unsigned int dim, typename NodeT > const NodeT* ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeValsIn () const inline
readNodeValsIn()
Definition at line 174 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
readNodeValsOut()
template<unsigned int dim, typename NodeT > const NodeT* ot::MatvecBase< dim, NodeT >::AccessSubtree::readNodeValsOut () const inline
readNodeValsOut()
Definition at line 184 of file sfcTreeLoop_matvec.h.
References ot::SFC_TreeLoop< dim, InputTypes, OutputTypes, SummaryType, ConcreteType >::getCurrentFrame().
Member Data Documentation
treeloop
template<unsigned int dim, typename NodeT > MatvecBase& ot::MatvecBase< dim, NodeT >::AccessSubtree::treeloop
Definition at line 135 of file sfcTreeLoop_matvec.h.
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/sfcTreeLoop_matvec.h