DENDRO: ot::OctreeAdler32 Struct Reference
ot::OctreeAdler32 Struct Reference
#include <octUtils.h>
Public Member Functions
OctreeAdler32 operator+ (const OctreeAdler32 &that) const
bool operator== (const OctreeAdler32 &that) const
Public Attributes
long unsigned code = adler32(0L, Z_NULL, 0)
size_t len = 0u
Detailed Description
Definition at line 1153 of file octUtils.h.
Member Function Documentation
operator+()
OctreeAdler32 ot::OctreeAdler32::operator+ (const OctreeAdler32 & that) const inline
Definition at line 1158 of file octUtils.h.
References code, and len.
operator==()
bool ot::OctreeAdler32::operator== (const OctreeAdler32 & that) const inline
Definition at line 1162 of file octUtils.h.
References code, and len.
Member Data Documentation
code
long unsigned ot::OctreeAdler32::code = adler32(0L, Z_NULL, 0)
Definition at line 1155 of file octUtils.h.
Referenced by ot::checksum_octant(), operator+(), and operator==().
len
size_t ot::OctreeAdler32::len = 0u
Definition at line 1156 of file octUtils.h.
Referenced by ot::checksum_octant(), operator+(), and operator==().
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/octUtils.h