DENDRO: type::StrongIndex< T, Unique > Struct Template Reference
type::StrongIndex< T, Unique > Struct Template Reference
#include <tsort.h>
Public Types
using Type = T
Public Member Functions
T get () const
StrongIndex minus (const T d) const
operator T () const
StrongIndex & operator++ ()
StrongIndex & operator+= (const T d)
StrongIndex plus (const T d) const
StrongIndex (const T i)
Public Attributes
T m_i
Detailed Description
template<typename T, typename Unique>
struct type::StrongIndex< T, Unique >
StrongIndex Based on pattern by Jonathan Boccara: https://www.fluentcpp.com/2016/12/08/strong-types-for-strong-interfaces/
Definition at line 32 of file tsort.h.
Member Typedef Documentation
Type
template<typename T, typename Unique> using type::StrongIndex< T, Unique >::Type = T
Definition at line 34 of file tsort.h.
Constructor & Destructor Documentation
StrongIndex()
template<typename T, typename Unique> type::StrongIndex< T, Unique >::StrongIndex (const T i) inline explicit
Definition at line 38 of file tsort.h.
Referenced by type::StrongIndex< int, struct RotIndex_ >::minus(), and type::StrongIndex< int, struct RotIndex_ >::plus().
Member Function Documentation
get()
template<typename T, typename Unique> T type::StrongIndex< T, Unique >::get () const inline
Definition at line 40 of file tsort.h.
minus()
template<typename T, typename Unique> StrongIndex type::StrongIndex< T, Unique >::minus (const T d) const inline
Definition at line 48 of file tsort.h.
operator T()
template<typename T, typename Unique> type::StrongIndex< T, Unique >::operator T () const inline
Definition at line 39 of file tsort.h.
References type::StrongIndex< T, Unique >::m_i.
operator++()
template<typename T, typename Unique> StrongIndex& type::StrongIndex< T, Unique >::operator++ () inline
Definition at line 43 of file tsort.h.
Referenced by ot::Keeper< X >::adv_store().
operator+=()
template<typename T, typename Unique> StrongIndex& type::StrongIndex< T, Unique >::operator+= (const T d) inline
Definition at line 44 of file tsort.h.
plus()
template<typename T, typename Unique> StrongIndex type::StrongIndex< T, Unique >::plus (const T d) const inline
Definition at line 47 of file tsort.h.
Member Data Documentation
m_i
template<typename T, typename Unique> T type::StrongIndex< T, Unique >::m_i
Definition at line 35 of file tsort.h.
Referenced by type::StrongIndex< int, struct RotIndex_ >::get(), type::StrongIndex< T, Unique >::operator T(), and type::StrongIndex< int, struct RotIndex_ >::operator++().
The documentation for this struct was generated from the following file:
/home/gaurav/Documents/Dendro-KT/include/tsort.h