dim: 3

overwrite_all: true

solvers:
  - &standalone_gmg
    name: "standalone_gmg"
    class: "multigrid"
    type: "GMG"
    ksp: "Stand"

  - &standalone_amg
    name: "standalone_amg"
    class: "multigrid"
    type: "AMG"
    ksp: "Stand"

  - &accelerated_gmg
    name: "accelerated_gmg"
    class: "multigrid"
    type: "GMG"
    ksp: "CG"

  - &accelerated_amg
    name: "accelerated_amg"
    class: "multigrid"
    type: "AMG"
    ksp: "CG"

mesh_recipes:
  - &proxy_adapt
    name: "adapt"
    construct: by_func   # scalar; for vector, use by_vector_func
    degree: 1

  - &uniform
    name: "uniform"
    construct: uniform
    degree: 1

setups:

  ## Adaptive ##

  - mesh_recipe: *proxy_adapt
    interpolation: 1.0e-2
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: true, solver: *standalone_amg}
      - {active: true, solver: *accelerated_amg}

  - mesh_recipe: *proxy_adapt
    interpolation: 5.0e-3
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: false, solver: *standalone_amg}
      - {active: false, solver: *accelerated_amg}

  - mesh_recipe: *proxy_adapt
    interpolation: 1.0e-3
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: false, solver: *standalone_amg}
      - {active: false, solver: *accelerated_amg}

  - mesh_recipe: *proxy_adapt
    interpolation: 1.0e-4
    runs: [{active: true, solver: *standalone_gmg}]

  - mesh_recipe: *proxy_adapt
    interpolation: 5.0e-5
    runs: [{active: false, solver: *standalone_gmg}]

  - mesh_recipe: *proxy_adapt
    interpolation: 1.0e-5
    runs: [{active: false, solver: *standalone_gmg}]


  ## Uniform ##

  - mesh_recipe: *uniform
    max_depth: 3
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: true, solver: *standalone_amg}
      - {active: true, solver: *accelerated_amg}

  - mesh_recipe: *uniform
    max_depth: 4
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: true, solver: *standalone_amg}
      - {active: true, solver: *accelerated_amg}

  - mesh_recipe: *uniform
    max_depth: 5
    runs:
      - {active: true, solver: *standalone_gmg}
      - {active: true, solver: *standalone_amg}
      - {active: true, solver: *accelerated_amg}

  - mesh_recipe: *uniform
    max_depth: 6
    runs: [{active: true, solver: *standalone_gmg}]

  - mesh_recipe: *uniform
    max_depth: 7
    runs: [{active: true, solver: *standalone_gmg}]

  - mesh_recipe: *uniform
    max_depth: 8
    runs: [{active: false, solver: *standalone_gmg}]

  - mesh_recipe: *uniform
    max_depth: 9
    runs: [{active: false, solver: *standalone_gmg}]

